import type { Quiz } from '../../../types';

export const chapter3Quiz: Quiz = {
  id: 'quiz-don-quixote-chapter-3',
  title: 'Chapter 3 Quiz: Dulcinea and Idealism',
  description: 'Test your understanding of courtly love, idealization, and the gap between fantasy and reality',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'Who is Dulcinea del Toboso based on?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A noble lady Don Quixote once met',
        'A peasant woman named Aldonza Lorenzo',
        'A purely fictional character with no real basis',
        'Don Quixote\'s deceased wife',
      ],
      correctAnswer: 'A peasant woman named Aldonza Lorenzo',
      explanation: 'Dulcinea is Don Quixote\'s idealized transformation of Aldonza Lorenzo, a sturdy peasant woman who probably doesn\'t know he exists.',
      relatedLearningPoints: ['dq-lp-ch3-s4-idealization'],
    },
    {
      id: 'q2',
      question: 'What is courtly love?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A historical form of arranged marriage among nobles',
        'A medieval literary convention where knights served ladies from a distance',
        'A type of dance popular in royal courts',
        'A legal code governing romance among aristocrats',
      ],
      correctAnswer: 'A medieval literary convention where knights served ladies from a distance',
      explanation: 'Courtly love was a LITERARY convention, not meant to be lived literally. Don Quixote treats it as real-world instruction, which is part of his madness.',
      relatedLearningPoints: ['dq-lp-ch3-s1-courtly-love', 'dq-lp-ch3-s2-convention'],
    },
    {
      id: 'q3',
      question: 'True or False: Don Quixote has never actually spoken to Dulcinea.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'true',
      explanation: 'True. His "love" is entirely one-sided and imaginary—he\'s in love with an ideal, not a person. This is courtly love taken to its absurd extreme.',
      relatedLearningPoints: ['dq-lp-ch3-s4-projection'],
    },
    {
      id: 'q4',
      question: 'What does Sancho do when Don Quixote asks him to deliver a letter to Dulcinea?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He actually delivers it to Aldonza Lorenzo',
        'He throws the letter away',
        'He invents a fictional meeting and response',
        'He convinces Don Quixote to deliver it himself',
      ],
      correctAnswer: 'He invents a fictional meeting and response',
      explanation: 'Sancho lies, creating a fake story about meeting Dulcinea. This makes him complicit in the fantasy, showing how delusions can be socially sustained.',
      relatedLearningPoints: ['dq-lp-ch3-s8-complicity'],
    },
    {
      id: 'q5',
      question: 'In the "enchanted Dulcinea" episode, what does Sancho do?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He finally introduces Don Quixote to the real Aldonza',
        'He points to peasant girls and claims they\'re Dulcinea under enchantment',
        'He admits Dulcinea doesn\'t exist',
        'He hires an actress to pretend to be Dulcinea',
      ],
      correctAnswer: 'He points to peasant girls and claims they\'re Dulcinea under enchantment',
      explanation: 'In a brilliant reversal, Sancho uses Don Quixote\'s own logic against him—claiming enchanters have transformed Dulcinea, forcing him to see reality as fantasy.',
      relatedLearningPoints: ['dq-lp-ch3-s9-reversal', 'dq-lp-ch3-s9-torment'],
    },
    {
      id: 'q6',
      question: 'What does idealization require according to the novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Deep knowledge of the person being idealized',
        'Ignoring or transforming reality',
        'Mutual agreement between both parties',
        'Historical accuracy',
      ],
      correctAnswer: 'Ignoring or transforming reality',
      explanation: 'Idealization requires erasing the real person to create the perfect fantasy—Don Quixote must ignore everything about Aldonza to see Dulcinea.',
      relatedLearningPoints: ['dq-lp-ch3-s4-idealization'],
    },
    {
      id: 'q7',
      question: 'What is the relationship between Don Quixote and Aldonza Lorenzo?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They are secretly in love',
        'She knows him and rejects his advances',
        'There is no relationship—she doesn\'t know he exists',
        'They were childhood friends',
      ],
      correctAnswer: 'There is no relationship—she doesn\'t know he exists',
      explanation: 'The relationship is entirely one-sided. Don Quixote has created an elaborate romance with someone who is unaware of his existence.',
      relatedLearningPoints: ['dq-lp-ch3-s3-reality'],
    },
    {
      id: 'q8',
      question: 'Why does Don Quixote never actually visit Dulcinea in El Toboso?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The town is too far away',
        'He unconsciously avoids confronting reality',
        'Sancho prevents him',
        'She sends word asking him not to come',
      ],
      correctAnswer: 'He unconsciously avoids confronting reality',
      explanation: 'Don Quixote always finds reasons to postpone the visit—unconsciously protecting his fantasy from the facts that would destroy it.',
      relatedLearningPoints: ['dq-lp-ch3-s5-avoidance'],
    },
    {
      id: 'q9',
      question: 'What does Cervantes suggest about the function of ideals?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Ideals are always harmful and should be abandoned',
        'Ideals can function powerfully even when disconnected from reality',
        'Ideals only work when based on truth',
        'Ideals are irrelevant to actual behavior',
      ],
      correctAnswer: 'Ideals can function powerfully even when disconnected from reality',
      explanation: 'Don Quixote\'s devotion to Dulcinea is genuine and inspires real virtue, despite being based on fantasy. The novel explores this paradox without fully resolving it.',
      relatedLearningPoints: ['dq-lp-ch3-s10-function', 'dq-lp-ch3-s11-necessity'],
    },
    {
      id: 'q10',
      question: 'How does the novel treat the question of whether idealism is admirable or delusional?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It clearly condemns idealism as madness',
        'It clearly celebrates idealism as noble',
        'It maintains deliberate ambiguity, showing both costs and benefits',
        'It ignores the question entirely',
      ],
      correctAnswer: 'It maintains deliberate ambiguity, showing both costs and benefits',
      explanation: 'Cervantes refuses to resolve the tension between idealism and realism—Don Quixote\'s ideals inspire virtue but also cause harm. Readers must grapple with this ambiguity.',
      relatedLearningPoints: ['dq-lp-ch3-s12-tension', 'dq-lp-ch3-s13-ambiguity'],
    },
  ],
};
