import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'quiz-don-quixote-chapter-1',
  title: 'Chapter 1 Quiz: The Knight Errant',
  description: 'Test your understanding of Don Quixote\'s transformation and the beginning of his adventures',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'What causes Alonso Quixano to lose his sanity and become Don Quixote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A traumatic experience in battle',
        'Excessive reading of chivalric romances',
        'A curse from an enchanter',
        'Grief over a lost love',
      ],
      correctAnswer: 'Excessive reading of chivalric romances',
      explanation: 'Don Quixote\'s madness stems from reading chivalric romances obsessively, day and night, until he can no longer distinguish fiction from reality. This makes Cervantes\' satire particularly pointed—literature literally drives him mad.',
      relatedLearningPoints: ['dq-lp-ch1-s1-obsession'],
    },
    {
      id: 'q2',
      question: 'What literary technique does Cervantes use to critique chivalric romances?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Allegory',
        'Parody',
        'Symbolism',
        'Foreshadowing',
      ],
      correctAnswer: 'Parody',
      explanation: 'Cervantes uses parody—imitating the style of chivalric romances while subverting their content. He describes Don Quixote using heroic language while showing the mundane, even pathetic reality.',
      relatedLearningPoints: ['dq-lp-ch1-s2-parody', 'dq-lp-ch1-s2-satire'],
    },
    {
      id: 'q3',
      question: 'True or False: Don Quixote was considered a realistic portrayal of knights in Cervantes\' time.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. By 1605, knights errant were completely obsolete. Cervantes deliberately shows Don Quixote trying to revive a dead past, which is part of the satire—he\'s fighting battles that no longer need fighting.',
      relatedLearningPoints: ['dq-lp-ch1-s3-context'],
    },
    {
      id: 'q4',
      question: 'What does Don Quixote rename his old workhorse?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Excalibur',
        'Rocinante',
        'Pegasus',
        'Thunder',
      ],
      correctAnswer: 'Rocinante',
      explanation: 'Rocinante is a pun in Spanish—"rocín" means workhorse and "ante" means before, suggesting it was a workhorse before but is now something greater (though obviously it isn\'t). The name itself is a joke.',
      relatedLearningPoints: [],
    },
    {
      id: 'q5',
      question: 'Who is the real person behind Don Quixote\'s imagined lady "Dulcinea del Toboso"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A noble lady who rejected him',
        'A peasant woman named Aldonza Lorenzo',
        'His deceased wife',
        'A purely fictional creation with no real basis',
      ],
      correctAnswer: 'A peasant woman named Aldonza Lorenzo',
      explanation: 'Dulcinea is based on Aldonza Lorenzo, a peasant woman from El Toboso who probably doesn\'t know Don Quixote exists. He transforms her in his mind into an impossibly perfect noble lady.',
      relatedLearningPoints: ['dq-lp-ch1-s4-dulcinea'],
    },
    {
      id: 'q6',
      question: 'How do others react to Don Quixote\'s request for a dubbing ceremony?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They take him seriously and perform a proper ceremony',
        'They refuse and send him away',
        'They humor him with a mock ceremony for their amusement',
        'They try to have him arrested for madness',
      ],
      correctAnswer: 'They humor him with a mock ceremony for their amusement',
      explanation: 'The innkeeper performs a fake dubbing ceremony, finding the whole situation amusing. This establishes a pattern—people profit from or are entertained by Don Quixote\'s madness rather than helping him.',
      relatedLearningPoints: ['dq-lp-ch1-s6-comedy', 'dq-lp-ch1-s8-ceremony'],
    },
    {
      id: 'q7',
      question: 'What happens to Don Quixote during his encounter with the merchants?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He defeats them in combat and continues his journey',
        'He convinces them of Dulcinea\'s beauty and they let him pass',
        'Rocinante stumbles, he falls, and a servant beats him with his own lance',
        'He realizes they are right and returns home voluntarily',
      ],
      correctAnswer: 'Rocinante stumbles, he falls, and a servant beats him with his own lance',
      explanation: 'Don Quixote\'s first "adventure" ends in humiliation—his horse stumbles, he crashes to the ground, and he\'s beaten with his own broken lance. This establishes the pattern of reality defeating his chivalric fantasies through physical consequences.',
      relatedLearningPoints: ['dq-lp-ch1-s9-consequences'],
    },
    {
      id: 'q8',
      question: 'Why is Don Quixote\'s transformation considered both comic and tragic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It\'s funny to watch but he gets physically hurt',
        'His delusions are absurd but stem from a deep need for meaning',
        'He makes people laugh but ultimately dies',
        'His costume is ridiculous but his goals are noble',
      ],
      correctAnswer: 'His delusions are absurd but stem from a deep need for meaning',
      explanation: 'The novel balances comedy and tragedy—Don Quixote is ridiculous, but his madness comes from a genuine human need for purpose and meaning. We laugh at him while recognizing ourselves in his desires.',
      relatedLearningPoints: ['dq-lp-ch1-s3-madness'],
    },
    {
      id: 'q9',
      question: 'What social context makes Don Quixote\'s attempt to be a knight particularly absurd?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Knights were considered primitive and barbaric',
        'Knights had been made obsolete by firearms and changing politics',
        'Becoming a knight required royal permission',
        'All the best knights had already died in recent wars',
      ],
      correctAnswer: 'Knights had been made obsolete by firearms and changing politics',
      explanation: 'By the early 1600s, gunpowder weapons and centralized governments had ended the age of chivalry. Don Quixote is trying to revive something dead for over a century—part of Cervantes\' satire.',
      relatedLearningPoints: ['dq-lp-ch1-s3-context', 'dq-lp-ch1-s7-obsolete'],
    },
    {
      id: 'q10',
      question: 'According to the novel, what is the relationship between reading and reality?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Reading helps us understand reality better',
        'Reading and reality are completely separate',
        'Excessive reading can distort our perception of reality',
        'Reading has no effect on how we see the world',
      ],
      correctAnswer: 'Excessive reading can distort our perception of reality',
      explanation: 'The novel suggests that consuming too much fiction without critical distance can warp our perception of reality—a surprisingly modern concern about media consumption.',
      relatedLearningPoints: ['dq-lp-ch1-s1-obsession'],
    },
  ],
};
