import type { Quiz } from '../../../types';

export const chapter5Quiz: Quiz = {
  id: 'quiz-don-quixote-chapter-5',
  title: 'Chapter 5 Quiz: The Final Journey',
  description: 'Test your understanding of Don Quixote\'s defeat, return to sanity, and the novel\'s conclusion',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'Who is the Knight of the White Moon in reality?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A real knight seeking glory',
        'Sansón Carrasco in disguise',
        'Don Quixote\'s imagination',
        'An agent of the Duke',
      ],
      correctAnswer: 'Sansón Carrasco in disguise',
      explanation: 'The bachelor Sansón Carrasco disguises himself to trick Don Quixote into returning home—a well-meaning intervention using Don Quixote\'s own beliefs against him.',
      relatedLearningPoints: ['dq-lp-ch5-s1-intervention'],
    },
    {
      id: 'q2',
      question: 'Why is Don Quixote\'s defeat by the Knight of the White Moon particularly devastating?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is physically injured worse than ever before',
        'He loses according to his own chivalric code',
        'All his friends witness the defeat',
        'Rocinante is killed in the battle',
      ],
      correctAnswer: 'He loses according to his own chivalric code',
      explanation: 'The defeat is both physical and psychological—Don Quixote is bound by honor to obey the victor\'s terms. He\'s defeated by the very rules he cherishes.',
      relatedLearningPoints: ['dq-lp-ch5-s1-defeat'],
    },
    {
      id: 'q3',
      question: 'True or False: Sancho is happy when Don Quixote returns to sanity.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. Sancho is heartbroken—for him, the return to sanity IS a kind of death. The man he loved (Don Quixote) has been replaced by a stranger (Alonso Quixano).',
      relatedLearningPoints: ['dq-lp-ch5-s2-loyalty', 'dq-lp-ch5-s9-perspective'],
    },
    {
      id: 'q4',
      question: 'What happens to Don Quixote\'s spirit during the journey home?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He becomes more determined to continue',
        'He falls into melancholic silence and defeat',
        'He plans new adventures',
        'He becomes angry and bitter',
      ],
      correctAnswer: 'He falls into melancholic silence and defeat',
      explanation: 'The return journey is marked by profound melancholy—Don Quixote has lost not just the battle but his entire sense of purpose and identity.',
      relatedLearningPoints: ['dq-lp-ch5-s3-melancholy', 'dq-lp-ch5-s3-end'],
    },
    {
      id: 'q5',
      question: 'What metafictional element appears in Part Two of the novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Don Quixote writes his own story',
        'Characters have read Part One and know Don Quixote as a fictional character',
        'The narrator reveals himself as Cervantes',
        'The novel ends abruptly without conclusion',
      ],
      correctAnswer: 'Characters have read Part One and know Don Quixote as a fictional character',
      explanation: 'In Part Two, characters treat Don Quixote as both a real person and a fictional character they\'ve read about—blurring the boundary between fiction and reality.',
      relatedLearningPoints: ['dq-lp-ch5-s6-metafiction', 'dq-lp-ch5-s8-meta'],
    },
    {
      id: 'q6',
      question: 'What does Don Quixote renounce on his deathbed?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His family and friends',
        'His property and wealth',
        'His chivalric identity and beliefs',
        'His religion',
      ],
      correctAnswer: 'His chivalric identity and beliefs',
      explanation: 'Don Quixote renounces his entire fantasy—admitting Dulcinea was a peasant girl, windmills were just windmills, and his quest was madness.',
      relatedLearningPoints: ['dq-lp-ch5-s9-tragedy'],
    },
    {
      id: 'q7',
      question: 'How is Don Quixote\'s return to sanity presented in the novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'As an unambiguous triumph',
        'As a tragic defeat',
        'As both triumph and tragedy simultaneously',
        'As irrelevant to the story',
      ],
      correctAnswer: 'As both triumph and tragedy simultaneously',
      explanation: 'The novel maintains ambiguity—some characters celebrate the return to sanity while others (like Sancho) mourn it. Cervantes doesn\'t resolve whether it\'s good or bad.',
      relatedLearningPoints: ['dq-lp-ch5-s9-tragedy', 'dq-lp-ch5-s9-perspective'],
    },
    {
      id: 'q8',
      question: 'What does Cervantes suggest about the relationship between life and legacy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Only those who live safely are remembered',
        'Stories can grant a kind of immortality',
        'Legacy doesn\'t matter compared to living well',
        'Only nobility achieves lasting fame',
      ],
      correctAnswer: 'Stories can grant a kind of immortality',
      explanation: 'Don Quixote (the character) achieves immortality through literature—living on 400+ years after Cervantes wrote him. Fiction grants lasting life that reality cannot.',
      relatedLearningPoints: ['dq-lp-ch5-s8-immortality'],
    },
    {
      id: 'q9',
      question: 'What is the significance of the final image—Sancho seeing the windmills and thinking they look like giants?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Sancho has gone mad too',
        'Don Quixote\'s vision survives in those who loved him',
        'Sancho is mocking his dead master',
        'The windmills actually were giants',
      ],
      correctAnswer: 'Don Quixote\'s vision survives in those who loved him',
      explanation: 'The ending suggests that Don Quixote\'s idealism lives on—Sancho has inherited the ability to see possibility beyond mere facts, showing that the madness has been transmuted into wisdom.',
      relatedLearningPoints: ['dq-lp-ch5-s13-legacy-lives', 'dq-lp-ch5-s13-ending'],
    },
    {
      id: 'q10',
      question: 'What central question does the novel leave unresolved?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Whether Don Quixote was truly mad',
        'Whether idealism or realism is better',
        'Whether Dulcinea was real',
        'Whether Sancho got his island',
      ],
      correctAnswer: 'Whether idealism or realism is better',
      explanation: 'Cervantes deliberately leaves this unresolved—forcing readers to grapple with whether Don Quixote\'s madness was worse than Alonso\'s sanity. There\'s no simple answer.',
      relatedLearningPoints: ['dq-lp-ch5-s11-ambiguity', 'dq-lp-ch5-s13-question'],
    },
  ],
};
