import type { Quiz } from '../../../types';

export const chapter2Quiz: Quiz = {
  id: 'quiz-don-quixote-chapter-2',
  title: 'Chapter 2 Quiz: Windmills and Reality',
  description: 'Test your knowledge of the famous windmill episode and Sancho Panza\'s introduction',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'Why does Sancho Panza agree to become Don Quixote\'s squire?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He admires Don Quixote\'s nobility',
        'He is promised governorship of an island',
        'He wants to escape his debts',
        'He believes in the chivalric cause',
      ],
      correctAnswer: 'He is promised governorship of an island',
      explanation: 'Sancho joins for purely practical reasons—Don Quixote promises him governorship of an island they\'ll conquer. This mercenary beginning makes Sancho\'s eventual genuine loyalty more meaningful.',
      relatedLearningPoints: ['dq-lp-ch2-s2-sancho'],
    },
    {
      id: 'q2',
      question: 'What does Don Quixote see when he looks at the windmills?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Windmills that he pretends are giants',
        'Giants that he genuinely believes are real',
        'Enchanted structures that change form',
        'Symbols of his quest',
      ],
      correctAnswer: 'Giants that he genuinely believes are real',
      explanation: 'Don Quixote GENUINELY sees giants—his delusion is complete and sincere. This distinguishes him from someone merely pretending; he truly cannot see reality.',
      relatedLearningPoints: ['dq-lp-ch2-s5-perception'],
    },
    {
      id: 'q3',
      question: 'What excuse does Don Quixote give for his defeat by the windmill?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He admits they were windmills after all',
        'He blames enchantments',
        'He claims Rocinante stumbled',
        'He says he wasn\'t truly defeated',
      ],
      correctAnswer: 'He blames enchantments',
      explanation: 'Don Quixote can\'t admit error—he claims the enchanter Friston transformed the giants into windmills to rob him of glory. This psychological defense mechanism protects his worldview.',
      relatedLearningPoints: ['dq-lp-ch2-s4-enchanter', 'dq-lp-ch2-s8-denial'],
    },
    {
      id: 'q4',
      question: 'What does Sancho represent in contrast to Don Quixote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Ignorance vs. education',
        'Evil vs. good',
        'Pragmatism vs. idealism',
        'Cowardice vs. bravery',
      ],
      correctAnswer: 'Pragmatism vs. idealism',
      explanation: 'Sancho embodies practical, earthly wisdom while Don Quixote represents impractical idealism. Neither perspective is presented as entirely right or wrong.',
      relatedLearningPoints: ['dq-lp-ch2-s3-contrast', 'dq-lp-ch2-s3-partnership'],
    },
    {
      id: 'q5',
      question: 'True or False: Don Quixote learns from his defeats and stops attacking innocent targets.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. Don Quixote doesn\'t learn—his delusions escalate. After windmills come sheep as armies, then a brass basin as a magical helmet. Each failure reinforces rather than challenges his beliefs.',
      relatedLearningPoints: ['dq-lp-ch2-s9-escalation'],
    },
    {
      id: 'q6',
      question: 'What has "tilting at windmills" come to mean in English?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Being persistent against all odds',
        'Fighting imaginary enemies or pursuing impossible goals',
        'Working hard at a difficult task',
        'Facing one\'s fears courageously',
      ],
      correctAnswer: 'Fighting imaginary enemies or pursuing impossible goals',
      explanation: 'The phrase now means fighting battles that don\'t exist or pursuing impossible objectives—showing how the novel\'s most famous scene entered common language.',
      relatedLearningPoints: ['dq-lp-ch2-s5-metaphor'],
    },
    {
      id: 'q7',
      question: 'How does Sancho\'s role function in the narrative?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He serves as comic relief',
        'He represents the reader\'s perspective on the madness',
        'He exists only to obey Don Quixote',
        'He provides historical context',
      ],
      correctAnswer: 'He represents the reader\'s perspective on the madness',
      explanation: 'Sancho voices what we\'re thinking—expressing frustration, disbelief, and concern. His presence makes us feel less alone in seeing the absurdity.',
      relatedLearningPoints: ['dq-lp-ch2-s4-witness', 'dq-lp-ch2-s8-sancho-role'],
    },
    {
      id: 'q8',
      question: 'What pattern emerges in Don Quixote\'s misinterpretations?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He randomly misidentifies things',
        'He always sees romantic/chivalric possibilities instead of prosaic reality',
        'He deliberately lies about what he sees',
        'His vision is actually impaired',
      ],
      correctAnswer: 'He always sees romantic/chivalric possibilities instead of prosaic reality',
      explanation: 'Don Quixote\'s delusions are systematic—he consistently transforms mundane reality into chivalric romance. Inns become castles, windmills become giants, sheep become armies.',
      relatedLearningPoints: ['dq-lp-ch2-s10-pattern', 'dq-lp-ch2-s10-perception'],
    },
    {
      id: 'q9',
      question: 'Why is the windmill episode considered the most iconic scene in the novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It\'s the funniest moment',
        'It perfectly captures the collision between romantic idealism and reality',
        'It\'s the only time Don Quixote gets seriously hurt',
        'It\'s based on a true historical event',
      ],
      correctAnswer: 'It perfectly captures the collision between romantic idealism and reality',
      explanation: 'The windmill scene crystallizes the novel\'s central theme—the clash between how Don Quixote wants the world to be and how it actually is. It\'s comedy and tragedy in one image.',
      relatedLearningPoints: ['dq-lp-ch2-s5-iconic', 'dq-lp-ch2-s7-reality'],
    },
    {
      id: 'q10',
      question: 'What does Don Quixote do after being beaten by the merchants?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He admits defeat and goes home',
        'He finds excuses and continues his quest',
        'He challenges them to another fight',
        'He seeks revenge on them',
      ],
      correctAnswer: 'He finds excuses and continues his quest',
      explanation: 'Don Quixote cannot accept defeat—he always finds explanations (enchantments, bad luck) that allow him to continue believing in his quest. This persistence is both admirable and tragic.',
      relatedLearningPoints: ['dq-lp-ch2-s9-escalation'],
    },
  ],
};
