import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-don-quixote-chapter-4',
  title: 'Chapter 4 Quiz: Sancho\'s Wisdom',
  description: 'Test your understanding of Sancho\'s character development and his governorship',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'How does Sancho change throughout his journey with Don Quixote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He becomes more educated and literate',
        'He becomes as mad as Don Quixote',
        'He develops wisdom while maintaining his practical nature',
        'He becomes more cynical and bitter',
      ],
      correctAnswer: 'He develops wisdom while maintaining his practical nature',
      explanation: 'Sancho undergoes genuine character development—he gains wisdom and broader perspective without losing his practical, earthy nature. He synthesizes idealism and pragmatism.',
      relatedLearningPoints: ['dq-lp-ch4-s1-growth', 'dq-lp-ch4-s1-synthesis'],
    },
    {
      id: 'q2',
      question: 'What do Sancho\'s proverbs represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His lack of education and intelligence',
        'Folk wisdom accumulated over generations',
        'Comic relief with no deeper meaning',
        'His attempt to sound like Don Quixote',
      ],
      correctAnswer: 'Folk wisdom accumulated over generations',
      explanation: 'Proverbs encode the practical wisdom of ordinary people—Sancho\'s peasant knowledge has its own validity alongside Don Quixote\'s book learning.',
      relatedLearningPoints: ['dq-lp-ch4-s2-proverbs', 'dq-lp-ch4-s3-folk-wisdom'],
    },
    {
      id: 'q3',
      question: 'True or False: The Duke and Duchess treat Don Quixote and Sancho with genuine respect.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. The nobles exploit them for entertainment, creating elaborate pranks and treating them as curiosities rather than people—revealing class cruelty.',
      relatedLearningPoints: ['dq-lp-ch4-s6-mockery', 'dq-lp-ch4-s7-exploitation'],
    },
    {
      id: 'q4',
      question: 'What happens when Sancho becomes governor of Barataria?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He fails miserably and is quickly removed',
        'He proves corrupt and greedy',
        'He delivers surprisingly wise and just judgments',
        'He immediately resigns in fear',
      ],
      correctAnswer: 'He delivers surprisingly wise and just judgments',
      explanation: 'Sancho surprises everyone with his wise, fair judgments—demonstrating that wisdom doesn\'t require education or noble birth.',
      relatedLearningPoints: ['dq-lp-ch4-s8-wisdom', 'dq-lp-ch4-s8-subversion'],
    },
    {
      id: 'q5',
      question: 'What does Sancho\'s success as governor suggest about intelligence and class?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Only nobles are fit to govern',
        'Education is the only path to wisdom',
        'Practical wisdom can equal or surpass book learning',
        'Anyone can govern if given the chance',
      ],
      correctAnswer: 'Practical wisdom can equal or surpass book learning',
      explanation: 'The Barataria episode is a radical class critique—showing that a peasant\'s practical intelligence can exceed educated nobles\' theoretical knowledge.',
      relatedLearningPoints: ['dq-lp-ch4-s9-intelligence', 'dq-lp-ch4-s9-class'],
    },
    {
      id: 'q6',
      question: 'Why does Sancho ultimately resign his governorship?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is forced out by rebellion',
        'He realizes power brings stress and he values freedom more',
        'Don Quixote orders him to return',
        'He is offered a better position elsewhere',
      ],
      correctAnswer: 'He realizes power brings stress and he values freedom more',
      explanation: 'Sancho discovers that achieving his dream is disappointing—he values freedom and authentic friendship over status and responsibility.',
      relatedLearningPoints: ['dq-lp-ch4-s11-realization', 'dq-lp-ch4-s11-freedom'],
    },
    {
      id: 'q7',
      question: 'What does Sancho mean when he says "I came naked into this government, and naked I leave it"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He stole nothing during his governorship',
        'He gained nothing material but much experience',
        'He was humiliated by the nobles',
        'He lost everything he owned',
      ],
      correctAnswer: 'He gained nothing material but much experience',
      explanation: 'Sancho indicates that material gain wasn\'t the real reward—the experience itself, and the wisdom gained, was what mattered.',
      relatedLearningPoints: ['dq-lp-ch4-s12-choice'],
    },
    {
      id: 'q8',
      question: 'What transformation occurs in Sancho\'s loyalty to Don Quixote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It weakens as he gains wisdom',
        'It changes from mercenary to genuine friendship',
        'It remains purely transactional throughout',
        'It becomes based on pity rather than respect',
      ],
      correctAnswer: 'It changes from mercenary to genuine friendship',
      explanation: 'Sancho initially follows for the promised island but develops genuine love and loyalty—the relationship becomes more important than any material reward.',
      relatedLearningPoints: ['dq-lp-ch4-s4-loyalty', 'dq-lp-ch4-s13-friendship'],
    },
    {
      id: 'q9',
      question: 'How does Sancho\'s approach to governance differ from traditional learned judges?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He relies on legal precedents and codes',
        'He uses practical tests and common sense',
        'He consults with Don Quixote on every case',
        'He decides cases randomly',
      ],
      correctAnswer: 'He uses practical tests and common sense',
      explanation: 'Sancho listens carefully, asks practical questions, and uses common sense (like the walking stick trick) rather than legal theory—often more effective.',
      relatedLearningPoints: ['dq-lp-ch4-s10-leadership'],
    },
    {
      id: 'q10',
      question: 'What does Sancho ultimately learn is most valuable?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Wealth and status',
        'Education and knowledge',
        'Freedom and authentic relationships',
        'Power and influence',
      ],
      correctAnswer: 'Freedom and authentic relationships',
      explanation: 'Sancho discovers that freedom and genuine friendship with Don Quixote matter more than status, comfort, or material success.',
      relatedLearningPoints: ['dq-lp-ch4-s13-freedom', 'dq-lp-ch4-s13-self'],
    },
  ],
};
