import type { Quiz } from '../../../types';

export const finalQuiz: Quiz = {
  id: 'quiz-don-quixote-final',
  title: 'Final Quiz: Don Quixote - Complete Adventure',
  description: 'Comprehensive assessment of your understanding of the entire Don Quixote adventure',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'What is the primary literary technique Cervantes uses throughout Don Quixote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Allegory',
        'Satire and parody',
        'Stream of consciousness',
        'Magical realism',
      ],
      correctAnswer: 'Satire and parody',
      explanation: 'Cervantes satirizes chivalric romances by parodying their conventions—imitating their style while subverting their content through Don Quixote\'s absurd adventures.',
      relatedLearningPoints: [],
    },
    {
      id: 'q2',
      question: 'How does the relationship between Don Quixote and Sancho Panza evolve?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'From friendship to enmity',
        'From transactional arrangement to genuine friendship',
        'From equality to master-servant hierarchy',
        'It remains unchanged throughout',
      ],
      correctAnswer: 'From transactional arrangement to genuine friendship',
      explanation: 'Their relationship transforms from a mercenary contract (Sancho wanting the island) to deep, mutual friendship that transcends material reward and social hierarchy.',
      relatedLearningPoints: [],
    },
    {
      id: 'q3',
      question: 'What does Don Quixote represent in the novel\'s central thematic conflict?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Ignorance',
        'Evil',
        'Idealism',
        'Nobility',
      ],
      correctAnswer: 'Idealism',
      explanation: 'Don Quixote embodies idealism—the belief that the world should match our ideals. Sancho represents pragmatism. The novel explores the tension between these perspectives.',
      relatedLearningPoints: [],
    },
    {
      id: 'q4',
      question: 'True or False: Cervantes clearly condemns Don Quixote\'s madness as entirely negative.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. The novel maintains ambiguity—Don Quixote\'s madness brings both harm and beauty, suffering and meaning. Cervantes refuses to simply condemn or celebrate it.',
      relatedLearningPoints: [],
    },
    {
      id: 'q5',
      question: 'What social critique does Sancho\'s governorship of Barataria represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A criticism of peasant ignorance',
        'A challenge to class assumptions about leadership and wisdom',
        'A defense of aristocratic privilege',
        'A celebration of education over experience',
      ],
      correctAnswer: 'A challenge to class assumptions about leadership and wisdom',
      explanation: 'Sancho\'s wise governance challenges the belief that only nobles can lead—showing that practical wisdom can equal or surpass book learning.',
      relatedLearningPoints: [],
    },
    {
      id: 'q6',
      question: 'What does the "Dulcinea" storyline reveal about idealization?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Idealization strengthens relationships',
        'Idealization requires ignoring reality',
        'Idealization is always harmful',
        'Idealization is impossible',
      ],
      correctAnswer: 'Idealization requires ignoring reality',
      explanation: 'Don Quixote must erase the real Aldonza Lorenzo to create the perfect Dulcinea—showing how idealization functions by transforming or ignoring actual persons.',
      relatedLearningPoints: [],
    },
    {
      id: 'q7',
      question: 'What metafictional technique does Cervantes use in Part Two?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Breaking the fourth wall directly',
        'Characters have read Part One and discuss Don Quixote as a fictional character',
        'The narrator admits the story is false',
        'Don Quixote reads his own adventures',
      ],
      correctAnswer: 'Characters have read Part One and discuss Don Quixote as a fictional character',
      explanation: 'In Part Two, characters treat Don Quixote as both real and fictional—blurring the boundary between literature and reality, making the novel self-aware.',
      relatedLearningPoints: [],
    },
    {
      id: 'q8',
      question: 'Why is Don Quixote\'s return to sanity presented as potentially tragic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He becomes mean and bitter',
        'He loses his purpose and dies soon after',
        'His family rejects him',
        'He becomes poor and homeless',
      ],
      correctAnswer: 'He loses his purpose and dies soon after',
      explanation: 'When Don Quixote becomes sane, he loses the meaning and purpose his madness provided—suggesting that his fantasy, while false, was psychologically necessary.',
      relatedLearningPoints: [],
    },
    {
      id: 'q9',
      question: 'What has "tilting at windmills" come to mean culturally?',
      type: 'self-assessment',
      points: 10,
      modelAnswer: 'The phrase "tilting at windmills" has become a cultural idiom meaning to fight imaginary enemies or to pursue impossible, impractical goals. It refers to someone who attacks problems that may not actually exist or who persists in hopeless endeavors despite obvious futility. The phrase captures Don Quixote\'s tendency to see threats where there are none and to pursue chivalric quests in a world where chivalry is dead. It shows the novel\'s lasting cultural influence—a single episode has become a universal metaphor for idealistic but misguided effort.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Explained that it means fighting imaginary enemies or non-existent problems',
          points: 3,
        },
        {
          id: 'crit2',
          text: 'Explained that it means pursuing impossible or impractical goals',
          points: 3,
        },
        {
          id: 'crit3',
          text: 'Connected the phrase to Don Quixote\'s character or the novel\'s cultural influence',
          points: 4,
        },
      ],
      explanation: 'The phrase now means fighting battles that don\'t exist or pursuing impossible objectives—showing the novel\'s lasting cultural influence.',
      relatedLearningPoints: [],
    },
    {
      id: 'q10',
      question: 'What form of wisdom does Sancho represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Academic and theoretical',
        'Practical and experiential',
        'Religious and spiritual',
        'Artistic and creative',
      ],
      correctAnswer: 'Practical and experiential',
      explanation: 'Sancho embodies practical wisdom gained through lived experience—using proverbs, common sense, and folk knowledge rather than book learning.',
      relatedLearningPoints: [],
    },
    {
      id: 'q11',
      question: 'How does Cervantes treat the tension between idealism and realism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He resolves it in favor of idealism',
        'He resolves it in favor of realism',
        'He maintains deliberate ambiguity, showing value and cost in both',
        'He ignores the tension entirely',
      ],
      correctAnswer: 'He maintains deliberate ambiguity, showing value and cost in both',
      explanation: 'The novel refuses simple resolution—showing that idealism inspires but can harm, while realism is truthful but can be empty. Both perspectives have merit.',
      relatedLearningPoints: [],
    },
    {
      id: 'q12',
      question: 'What does the novel suggest about the relationship between fiction and reality?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Fiction corrupts our understanding of reality',
        'Fiction and reality are completely separate',
        'Fiction can shape reality and grant a kind of truth',
        'Reality is always superior to fiction',
      ],
      correctAnswer: 'Fiction can shape reality and grant a kind of truth',
      explanation: 'Don Quixote achieves immortality through fiction—living on 400+ years in literature. The novel suggests fiction can be "truer" than mere fact in important ways.',
      relatedLearningPoints: [],
    },
    {
      id: 'q13',
      question: 'Why is Don Quixote considered the first modern novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It was written in modern language',
        'It features realistic psychological depth and self-aware narration',
        'It was the first book printed',
        'It was the longest novel of its time',
      ],
      correctAnswer: 'It features realistic psychological depth and self-aware narration',
      explanation: 'Don Quixote pioneered realistic characterization, psychological complexity, and metafictional awareness—establishing conventions that define the modern novel.',
      relatedLearningPoints: [],
    },
    {
      id: 'q14',
      question: 'What does Sancho learn by the end of the novel?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That Don Quixote was completely wrong',
        'That power and status are most important',
        'That freedom and authentic relationship matter more than material success',
        'That idealism always fails',
      ],
      correctAnswer: 'That freedom and authentic relationship matter more than material success',
      explanation: 'Sancho achieves his dream of governorship but chooses to resign, valuing freedom and friendship with Don Quixote over power and status.',
      relatedLearningPoints: [],
    },
    {
      id: 'q15',
      question: 'What is the significance of the novel\'s final image—Sancho seeing giants in the windmills?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Sancho has become as mad as Don Quixote',
        'Don Quixote\'s vision and idealism survive in those who loved him',
        'The windmills are actually dangerous',
        'Sancho is hallucinating from grief',
      ],
      correctAnswer: 'Don Quixote\'s vision and idealism survive in those who loved him',
      explanation: 'The ending suggests Don Quixote\'s legacy lives on—his ability to see possibility beyond mere facts has been inherited by Sancho, showing that idealism can endure beyond the idealist.',
      relatedLearningPoints: [],
    },
  ],
};
