import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'edda-ch4-quiz',
  title: 'Chapter 4: The Death of Baldr Quiz',
  description: 'Test your understanding of the tragic myth of Baldr\'s death and its significance in Norse mythology.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1',
      question: 'What prompted Frigg to seek oaths from all things to protect Baldr?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Baldr was injured in battle',
        'Baldr had prophetic dreams of his own death',
        'Odin commanded her to do so',
        'Loki threatened Baldr directly',
      ],
      correctAnswer: 'Baldr had prophetic dreams of his own death',
      explanation: 'Baldr suffered from terrible dreams that foretold his death. In Norse belief, prophetic dreams were taken seriously as glimpses of fate, prompting Frigg to take action to protect her son.',
      relatedLearningPoints: ['edda-ch4-lp-1', 'edda-ch4-lp-3'],
    },
    {
      id: 'q2',
      question: 'Which plant did Frigg overlook when extracting oaths?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Holly',
        'Mistletoe',
        'Oak',
        'Ivy',
      ],
      correctAnswer: 'Mistletoe',
      explanation: 'Frigg thought the mistletoe was too young and harmless to pose a threat, so she didn\'t bother to extract an oath from it. This oversight became the fatal vulnerability that Loki exploited.',
      relatedLearningPoints: ['edda-ch4-lp-8', 'edda-ch4-lp-13'],
    },
    {
      id: 'q3',
      question: 'How did Loki discover the secret of the mistletoe?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He spied on Frigg from the shadows',
        'Odin accidentally revealed it',
        'He disguised himself as an old woman and questioned Frigg',
        'He tortured one of the gods for information',
      ],
      correctAnswer: 'He disguised himself as an old woman and questioned Frigg',
      explanation: 'Loki used his shapeshifting abilities to disguise himself as a harmless old woman and cunningly extracted the information from Frigg through seemingly innocent conversation.',
      relatedLearningPoints: ['edda-ch4-lp-7'],
    },
    {
      id: 'q4',
      question: 'Who actually threw the mistletoe dart that killed Baldr?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Loki himself',
        'Höðr, Baldr\'s blind brother',
        'Thor in a rage',
        'An unknown assassin',
      ],
      correctAnswer: 'Höðr, Baldr\'s blind brother',
      explanation: 'Loki tricked Höðr, Baldr\'s blind brother, into throwing the mistletoe dart by claiming to help him participate in the throwing game. This made the tragedy even more cruel, as Höðr was an innocent tool of murder.',
      relatedLearningPoints: ['edda-ch4-lp-14'],
    },
    {
      id: 'q5',
      question: 'What type of funeral did the gods give Baldr?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was buried in a simple grave',
        'He was placed in a ship that was set ablaze and sent to sea',
        'He was cremated on a mountaintop',
        'He was entombed in a stone chamber',
      ],
      correctAnswer: 'He was placed in a ship that was set ablaze and sent to sea',
      explanation: 'Baldr received an elaborate ship funeral on his vessel Ringhorn, reflecting the historical Viking practice of ship burials for the most important members of society. This honored his status as the most beloved of the gods.',
      relatedLearningPoints: ['edda-ch4-lp-16', 'edda-ch4-lp-18'],
    },
    {
      id: 'q6',
      question: 'What condition did Hel set for releasing Baldr from her realm?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The gods must pay a great treasure',
        'Odin must sacrifice his other eye',
        'All things in the nine worlds must weep for Baldr',
        'Thor must defeat her in single combat',
      ],
      correctAnswer: 'All things in the nine worlds must weep for Baldr',
      explanation: 'Hel agreed to release Baldr only if everything in existence—living and dead, animate and inanimate—wept for him. This impossible condition reflected the finality of death in Norse belief.',
      relatedLearningPoints: ['edda-ch4-lp-21'],
    },
    {
      id: 'q7',
      question: 'Who refused to weep for Baldr, preventing his return?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Frigg in her grief',
        'The giantess Þökk (likely Loki in disguise)',
        'Hel herself',
        'The Norns',
      ],
      correctAnswer: 'The giantess Þökk (likely Loki in disguise)',
      explanation: 'A giantess named Þökk, whom the gods suspected was Loki in another disguise, refused to weep for Baldr. Because not all things mourned him, Hel\'s condition was not met, and Baldr remained in her realm.',
      relatedLearningPoints: ['edda-ch4-lp-22', 'edda-ch4-lp-23'],
    },
    {
      id: 'q8',
      question: 'How was Loki punished for his role in Baldr\'s death?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was executed immediately',
        'He was banished from all nine worlds',
        'He was bound beneath the earth with serpent venom dripping on his face',
        'He was forced to serve in Hel\'s realm',
      ],
      correctAnswer: 'He was bound beneath the earth with serpent venom dripping on his face',
      explanation: 'The gods bound Loki with chains made from his son\'s entrails and placed him beneath a serpent whose venom drips onto his face. His wife Sigyn catches the poison, but when she must empty the bowl, his writhing causes earthquakes.',
      relatedLearningPoints: ['edda-ch4-lp-26'],
    },
    {
      id: 'q9',
      question: 'What does Baldr\'s death represent in the larger narrative of Norse mythology?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The triumph of good over evil',
        'The beginning of the countdown to Ragnarök',
        'The strengthening of the gods\' power',
        'A minor setback with no lasting consequences',
      ],
      correctAnswer: 'The beginning of the countdown to Ragnarök',
      explanation: 'Baldr\'s death is the pivotal event that sets the apocalyptic events of Ragnarök in motion. It marks the end of the golden age of the gods and the beginning of their inevitable downfall.',
      relatedLearningPoints: ['edda-ch4-lp-15', 'edda-ch4-lp-27'],
    },
    {
      id: 'q10',
      question: 'What Norse concept is central to the inevitability of Baldr\'s death?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Valhalla (hall of the slain)',
        'Wyrd (fate)',
        'Ragnarök (apocalypse)',
        'Hamingja (luck)',
      ],
      correctAnswer: 'Wyrd (fate)',
      explanation: 'The concept of wyrd or fate is central to the myth. Despite all efforts to prevent it, Baldr\'s death was fated to occur. This reflects the Norse belief that even gods cannot escape destiny.',
      relatedLearningPoints: ['edda-ch4-lp-10', 'edda-ch4-lp-27'],
    },
    {
      id: 'q11',
      question: 'What transformation does Loki undergo in this myth?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'From god to mortal',
        'From trickster to malicious villain',
        'From villain to hero',
        'From giant to god',
      ],
      correctAnswer: 'From trickster to malicious villain',
      explanation: 'Baldr\'s death marks Loki\'s transformation from a clever trickster whose pranks were sometimes helpful into a truly evil figure. This shift foreshadows his role as leader of the forces of chaos at Ragnarök.',
      relatedLearningPoints: ['edda-ch4-lp-12'],
    },
    {
      id: 'q12',
      question: 'True or False: The gods were able to overcome fate and bring Baldr back to life.',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'False. Despite their efforts and Hermóðr\'s journey to Hel, the gods could not bring Baldr back because Þökk refused to weep. This emphasizes the Norse belief in the finality of death and the power of fate over even the gods.',
      relatedLearningPoints: ['edda-ch4-lp-23', 'edda-ch4-lp-27'],
    },
    {
      id: 'q13',
      question: 'According to the historical source by Ahmad ibn Fadlan, what did Vikings include in burial rituals?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Only the person\'s clothing',
        'Weapons, horses, and valuable possessions',
        'Books and scrolls',
        'Nothing but the body',
      ],
      correctAnswer: 'Weapons, horses, and valuable possessions',
      explanation: 'Ibn Fadlan\'s account describes elaborate funeral rites including weapons, sacrificed horses, and valuable possessions, showing Vikings believed the dead needed these items in the afterlife. This mirrors Baldr\'s mythological funeral.',
      relatedLearningPoints: ['edda-ch4-lp-16', 'edda-ch4-lp-17'],
    },
    {
      id: 'q14',
      question: 'What symbolic significance does the mistletoe have in the myth?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It represents divine power',
        'As a parasitic plant, it symbolizes how death undermined the gods\' celebration from within',
        'It represents eternal life',
        'It has no symbolic meaning',
      ],
      correctAnswer: 'As a parasitic plant, it symbolizes how death undermined the gods\' celebration from within',
      explanation: 'Mistletoe is a parasitic plant that grows on other trees, making it symbolically appropriate as the instrument of death that undermines the gods\' joy and sense of security from within their own celebration.',
      relatedLearningPoints: ['edda-ch4-lp-13'],
    },
    {
      id: 'q15',
      question: 'What mysterious action did Odin perform at Baldr\'s funeral?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He whispered something in Baldr\'s ear',
        'He placed a ring on Baldr\'s finger',
        'He gave Baldr his spear Gungnir',
        'He wept openly before all the gods',
      ],
      correctAnswer: 'He whispered something in Baldr\'s ear',
      explanation: 'Odin whispered something in Baldr\'s ear before the funeral pyre was lit, but the content of those words was never revealed. This mystery has been debated for centuries and adds to the myth\'s enduring fascination.',
      relatedLearningPoints: ['edda-ch4-lp-19'],
    },
    {
      id: 'q16',
      question: 'Analyze how the myth of Baldr\'s death illustrates the Norse concept of inevitable fate (wyrd). Why couldn\'t the gods prevent his death despite their efforts?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'The myth of Baldr\'s death perfectly embodies the Norse concept of wyrd—the idea that fate is an inescapable web of consequences woven by past actions. Despite Frigg extracting oaths from nearly everything in existence and the gods\' desperate attempts to bring Baldr back from Hel, his death could not be prevented. Even Baldr\'s prophetic dreams warned of his doom, yet knowledge of fate didn\'t grant power to change it. The single oversight (mistletoe) became the fatal flaw, showing how wyrd finds its way through any defense. After his death, the gods\' mission to have all things weep for Baldr failed because of one refusal (Þökk/Loki), demonstrating that fate requires only the smallest crack to manifest. This illustrates a fundamental Norse belief: even gods cannot escape destiny. Their power is limited by the accumulated weight of past actions and the inevitable unfolding of consequences, making Baldr\'s death both tragic and cosmically necessary.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Explains the Norse concept of wyrd/fate as inevitable and inescapable',
          points: 4,
        },
        {
          id: 'crit2',
          text: 'Discusses specific actions the gods took to prevent Baldr\'s death',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Analyzes why these efforts ultimately failed',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Connects this to broader themes about the limitations of divine power in Norse mythology',
          points: 3,
        },
      ],
      explanation: 'This question asks you to analyze how Baldr\'s death demonstrates the Norse concept of fate. Consider both the preventive measures taken and why they failed.',
      relatedLearningPoints: ['edda-ch4-lp-10', 'edda-ch4-lp-15', 'edda-ch4-lp-23', 'edda-ch4-lp-27'],
    },
    {
      id: 'q17',
      question: 'Trace Loki\'s transformation from trickster to villain throughout The Edda. What does his role in Baldr\'s death reveal about his character development?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'Loki\'s character arc throughout The Edda shows a gradual descent from clever trickster to malevolent villain. In earlier myths, while his tricks caused problems, they often resulted in benefits for the gods—his cunning helped retrieve Thor\'s hammer and acquire treasures for Asgard. However, Baldr\'s death marks a pivotal transformation: this is not a prank gone wrong but a deliberate, calculated murder. Loki actively sought out Baldr\'s weakness by disguising himself to trick Frigg, then manipulated the innocent Höðr into becoming the murder weapon. Even more cruelly, he likely disguised himself as Þökk to ensure Baldr couldn\'t return, showing complete commitment to causing irreversible harm. This reveals a character consumed by jealousy and malice—possibly envious of Baldr\'s perfection and universal love. His actions here cross the line from mischief to evil, setting up his role as the leader of chaos\'s forces at Ragnarök. The myth suggests that unchecked trickery and resentment inevitably corrupt into genuine malevolence.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Discusses Loki\'s earlier role as a trickster whose pranks were sometimes helpful',
          points: 4,
        },
        {
          id: 'crit2',
          text: 'Identifies specific actions showing his transformation to malicious villain',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Analyzes what Baldr\'s death reveals about Loki\'s motivations and character',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Connects this transformation to his future role in Ragnarök',
          points: 3,
        },
      ],
      explanation: 'This question asks you to trace Loki\'s character development and analyze his transformation from trickster to villain. Think about what motivates this change and what it reveals about his nature.',
      relatedLearningPoints: ['edda-ch4-lp-7', 'edda-ch4-lp-12', 'edda-ch4-lp-22', 'edda-ch4-lp-26'],
    },
  ],
};
