import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'edda-ch1-quiz',
  title: 'Chapter 1: The Beginning of All Things Quiz',
  description: 'Test your knowledge of the Norse creation myth, the Nine Worlds, and the foundations of Norse cosmology.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'edda-ch1-q1',
      question: 'What was Ginnungagap?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The first giant who created the world',
        'The primordial void that existed before creation',
        'The world tree that connects all realms',
        'The rainbow bridge to Asgard',
      ],
      correctAnswer: 'The primordial void that existed before creation',
      explanation: 'Ginnungagap was the "yawning void" or great emptiness that existed before creation, with Niflheim to the north and Muspelheim to the south.',
      relatedLearningPoints: ['edda-ch1-lp-3-creation'],
    },
    {
      id: 'edda-ch1-q2',
      question: 'Which two opposing forces came together to create life?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Light and darkness',
        'Good and evil',
        'Ice and fire',
        'Gods and giants',
      ],
      correctAnswer: 'Ice and fire',
      explanation: 'Creation emerged from the meeting of ice (from Niflheim) and fire (from Muspelheim) in Ginnungagap. This duality of opposing forces is central to Norse cosmology.',
      relatedLearningPoints: ['edda-ch1-lp-3-creation', 'edda-ch1-lp-4-duality'],
    },
    {
      id: 'edda-ch1-q3',
      question: 'Who was Ymir?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The first god who created the world',
        'The primordial giant whose body became the world',
        'The dragon that guards the world tree',
        'The first human created by the gods',
      ],
      correctAnswer: 'The primordial giant whose body became the world',
      explanation: 'Ymir was the first living being, a primordial giant. When Odin, Vili, and Vé slew him, they used his body to create the world—his flesh became earth, his blood the seas, his bones the mountains, and his skull the sky.',
      relatedLearningPoints: ['edda-ch1-lp-9-ymir', 'edda-ch1-lp-14-sacrifice'],
    },
    {
      id: 'edda-ch1-q4',
      question: 'What did Audhumla the cow do that was significant for creation?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She only provided milk to nourish Ymir',
        'She only licked the ice to reveal Búri',
        'She created the first humans from her milk',
        'She nourished Ymir with milk and licked ice to free Búri',
      ],
      correctAnswer: 'She nourished Ymir with milk and licked ice to free Búri',
      explanation: 'Audhumla had two crucial roles: she fed Ymir with four rivers of milk, and by licking the salty ice blocks, she revealed Búri over three days. Búri was the ancestor of the gods. Both actions were essential to the creation story.',
      relatedLearningPoints: ['edda-ch1-lp-10-audhumla', 'edda-ch1-lp-11-divine-lineage'],
    },
    {
      id: 'edda-ch1-q5',
      question: 'Which three brothers slew Ymir and created the world?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Thor, Loki, and Freyr',
        'Odin, Vili, and Vé',
        'Búri, Borr, and Bestla',
        'Nordri, Sudri, and Austri',
      ],
      correctAnswer: 'Odin, Vili, and Vé',
      explanation: 'Odin, Vili, and Vé—the three divine brothers and sons of Borr—slew Ymir and used his body to create the physical world, imposing order upon primordial chaos.',
      relatedLearningPoints: ['edda-ch1-lp-15-order-chaos'],
    },
    {
      id: 'edda-ch1-q6',
      question: 'How were the first humans, Ask and Embla, created?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They were born from Ymir\'s sweat',
        'They emerged from the earth',
        'They were created from two trees',
        'They were shaped from clay',
      ],
      correctAnswer: 'They were created from two trees',
      explanation: 'Odin, Vili, and Vé found two trees (an ash and an elm) on the seashore and gave them life, consciousness, and senses, transforming them into Ask and Embla, the first humans.',
      relatedLearningPoints: ['edda-ch1-lp-19-humanity', 'edda-ch1-lp-20-trees'],
    },
    {
      id: 'edda-ch1-q7',
      question: 'What is Yggdrasil?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The first giant slain by the gods',
        'The world tree that connects the Nine Worlds',
        'The ship that will carry the dead at Ragnarök',
        'Odin\'s eight-legged horse',
      ],
      correctAnswer: 'The world tree that connects the Nine Worlds',
      explanation: 'Yggdrasil is the immense cosmic ash tree that connects all Nine Worlds. Its roots reach into different realms, and its branches spread over the entire cosmos. It serves as the axis of Norse cosmology.',
      relatedLearningPoints: ['edda-ch1-lp-29-yggdrasil'],
    },
    {
      id: 'edda-ch1-q8',
      question: 'Asgard is the realm of which beings?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Humans',
        'Giants',
        'The Aesir gods',
        'Elves',
      ],
      correctAnswer: 'The Aesir gods',
      explanation: 'Asgard is the realm of the Aesir, the principal gods including Odin, Thor, and Frigg. It is connected to Midgard (the human realm) by the rainbow bridge Bifrost.',
      relatedLearningPoints: ['edda-ch1-lp-12-nine-worlds'],
    },
    {
      id: 'edda-ch1-q9',
      question: 'What is Midgard?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The realm of the dead',
        'The realm of giants',
        'The realm of humans, created from Ymir\'s body',
        'The realm of fire',
      ],
      correctAnswer: 'The realm of humans, created from Ymir\'s body',
      explanation: 'Midgard (Middle-Earth) is the realm of humans, created from Ymir\'s flesh and encircled by the ocean. It is the central world, protected by the gods but vulnerable to threats from giants and monsters.',
      relatedLearningPoints: ['edda-ch1-lp-12-nine-worlds'],
    },
    {
      id: 'edda-ch1-q10',
      question: 'What constantly attacks Yggdrasil, the world tree?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The gods try to cut it down',
        'The dragon Níðhöggr gnaws its roots, and stags eat its leaves',
        'Fire giants try to burn it',
        'Nothing attacks it; it is eternal and indestructible',
      ],
      correctAnswer: 'The dragon Níðhöggr gnaws its roots, and stags eat its leaves',
      explanation: 'Yggdrasil is under constant attack: the dragon Níðhöggr gnaws at its roots from below, four stags eat its leaves, and it suffers decay. This symbolizes that even cosmic structures are mortal and subject to entropy.',
      relatedLearningPoints: ['edda-ch1-lp-30-decay'],
    },
    {
      id: 'edda-ch1-q11',
      question: 'Who is Odin in Norse mythology?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The god of thunder who wields a hammer',
        'The Allfather, god of wisdom, war, poetry, and death',
        'The trickster god who causes mischief',
        'The god of the sea and seafarers',
      ],
      correctAnswer: 'The Allfather, god of wisdom, war, poetry, and death',
      explanation: 'Odin is the chief of the Aesir, known as the Allfather. He is a complex deity associated with wisdom (which he seeks relentlessly), war, poetry, and death. He sacrificed his eye for knowledge and will lead the gods at Ragnarök.',
      relatedLearningPoints: ['edda-ch1-lp-24-odin'],
    },
    {
      id: 'edda-ch1-q12',
      question: 'The Norse creation myth involves creation from nothing (ex nihilo).',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'False. Norse creation does not involve creation from nothing. Instead, the world was created through transformation—Ymir\'s body was transformed into earth, seas, and sky. This represents imposing order upon existing chaos.',
      relatedLearningPoints: ['edda-ch1-lp-15-order-chaos'],
    },
    {
      id: 'edda-ch1-q13',
      question: 'What role does Bifrost play in Norse cosmology?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It is the weapon of Thor',
        'It is the rainbow bridge connecting Asgard and Midgard',
        'It is the well of wisdom beneath Yggdrasil',
        'It is the hall where warriors feast',
      ],
      correctAnswer: 'It is the rainbow bridge connecting Asgard and Midgard',
      explanation: 'Bifrost is the rainbow bridge that connects Asgard (realm of the gods) to Midgard (realm of humans). It is guarded by the god Heimdall, who watches for threats to the divine realm.',
      relatedLearningPoints: ['edda-ch1-lp-12-nine-worlds'],
    },
    {
      id: 'edda-ch1-q14',
      question: 'What is the significance of Snorri Sturluson writing the Prose Edda?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was the first person to invent Norse mythology',
        'He preserved dying oral traditions for future generations',
        'He tried to convert people back to the old Norse religion',
        'He wrote it as pure fiction for entertainment',
      ],
      correctAnswer: 'He preserved dying oral traditions for future generations',
      explanation: 'Snorri Sturluson wrote the Prose Edda around 1220 CE to preserve Norse myths that were being forgotten after Iceland\'s conversion to Christianity. Without his work, much of what we know about Norse mythology would be lost.',
      relatedLearningPoints: ['edda-ch1-lp-1-snorri', 'edda-ch1-lp-2-preservation'],
    },
    {
      id: 'edda-ch1-q15',
      question: 'What is the relationship between gods and giants in Norse mythology?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They are completely separate races with no connection',
        'Giants and gods are related; many gods have giant ancestry',
        'Giants are always evil and gods are always good',
        'Giants created the gods',
      ],
      correctAnswer: 'Giants and gods are related; many gods have giant ancestry',
      explanation: 'The relationship is complex—Odin\'s mother Bestla was a giantess, and many gods married giants. Giants represent chaos and nature while gods represent order, but they are not simply "good vs. evil." They are interconnected parts of the cosmos.',
      relatedLearningPoints: ['edda-ch1-lp-11-divine-lineage', 'edda-ch1-lp-13-cosmology'],
    },

    // Self-Assessment Questions
    {
      id: 'edda-ch1-q16',
      question: 'Analyze the significance of creation through transformation in Norse mythology. How does creating the world from Ymir\'s body differ from creation myths where the world is made from nothing? What does this tell us about Norse views on death, sacrifice, and the relationship between destruction and creation?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'Norse creation through transformation is fundamentally different from ex nihilo (creation from nothing) myths. The world was not spoken into existence or born from divine will alone—it emerged from the violent death and transformation of Ymir, the primordial giant. His flesh became earth, his blood the seas, his bones the mountains, his skull the sky. This represents several key Norse concepts:\n\nFirst, it shows that creation requires sacrifice and destruction—something must die for something new to emerge. Death is not simply an ending but a transformation into new forms. Second, it reflects a view that the universe operates through transformation rather than absolute creation or destruction. Matter and energy change forms but aren\'t created from nothing. Third, it establishes that order (cosmos) emerges from imposing structure upon chaos (the primordial giant), not from eliminating chaos entirely. The gods didn\'t destroy chaos—they shaped it into ordered forms. Finally, it creates a universe that is fundamentally mortal and impermanent. Since the world is made from a slain being, it too can die (as in Ragnarök). This contrasts sharply with eternal creation myths and reflects Norse acceptance of cyclical time and inevitable endings.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Explained how transformation differs from ex nihilo creation (reshaping vs. creating from nothing)',
          points: 4,
        },
        {
          id: 'crit2',
          text: 'Discussed the role of sacrifice and violent transformation in Norse cosmology',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Analyzed what this reveals about Norse views on death, impermanence, and the relationship between order and chaos',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Connected this creation pattern to broader Norse themes (mortality of cosmos, Ragnarök, cyclical time)',
          points: 3,
        },
      ],
      explanation: 'This question asks you to think deeply about the philosophical implications of creation through transformation. Understanding why the Norse chose this type of creation myth helps us grasp their worldview—one that accepted violence, sacrifice, impermanence, and cyclical change as fundamental aspects of existence.',
      relatedLearningPoints: ['edda-ch1-lp-9-ymir', 'edda-ch1-lp-14-sacrifice', 'edda-ch1-lp-15-order-chaos'],
    },
    {
      id: 'edda-ch1-q17',
      question: 'Explain how Yggdrasil functions as more than just a physical tree in Norse cosmology. What does it represent about Norse understanding of the universe, and why is it significant that this cosmic structure is under constant attack and decay?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'Yggdrasil is not merely a physical tree but the axis mundi—the cosmic axis that structures and connects all of reality. It is the organizing principle of the Norse universe, with its roots reaching into different realms and its branches spreading across the cosmos. The Nine Worlds exist in relation to Yggdrasil; without it, there would be no structure to reality.\n\nThe tree represents several crucial concepts. First, it embodies interconnection—all realms are linked through it, meaning actions in one world can affect others. Gods, giants, humans, and other beings all depend on the same cosmic structure. Second, it symbolizes that the universe is fundamentally organic and living, not mechanical. Like all living things, it grows, suffers, and can die. Third, the tree\'s central position reflects the Norse view that reality has structure and order, even if that order is constantly contested.\n\nThe fact that Yggdrasil is under constant attack—Níðhöggr gnawing at its roots, stags eating its leaves, decay affecting its trunk—is philosophically crucial. It shows that even the most fundamental cosmic structures are mortal and vulnerable. Order is not eternal or guaranteed; it must be constantly maintained against entropy and chaos. The Norns water the tree daily, but this can only slow, not prevent, its eventual death at Ragnarök. This reflects the Norse acceptance that all things, even the universe itself, are temporary. There is no eternal, unchanging realm—even cosmic order is subject to time and decay.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Explained Yggdrasil\'s role as axis mundi and cosmic structure (organizing principle, connecting realms)',
          points: 5,
        },
        {
          id: 'crit2',
          text: 'Discussed what the tree symbolizes (interconnection, organic universe, structured reality)',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Analyzed the significance of constant attacks and decay (mortality of cosmic structures, entropy vs. order)',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Connected this to broader Norse worldview (impermanence, absence of eternal realm, acceptance of endings)',
          points: 2,
        },
      ],
      explanation: 'This question explores how Yggdrasil functions as a symbol and philosophical concept. Understanding the tree\'s vulnerability helps us grasp the Norse view that nothing is permanent—not humans, not gods, not even the structure of reality itself. This acceptance of universal mortality distinguishes Norse mythology from many other traditions.',
      relatedLearningPoints: ['edda-ch1-lp-29-yggdrasil', 'edda-ch1-lp-30-decay', 'edda-ch1-lp-13-cosmology'],
    },
  ],
};
