import type { Quiz } from '../../../types';

export const chapter3Quiz: Quiz = {
  id: 'quiz-chapter-3',
  title: 'Chapter 3: Odin\'s Quest for Wisdom Quiz',
  description: 'Test your knowledge of Odin\'s sacrifices and the pursuit of wisdom in Norse mythology.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What did Odin sacrifice to drink from Mimir\'s well?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His right hand',
        'One of his eyes',
        'His immortality',
        'His throne in Asgard',
      ],
      correctAnswer: 'One of his eyes',
      explanation: 'Odin sacrificed one of his eyes to Mimir\'s well, trading outer sight for inner wisdom. This permanent sacrifice symbolizes the cost of true knowledge.',
      relatedLearningPoints: ['edda-ch3-lp-3-sacrifice-choice', 'edda-ch3-lp-5-eye-symbolism'],
    },
    {
      id: 'q2',
      question: 'What knowledge did Odin gain by drinking from Mimir\'s well?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The location of hidden treasure',
        'How to defeat the giants',
        'Wisdom of past, present, and future',
        'The secret of immortality',
      ],
      correctAnswer: 'Wisdom of past, present, and future',
      explanation: 'Mimir\'s well granted Odin knowledge of all times—past, present, and future. This included awareness of Ragnarök and his own fate.',
      relatedLearningPoints: ['edda-ch3-lp-4-mimir-well', 'edda-ch3-lp-7-knowledge-burden'],
    },
    {
      id: 'q3',
      question: 'How long did Odin hang on Yggdrasil to learn the runes?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Three days and three nights',
        'Seven days and seven nights',
        'Nine days and nine nights',
        'Thirteen days and thirteen nights',
      ],
      correctAnswer: 'Nine days and nine nights',
      explanation: 'Odin hung on Yggdrasil for nine days and nine nights. The number nine was sacred in Norse mythology and represents completeness.',
      relatedLearningPoints: ['edda-ch3-lp-13-yggdrasil-ordeal'],
    },
    {
      id: 'q4',
      question: 'What weapon did Odin use to wound himself before hanging on Yggdrasil?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His sword',
        'His spear Gungnir',
        'An arrow',
        'A dagger',
      ],
      correctAnswer: 'His spear Gungnir',
      explanation: 'Odin pierced his own side with his spear Gungnir before hanging on Yggdrasil. This self-sacrifice was necessary to gain the knowledge of the runes.',
      relatedLearningPoints: ['edda-ch3-lp-13-yggdrasil-ordeal', 'edda-ch3-lp-15-self-sacrifice'],
    },
    {
      id: 'q5',
      question: 'What are the runes in Norse culture?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Simple letters for writing messages',
        'Magical symbols with cosmic power and meaning',
        'Decorative carvings with no special significance',
        'A type of weapon used by warriors',
      ],
      correctAnswer: 'Magical symbols with cosmic power and meaning',
      explanation: 'Runes were believed to be more than just an alphabet—they were symbols of magical power that could bring victory, protection, and wisdom when properly used.',
      relatedLearningPoints: ['edda-ch3-lp-11-rune-magic', 'edda-ch3-lp-16-elder-futhark', 'edda-ch3-lp-17-rune-meanings'],
    },
    {
      id: 'q6',
      question: 'According to the Hávamál, what is the one thing that never dies?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The gods themselves',
        'Gold and treasure',
        'The reputation of one who has died',
        'The World Tree Yggdrasil',
      ],
      correctAnswer: 'The reputation of one who has died',
      explanation: 'The famous verse states: "Cattle die, kinsmen die, you yourself will die; I know one thing that never dies—the reputation of the one who has died." This emphasizes that honor and reputation are immortal.',
      relatedLearningPoints: ['edda-ch3-lp-10-reputation', 'edda-ch3-lp-18-practical-wisdom'],
    },
    {
      id: 'q7',
      question: 'What was the Mead of Poetry made from?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Honey from magical bees',
        'The blood of Kvasir mixed with honey',
        'Fermented berries from Asgard',
        'Water from Mimir\'s well',
      ],
      correctAnswer: 'The blood of Kvasir mixed with honey',
      explanation: 'The Mead of Poetry was brewed from the blood of Kvasir, the wisest being ever created, mixed with honey. Drinking it granted poetic inspiration and eloquence.',
      relatedLearningPoints: ['edda-ch3-lp-19-mead-origin'],
    },
    {
      id: 'q8',
      question: 'Who guarded the Mead of Poetry in the mountain?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The giant Suttung and his daughter Gunnlod',
        'The dwarves who brewed it',
        'Thor and his warriors',
        'The Norns at the well of fate',
      ],
      correctAnswer: 'The giant Suttung and his daughter Gunnlod',
      explanation: 'The giant Suttung kept the mead locked in a mountain cave, with his daughter Gunnlod watching over it. Odin had to seduce Gunnlod to gain access.',
      relatedLearningPoints: ['edda-ch3-lp-19-mead-origin', 'edda-ch3-lp-21-seduction'],
    },
    {
      id: 'q9',
      question: 'How did Odin escape with the Mead of Poetry?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He fought his way out with his spear',
        'He transformed into an eagle and flew away',
        'He used magic to teleport to Asgard',
        'He negotiated a trade with Suttung',
      ],
      correctAnswer: 'He transformed into an eagle and flew away',
      explanation: 'Odin shapeshifted into an eagle to escape, with Suttung (also in eagle form) chasing him. In his haste, Odin spilled some mead, which fell to Midgard and gave lesser poets their inspiration.',
      relatedLearningPoints: ['edda-ch3-lp-23-shapeshifting', 'edda-ch3-lp-24-poetry-distribution'],
    },
    {
      id: 'q10',
      question: 'What does Odin\'s quest for wisdom reveal about Norse values?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Physical strength was valued above all else',
        'Wisdom and knowledge were worth any sacrifice',
        'Material wealth was the highest goal',
        'The gods had no need for learning',
      ],
      correctAnswer: 'Wisdom and knowledge were worth any sacrifice',
      explanation: 'Odin\'s willingness to sacrifice his eye, endure nine days of agony, and risk everything for knowledge shows that Norse culture valued wisdom above physical wholeness, comfort, or safety.',
      relatedLearningPoints: ['edda-ch3-lp-2-wisdom-value', 'edda-ch3-lp-28-wisdom-cost'],
    },
    {
      id: 'q11',
      question: 'The Hávamál teaches that you should "praise no day until evening." What does this mean?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Always be pessimistic about the future',
        'Never celebrate any achievements',
        'Wait to judge something until it is complete',
        'Only speak at night, never during the day',
      ],
      correctAnswer: 'Wait to judge something until it is complete',
      explanation: 'This verse teaches caution and wisdom—don\'t judge success until the outcome is certain. Many things can change before the end, so reserve judgment until completion.',
      relatedLearningPoints: ['edda-ch3-lp-9-havamal', 'edda-ch3-lp-18-practical-wisdom'],
    },
    {
      id: 'q12',
      question: 'What does "wyrd" mean in Norse culture?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A type of magical spell',
        'The web of fate connecting all actions and consequences',
        'A word for strange or unusual events',
        'The name of one of the Norns',
      ],
      correctAnswer: 'The web of fate connecting all actions and consequences',
      explanation: 'Wyrd represents the Norse concept of fate as the accumulated weight of past actions shaping future outcomes—a web of cause and effect connecting all beings.',
      relatedLearningPoints: ['edda-ch3-lp-7-knowledge-burden', 'edda-ch3-lp-8-fate-awareness'],
    },
    {
      id: 'q13',
      question: 'What happened to the mead that Odin spilled during his escape?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It was lost forever',
        'The giants reclaimed it',
        'It fell to Midgard and gave humans lesser poetic ability',
        'It poisoned the land where it fell',
      ],
      correctAnswer: 'It fell to Midgard and gave humans lesser poetic ability',
      explanation: 'The drops of mead that Odin spilled during his hasty escape fell to Midgard. This explains why some humans have minor poetic talent (from the spilled mead) while great poets received the mead Odin saved.',
      relatedLearningPoints: ['edda-ch3-lp-24-poetry-distribution'],
    },
    {
      id: 'q14',
      question: 'Why was poetry so important in Norse culture?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It was purely for entertainment',
        'It was the primary means of preserving history and cultural memory',
        'It was considered a waste of time',
        'Only the gods were allowed to create poetry',
      ],
      correctAnswer: 'It was the primary means of preserving history and cultural memory',
      explanation: 'In pre-literate Norse society, poetry was how cultural memory, history, and wisdom were preserved and passed down through generations. Poets (skalds) were highly honored.',
      relatedLearningPoints: ['edda-ch3-lp-20-poetry-value', 'edda-ch3-lp-27-poetry-preservation'],
    },
    {
      id: 'q15',
      question: 'Odin\'s knowledge of Ragnarök shows that even gods cannot escape fate.',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'True! Even though Odin gained knowledge of Ragnarök and his own death, he could not prevent it. Norse mythology emphasizes that fate is inevitable—what matters is facing it with courage.',
      relatedLearningPoints: ['edda-ch3-lp-8-fate-awareness', 'edda-ch3-lp-7-knowledge-burden'],
    },
    {
      id: 'q16',
      question: 'Odin sacrifices his eye, hangs from Yggdrasil for nine days, and uses deception to steal the mead of poetry. What philosophy of knowledge and wisdom do these actions reveal about Norse culture?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'Odin\'s actions reveal a Norse philosophy where wisdom is worth any cost, even permanent physical sacrifice or moral compromise. His willingness to lose an eye and endure extreme suffering shows that knowledge was valued more than bodily integrity or comfort. Additionally, his use of deception to obtain the mead demonstrates that cunning and cleverness were respected methods for gaining wisdom—there was no single "honorable" path. This reflects a pragmatic culture that prioritized the end result (gaining wisdom) and understood that true knowledge often requires sacrifice, suffering, and creative thinking. The Norse saw wisdom-seeking as an active, often painful pursuit, not something passively received.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Discusses the high value placed on knowledge and wisdom in Norse culture',
          points: 4,
        },
        {
          id: 'crit2',
          text: 'Analyzes the willingness to sacrifice physical wholeness for intellectual/spiritual gain',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Explains how both suffering and cunning were considered acceptable paths to wisdom',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Connects Odin\'s actions to broader Norse values about the cost and pursuit of knowledge',
          points: 3,
        },
      ],
      explanation: 'This question asks you to analyze what Odin\'s various quests for knowledge reveal about Norse cultural values. Consider both the methods he uses and the prices he pays to gain wisdom.',
      relatedLearningPoints: ['edda-ch3-lp-2-wisdom-value', 'edda-ch3-lp-3-sacrifice-choice', 'edda-ch3-lp-15-self-sacrifice', 'edda-ch3-lp-28-wisdom-cost'],
    },
    {
      id: 'q17',
      question: 'Compare and contrast Odin\'s sacrifices for wisdom with quests for knowledge in other mythological traditions. What makes the Norse approach unique?',
      type: 'self-assessment',
      points: 15,
      modelAnswer: 'Unlike Greek mythology, where wisdom is often granted by gods (Athena) or gained through divine favor, Norse mythology requires active, painful sacrifice. Odin must wound himself and endure suffering—wisdom isn\'t given freely but must be earned through ordeal. In contrast to Judeo-Christian traditions where forbidden knowledge (like the Tree of Knowledge) brings punishment, Odin\'s pursuit of knowledge is heroic and admirable, even when it involves deception or suffering. What makes the Norse approach unique is the acceptance that even divine knowledge cannot prevent fate—Odin learns of Ragnarök but cannot stop it. This reflects a worldview where knowledge brings burden and responsibility rather than control. The emphasis on self-sacrifice (rather than divine gift or quest) also distinguishes Norse tradition, suggesting a culture that valued personal agency and understood wisdom as something taken, not given.',
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'References at least one other mythological tradition\'s approach to wisdom',
          points: 4,
        },
        {
          id: 'crit2',
          text: 'Identifies specific differences in how knowledge is pursued or granted',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Discusses the unique aspects of Norse mythology (self-sacrifice, physical cost, inevitability of fate)',
          points: 4,
        },
        {
          id: 'crit4',
          text: 'Demonstrates understanding of cultural values reflected in these different approaches',
          points: 3,
        },
      ],
      explanation: 'This comparative question asks you to place Norse wisdom-seeking in a broader cultural context. Think about how different mythological traditions reflect different cultural values about knowledge, power, and fate.',
      relatedLearningPoints: ['edda-ch3-lp-2-wisdom-value', 'edda-ch3-lp-7-knowledge-burden', 'edda-ch3-lp-8-fate-awareness', 'edda-ch3-lp-28-wisdom-cost'],
    },
  ],
};
