import type { Quiz } from '../../../types';

export const chapter3Quiz: Quiz = {
  id: 'quiz-chapter-3-tempest',
  title: 'Chapter 3: The Tempest Quiz',
  description: 'Test your understanding of magic, colonialism, and the journey from vengeance to forgiveness.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'Why does Prospero create the tempest that opens the play?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To destroy his enemies completely',
        'To bring his enemies to the island where he can confront them and potentially take revenge',
        'To show off his magical powers',
        'To escape from the island',
      ],
      correctAnswer: 'To bring his enemies to the island where he can confront them and potentially take revenge',
      explanation: 'Prospero uses magic to shipwreck those who betrayed him, creating the opportunity for confrontation—and ultimately, a choice between revenge and forgiveness.',
      relatedLearningPoints: ['lp-tempest-1-setup', 'lp-tempest-2-backstory'],
    },
    {
      id: 'q2',
      question: 'What was Prospero\'s original crime that led to his overthrow?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He tried to seize his brother\'s throne',
        'He neglected his duties as Duke, lost in his books and magic',
        'He made a deal with evil spirits',
        'He refused to marry',
      ],
      correctAnswer: 'He neglected his duties as Duke, lost in his books and magic',
      explanation: 'Prospero admits he prioritized study over governance, allowing Antonio to gain power and eventually usurp him—a failure of responsibility.',
      relatedLearningPoints: ['lp-tempest-2-backstory', 'lp-tempest-2-neglect'],
    },
    {
      id: 'q3',
      question: 'What does Ariel represent in the play\'s symbolic structure?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Pure evil and chaos',
        'Air, spirit, imagination, and the desire for freedom',
        'Earth and material wealth',
        'Human love and passion',
      ],
      correctAnswer: 'Air, spirit, imagination, and the desire for freedom',
      explanation: 'Ariel embodies the ethereal—serving Prospero in exchange for promised freedom, representing both magical power and the longing for liberation.',
      relatedLearningPoints: ['lp-tempest-4-ariel', 'lp-tempest-4-spirit'],
    },
    {
      id: 'q4',
      question: 'What does Caliban\'s famous line "You taught me language, and my profit on\'t is I know how to curse" suggest about colonialism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Caliban is simply ungrateful',
        'Colonial education can be a form of domination, and the colonized may use the colonizer\'s tools against them',
        'Language is useless',
        'Caliban prefers to remain silent',
      ],
      correctAnswer: 'Colonial education can be a form of domination, and the colonized may use the colonizer\'s tools against them',
      explanation: 'Caliban\'s curse shows how the colonized can turn the colonizer\'s "gifts" into weapons of resistance—a profound insight into colonial dynamics.',
      relatedLearningPoints: ['lp-tempest-5-caliban', 'lp-tempest-5-colonialism'],
    },
    {
      id: 'q5',
      question: 'How does the Ferdinand-Miranda romance differ from tragic love stories in Part I?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It has more conflict and drama',
        'It ends in death like Romeo and Juliet',
        'It is innocent, approved by the father, and leads to reconciliation rather than tragedy',
        'The lovers never actually meet',
      ],
      correctAnswer: 'It is innocent, approved by the father, and leads to reconciliation rather than tragedy',
      explanation: 'Unlike Romeo and Juliet\'s forbidden love, Miranda and Ferdinand\'s relationship is orchestrated by Prospero to heal political wounds through marriage.',
      relatedLearningPoints: ['lp-tempest-6-love', 'lp-tempest-6-contrast'],
    },
    {
      id: 'q6',
      question: 'What is the significance of Prospero\'s masque (the wedding entertainment)?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It is simply entertainment with no deeper meaning',
        'It shows Prospero\'s power to create beautiful illusions, but he must break it when reality intrudes',
        'It proves magic is evil',
        'It is Caliban\'s revenge',
      ],
      correctAnswer: 'It shows Prospero\'s power to create beautiful illusions, but he must break it when reality intrudes',
      explanation: 'The masque represents art\'s power to create beauty, but Prospero must dissolve it when he remembers Caliban\'s plot—art cannot ignore reality.',
      relatedLearningPoints: ['lp-tempest-8-masque', 'lp-tempest-8-illusion'],
    },
    {
      id: 'q7',
      question: 'What does "We are such stuff as dreams are made on" mean in context?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Dreams are meaningless',
        'Humans and all our creations are as transient and insubstantial as dreams',
        'We should sleep more',
        'Only magic is real',
      ],
      correctAnswer: 'Humans and all our creations are as transient and insubstantial as dreams',
      explanation: 'This famous speech suggests that human life, like theatrical illusion, is temporary—a profound meditation on mortality and meaning.',
      relatedLearningPoints: ['lp-tempest-9-dreams', 'lp-tempest-9-philosophy'],
    },
    {
      id: 'q8',
      question: 'What triggers Prospero\'s decision to choose forgiveness over revenge?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Miranda begs him to forgive',
        'Ariel describes the enemies\' suffering and suggests that Prospero\'s humanity should move him to pity',
        'Caliban threatens him',
        'A storm destroys his books',
      ],
      correctAnswer: 'Ariel describes the enemies\' suffering and suggests that Prospero\'s humanity should move him to pity',
      explanation: 'Ironically, the non-human Ariel reminds Prospero of his humanity. Prospero realizes that "the rarer action is in virtue than in vengeance."',
      relatedLearningPoints: ['lp-tempest-10-choice', 'lp-tempest-10-humanity'],
    },
    {
      id: 'q9',
      question: 'Why does Prospero renounce his magic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He has no more use for it after his enemies are dead',
        'Choosing to live as a human rather than a god-like magician represents embracing mortality and human connection',
        'The magic runs out',
        'Ariel forces him to',
      ],
      correctAnswer: 'Choosing to live as a human rather than a god-like magician represents embracing mortality and human connection',
      explanation: 'Prospero\'s choice to "drown his book" represents accepting human limitations rather than wielding superhuman power—choosing connection over control.',
      relatedLearningPoints: ['lp-tempest-11-renunciation', 'lp-tempest-11-humanity'],
    },
    {
      id: 'q10',
      question: 'Why is Prospero often seen as a figure for Shakespeare himself?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They have the same name',
        'Both are magicians who create illusions (plays), control characters, and ultimately bid farewell to their art',
        'Both lived on islands',
        'They look alike',
      ],
      correctAnswer: 'Both are magicians who create illusions (plays), control characters, and ultimately bid farewell to their art',
      explanation: 'Prospero\'s farewell to magic mirrors Shakespeare\'s farewell to theater—The Tempest is often read as Shakespeare\'s artistic testament.',
      relatedLearningPoints: ['lp-tempest-12-metatheater', 'lp-tempest-12-farewell'],
    },
    {
      id: 'q11',
      question: 'What does the Epilogue\'s request for applause represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Shakespeare begging for money',
        'The artist stripped of power, dependent on the audience\'s grace—mirroring Prospero\'s forgiveness',
        'A joke with no meaning',
        'Prospero asking for revenge',
      ],
      correctAnswer: 'The artist stripped of power, dependent on the audience\'s grace—mirroring Prospero\'s forgiveness',
      explanation: 'Having forgiven others, Prospero/Shakespeare asks to be "set free" by applause—the audience completes the circle of forgiveness.',
      relatedLearningPoints: ['lp-tempest-13-epilogue', 'lp-tempest-13-freedom'],
    },
    {
      id: 'q12',
      question: 'How does The Tempest resolve the tragic themes of Parts I and II?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It ignores tragedy completely',
        'It shows that forgiveness, not revenge, can break cycles of violence and restore what was lost',
        'It proves tragedy is always inevitable',
        'It has a completely different theme',
      ],
      correctAnswer: 'It shows that forgiveness, not revenge, can break cycles of violence and restore what was lost',
      explanation: 'Where Hamlet delays revenge until everyone dies and Julius Caesar shows assassination destroying the assassins, The Tempest offers reconciliation as an alternative.',
      relatedLearningPoints: ['lp-tempest-14-synthesis', 'lp-tempest-14-resolution'],
    },
  ],
};
