import type { Quiz } from '../../../types';

export const chapter2Quiz: Quiz = {
  id: 'quiz-chapter-2-julius-caesar',
  title: 'Chapter 2: Julius Caesar Quiz',
  description: 'Test your understanding of political betrayal, rhetoric, and the consequences of assassination.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What is the fundamental moral dilemma at the heart of Julius Caesar?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Whether Caesar should marry Cleopatra',
        'Whether killing a potential tyrant to preserve freedom is justified',
        'Whether Rome should become a democracy',
        'Whether Brutus should become king',
      ],
      correctAnswer: 'Whether killing a potential tyrant to preserve freedom is justified',
      explanation: 'The play explores whether preemptive assassination of a leader who might become a tyrant is morally justified—a question that resonates through history.',
      relatedLearningPoints: ['lp-caesar-1-dilemma'],
    },
    {
      id: 'q2',
      question: 'Why does Cassius target Brutus specifically for the conspiracy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Brutus is the best fighter in Rome',
        'Brutus\'s reputation for honor would legitimize the assassination',
        'Brutus hates Caesar more than anyone',
        'Brutus has the most money to fund the conspiracy',
      ],
      correctAnswer: 'Brutus\'s reputation for honor would legitimize the assassination',
      explanation: 'Brutus is known as "the noblest Roman." If he joins, the assassination appears principled rather than merely ambitious or envious.',
      relatedLearningPoints: ['lp-caesar-3-recruitment', 'lp-caesar-3-legitimacy'],
    },
    {
      id: 'q3',
      question: 'What does Brutus\'s soliloquy "It must be by his death" reveal about his reasoning?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He has personal hatred for Caesar',
        'He is killing based on what Caesar might become, not what he is',
        'He wants power for himself',
        'He believes Caesar has already committed crimes',
      ],
      correctAnswer: 'He is killing based on what Caesar might become, not what he is',
      explanation: 'Brutus admits Caesar hasn\'t acted tyrannically yet—he\'s killing to prevent future tyranny, which is philosophically problematic.',
      relatedLearningPoints: ['lp-caesar-4-soliloquy', 'lp-caesar-4-preemptive'],
    },
    {
      id: 'q4',
      question: 'What critical mistake does Brutus make regarding Mark Antony?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He refuses to let Antony speak at the funeral',
        'He kills Antony along with Caesar',
        'He lets Antony speak after him, allowing Antony to turn the crowd',
        'He makes Antony the new leader of Rome',
      ],
      correctAnswer: 'He lets Antony speak after him, allowing Antony to turn the crowd',
      explanation: 'Against Cassius\'s advice, Brutus allows Antony to speak. Brutus\'s faith in reason over emotion proves his undoing.',
      relatedLearningPoints: ['lp-caesar-5-mistake', 'lp-caesar-8-aftermath'],
    },
    {
      id: 'q5',
      question: 'What rhetorical strategy does Brutus use in his funeral speech?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Emotional appeals to love and grief',
        'Logical appeals to Roman honor and republican values',
        'Threats and intimidation',
        'Humor and entertainment',
      ],
      correctAnswer: 'Logical appeals to Roman honor and republican values',
      explanation: 'Brutus uses prose and logical reasoning, assuming Romans will be persuaded by principle. This reflects his character but underestimates human emotion.',
      relatedLearningPoints: ['lp-caesar-8-brutus-speech'],
    },
    {
      id: 'q6',
      question: 'How does Antony\'s "Friends, Romans, countrymen" speech manipulate the crowd?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He directly insults Brutus',
        'He uses irony, emotion, and physical evidence (Caesar\'s wounds, the will)',
        'He threatens them with military force',
        'He promises them positions in government',
      ],
      correctAnswer: 'He uses irony, emotion, and physical evidence (Caesar\'s wounds, the will)',
      explanation: 'Antony\'s masterful rhetoric combines ironic repetition of "honorable men," emotional display of Caesar\'s wounds, and the promise of Caesar\'s bequest to the people.',
      relatedLearningPoints: ['lp-caesar-9-antony-speech', 'lp-caesar-9-rhetoric'],
    },
    {
      id: 'q7',
      question: 'What does the murder of Cinna the Poet by the mob demonstrate?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The conspirators\' continued power',
        'How rhetoric unleashes irrational violence that cannot be controlled',
        'The people\'s love for poetry',
        'Antony\'s loss of control',
      ],
      correctAnswer: 'How rhetoric unleashes irrational violence that cannot be controlled',
      explanation: 'The mob kills Cinna even after learning he\'s the wrong man. This shows how inflammatory rhetoric creates violence beyond anyone\'s control.',
      relatedLearningPoints: ['lp-caesar-10-cinna', 'lp-caesar-10-violence'],
    },
    {
      id: 'q8',
      question: 'What is the significance of Caesar\'s ghost appearing to Brutus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It proves ghosts are real in Shakespeare\'s world',
        'It symbolizes that Brutus cannot escape the consequences of his deed',
        'It shows Caesar forgiving Brutus',
        'It is a simple scare tactic with no meaning',
      ],
      correctAnswer: 'It symbolizes that Brutus cannot escape the consequences of his deed',
      explanation: 'The ghost represents Brutus\'s guilty conscience and foreshadows his doom. Caesar\'s influence continues even in death.',
      relatedLearningPoints: ['lp-caesar-11-ghost', 'lp-caesar-11-consequence'],
    },
    {
      id: 'q9',
      question: 'Why does Brutus ultimately fail despite his noble intentions?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was not a good enough soldier',
        'He trusted too much in reason and underestimated human emotion and ambition',
        'He did not have enough money',
        'Caesar\'s ghost cursed him',
      ],
      correctAnswer: 'He trusted too much in reason and underestimated human emotion and ambition',
      explanation: 'Brutus\'s tragic flaw is his idealism—he believes others will act on principle as he does, not realizing that emotion and self-interest drive most people.',
      relatedLearningPoints: ['lp-caesar-12-tragedy', 'lp-caesar-12-irony'],
    },
    {
      id: 'q10',
      question: 'What is the ultimate irony of the assassination?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Caesar was already planning to give up power',
        'The conspirators preserved the Republic successfully',
        'It led to civil war and ultimately imperial rule—the opposite of what conspirators intended',
        'Brutus became the new dictator',
      ],
      correctAnswer: 'It led to civil war and ultimately imperial rule—the opposite of what conspirators intended',
      explanation: 'The assassination meant to preserve the Republic actually destroyed it. Octavian (Augustus) would soon become the first Emperor.',
      relatedLearningPoints: ['lp-caesar-12-irony', 'lp-caesar-13-aftermath'],
    },
    {
      id: 'q11',
      question: 'How does Julius Caesar connect to themes in Macbeth from Part II?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Both feature exactly the same characters',
        'Both explore assassination, ambition, and the haunting guilt that follows political murder',
        'Both are comedies about love',
        'Both are set in the same time period',
      ],
      correctAnswer: 'Both explore assassination, ambition, and the haunting guilt that follows political murder',
      explanation: 'While Macbeth kills for personal ambition and Brutus kills for principle, both plays explore how political murder destroys the perpetrator.',
      relatedLearningPoints: ['lp-caesar-13-connections'],
    },
    {
      id: 'q12',
      question: 'What lesson does Julius Caesar offer about political violence?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Violence is always the best solution',
        'Political assassination rarely achieves its intended goals and often makes things worse',
        'The ends always justify the means',
        'Democracy cannot survive without violence',
      ],
      correctAnswer: 'Political assassination rarely achieves its intended goals and often makes things worse',
      explanation: 'Shakespeare shows that even well-intentioned political violence creates uncontrollable consequences—a lesson that echoes through history.',
      relatedLearningPoints: ['lp-caesar-14-legacy'],
    },
  ],
};
