import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'quiz-chapter-1-hamlet',
  title: 'Chapter 1: Hamlet Quiz',
  description: 'Test your understanding of Shakespeare\'s most philosophical tragedy.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What distinguishes Hamlet from typical revenge tragedy heroes?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is too weak to fight and must rely on others',
        'He philosophizes and delays rather than acting immediately',
        'He refuses to seek revenge entirely',
        'He is unaware of who killed his father',
      ],
      correctAnswer: 'He philosophizes and delays rather than acting immediately',
      explanation: 'Unlike simple revenge heroes, Hamlet thinks deeply about the morality and consequences of revenge, creating delay that becomes the center of the drama.',
      relatedLearningPoints: ['lp-hamlet-4-subversion'],
    },
    {
      id: 'q2',
      question: 'Why does Hamlet need to verify the Ghost\'s claims before acting?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He doesn\'t believe in ghosts',
        'The Ghost could be a demon trying to damn Hamlet\'s soul through murder',
        'He wants to gather more witnesses first',
        'He needs legal evidence for a trial',
      ],
      correctAnswer: 'The Ghost could be a demon trying to damn Hamlet\'s soul through murder',
      explanation: 'In Renaissance theology, ghosts could be demons in disguise. If Hamlet kills based on demonic deception, he commits murder and damns his own soul.',
      relatedLearningPoints: ['lp-hamlet-2-ghost-command', 'lp-hamlet-2-theology'],
    },
    {
      id: 'q3',
      question: 'What does "The Mousetrap" (the play-within-a-play) reveal?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That Hamlet has gone mad',
        'That the actors are spies for Claudius',
        'That Claudius is guilty—his reaction proves the Ghost spoke truth',
        'That Gertrude helped murder King Hamlet',
      ],
      correctAnswer: 'That Claudius is guilty—his reaction proves the Ghost spoke truth',
      explanation: 'When Claudius flees the play that depicts a murder identical to what the Ghost described, his guilt is confirmed. Hamlet now has proof.',
      relatedLearningPoints: ['lp-hamlet-8-mousetrap', 'lp-hamlet-8-proof'],
    },
    {
      id: 'q4',
      question: 'What is the central question of the "To be or not to be" soliloquy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Whether to kill Claudius or expose him publicly',
        'Whether existence itself is worth the suffering it entails',
        'Whether to marry Ophelia or remain single',
        'Whether to trust Horatio with his secrets',
      ],
      correctAnswer: 'Whether existence itself is worth the suffering it entails',
      explanation: '"To be or not to be" is an existential meditation on whether life\'s suffering makes existence worth continuing, and what prevents us from ending it.',
      relatedLearningPoints: ['lp-hamlet-5-existential', 'lp-hamlet-5-paralysis'],
    },
    {
      id: 'q5',
      question: 'According to Hamlet, what prevents people from escaping life\'s suffering through death?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Religious laws forbidding suicide',
        'Love for family and friends',
        'Fear of what might come after death—"the undiscovered country"',
        'The hope that things will improve',
      ],
      correctAnswer: 'Fear of what might come after death—"the undiscovered country"',
      explanation: 'Hamlet argues that "the dread of something after death"—fear of the unknown—prevents us from escaping suffering through death.',
      relatedLearningPoints: ['lp-hamlet-5-existential'],
    },
    {
      id: 'q6',
      question: 'What does Hamlet mean by "conscience does make cowards of us all"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Moral guilt prevents us from doing evil',
        'Consciousness and overthinking paralyze our ability to act',
        'Religious conscience keeps us obedient',
        'Cowardice is a natural human trait',
      ],
      correctAnswer: 'Consciousness and overthinking paralyze our ability to act',
      explanation: 'Here "conscience" means consciousness. Hamlet argues that thinking too much about consequences prevents decisive action—a self-diagnosis of his own paralysis.',
      relatedLearningPoints: ['lp-hamlet-5-paralysis'],
    },
    {
      id: 'q7',
      question: 'How does Polonius\'s death trigger the play\'s tragic cascade?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It reveals Hamlet\'s plan to Claudius',
        'It drives Ophelia mad and arms Laertes with righteous vengeance',
        'It causes Gertrude to turn against Hamlet',
        'It forces Hamlet to flee Denmark immediately',
      ],
      correctAnswer: 'It drives Ophelia mad and arms Laertes with righteous vengeance',
      explanation: 'Hamlet\'s accidental killing of Polonius causes Ophelia\'s madness and death, and gives Laertes legitimate cause for revenge—creating the final catastrophe.',
      relatedLearningPoints: ['lp-hamlet-10-cascade', 'lp-hamlet-10-contrast'],
    },
    {
      id: 'q8',
      question: 'What is ironic about Hamlet\'s delay?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He acts too quickly and regrets it',
        'His delay causes more deaths than immediate action would have',
        'He delays because he enjoys power',
        'His delay allows him to escape Denmark',
      ],
      correctAnswer: 'His delay causes more deaths than immediate action would have',
      explanation: 'Hamlet\'s philosophical hesitation doesn\'t prevent tragedy—it multiplies it. Polonius, Ophelia, Rosencrantz, Guildenstern, Laertes, Gertrude, and Claudius all die.',
      relatedLearningPoints: ['lp-hamlet-10-cascade', 'lp-hamlet-11-causation'],
    },
    {
      id: 'q9',
      question: 'What are Hamlet\'s final words, "The rest is silence," often interpreted to mean?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is disappointed in his achievements',
        'He is refusing to forgive Claudius',
        'Death brings the silence his restless consciousness could never find in life',
        'He wants everyone to stop talking',
      ],
      correctAnswer: 'Death brings the silence his restless consciousness could never find in life',
      explanation: 'After a play full of words, questions, and philosophical struggle, "the rest is silence" suggests Hamlet finally finds peace in death—the ultimate answer to "To be or not to be."',
      relatedLearningPoints: ['lp-hamlet-13-silence', 'lp-hamlet-13-storytelling'],
    },
    {
      id: 'q10',
      question: 'Why does Hamlet want Horatio to survive and tell his story?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To punish Horatio for not helping him',
        'So Horatio can rule Denmark',
        'So his "wounded name" will be cleared through the telling',
        'To ensure Claudius\'s family is destroyed',
      ],
      correctAnswer: 'So his "wounded name" will be cleared through the telling',
      explanation: 'Hamlet\'s concern for his story shows that meaning matters even at the point of death—he wants to be understood, not condemned as a mere murderer.',
      relatedLearningPoints: ['lp-hamlet-13-storytelling'],
    },
    {
      id: 'q11',
      question: 'How does Laertes function as a foil to Hamlet?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Both are philosophical and hesitant',
        'Where Hamlet thinks and delays, Laertes acts immediately—and both approaches lead to tragedy',
        'Laertes represents comedy while Hamlet represents tragedy',
        'Laertes is loyal to Claudius while Hamlet opposes him',
      ],
      correctAnswer: 'Where Hamlet thinks and delays, Laertes acts immediately—and both approaches lead to tragedy',
      explanation: 'Laertes serves as Hamlet\'s foil by contrasting philosophical hesitation with impulsive action. Neither approach succeeds—Shakespeare shows both extremes are flawed.',
      relatedLearningPoints: ['lp-hamlet-10-contrast'],
    },
    {
      id: 'q12',
      question: 'Why does Hamlet endure as one of literature\'s greatest works?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It has the most exciting plot of any play',
        'It asks unanswerable questions about consciousness, action, and mortality that remain universally human',
        'It provides clear moral lessons about revenge',
        'It has a happy ending that audiences prefer',
      ],
      correctAnswer: 'It asks unanswerable questions about consciousness, action, and mortality that remain universally human',
      explanation: 'Hamlet endures because it dramatizes the human condition itself—our capacity for thought that both elevates and paralyzes us.',
      relatedLearningPoints: ['lp-hamlet-14-endurance', 'lp-hamlet-14-conclusion'],
    },
  ],
};
