import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-chapter-4-epilogue',
  title: 'Chapter 4: Shakespeare\'s Legacy Quiz',
  description: 'Test your understanding of Shakespeare\'s impact on language, literature, and culture.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'Approximately how many words and phrases did Shakespeare add to the English language?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'About 100',
        'About 500',
        'About 1,700',
        'About 10,000',
      ],
      correctAnswer: 'About 1,700',
      explanation: 'Shakespeare coined or first recorded approximately 1,700 words, from "assassination" to "eyeball" to "lonely."',
      relatedLearningPoints: ['lp-legacy-1-words'],
    },
    {
      id: 'q2',
      question: 'Why do Shakespeare\'s plays continue to be performed and adapted worldwide?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because there are laws requiring it',
        'Because no one has written anything new since then',
        'Because they explore universal human experiences that transcend time and culture',
        'Because they are all in the public domain',
      ],
      correctAnswer: 'Because they explore universal human experiences that transcend time and culture',
      explanation: 'Shakespeare\'s themes—love, jealousy, ambition, mortality, power—are fundamental to human experience, making his work perpetually relevant.',
      relatedLearningPoints: ['lp-legacy-2-universal'],
    },
    {
      id: 'q3',
      question: 'What is the "anxiety of influence" that Shakespeare created for later writers?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Fear that Shakespeare\'s ghost would haunt them',
        'The challenge of creating original work when Shakespeare has already explored human nature so thoroughly',
        'Worry about copyright issues',
        'Concern about being compared to actors',
      ],
      correctAnswer: 'The challenge of creating original work when Shakespeare has already explored human nature so thoroughly',
      explanation: 'Harold Bloom argued that Shakespeare\'s psychological insights were so complete that later writers must work in his shadow.',
      relatedLearningPoints: ['lp-legacy-3-influence'],
    },
    {
      id: 'q4',
      question: 'How has the "To be or not to be" soliloquy influenced Western thought?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It established laws about suicide',
        'It provided vocabulary for discussing existential questions about meaning and mortality',
        'It has had no influence outside theater',
        'It only influenced Danish culture',
      ],
      correctAnswer: 'It provided vocabulary for discussing existential questions about meaning and mortality',
      explanation: 'Hamlet\'s soliloquy gave Western culture language for contemplating existence itself, influencing philosophy, psychology, and everyday speech.',
      relatedLearningPoints: ['lp-legacy-4-existential'],
    },
    {
      id: 'q5',
      question: 'What makes Shakespeare\'s approach to adaptation unique?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He invented all his plots from nothing',
        'He never borrowed from other sources',
        'He transformed source materials into something greater while the core human truths remain adaptable',
        'He only wrote original comedies',
      ],
      correctAnswer: 'He transformed source materials into something greater while the core human truths remain adaptable',
      explanation: 'Shakespeare freely adapted histories, Italian novels, and classical sources. This tradition of adaptation continues—his plays have been reimagined in countless settings.',
      relatedLearningPoints: ['lp-legacy-5-adaptation'],
    },
    {
      id: 'q6',
      question: 'Why might a production set Macbeth in 1930s Chicago or Julius Caesar in modern corporate America?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To confuse the audience',
        'Because directors don\'t understand the original plays',
        'Because Shakespeare\'s themes translate across settings—ambition, power, and betrayal are universal',
        'To save money on costumes',
      ],
      correctAnswer: 'Because Shakespeare\'s themes translate across settings—ambition, power, and betrayal are universal',
      explanation: 'Shakespeare\'s insights into human nature transcend specific historical settings, making his plays endlessly adaptable to new contexts.',
      relatedLearningPoints: ['lp-legacy-6-settings'],
    },
    {
      id: 'q7',
      question: 'What role did Shakespeare play in establishing psychological realism in drama?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He ignored psychology entirely',
        'He created characters with complex inner lives whose thoughts the audience shares through soliloquy',
        'He only wrote about historical facts',
        'He invented psychotherapy',
      ],
      correctAnswer: 'He created characters with complex inner lives whose thoughts the audience shares through soliloquy',
      explanation: 'Shakespeare\'s use of soliloquy lets audiences enter characters\' minds, creating unprecedented psychological depth that influenced all subsequent drama.',
      relatedLearningPoints: ['lp-legacy-7-psychology'],
    },
    {
      id: 'q8',
      question: 'How did Shakespeare influence Romantic poets like Keats and Coleridge?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He had no influence on poetry',
        'They saw Shakespeare as a model of imaginative freedom and natural genius',
        'They rejected everything he wrote',
        'He taught them about science',
      ],
      correctAnswer: 'They saw Shakespeare as a model of imaginative freedom and natural genius',
      explanation: 'Romantic poets celebrated Shakespeare as the supreme example of natural genius, inspiring their own experiments with imagination and emotion.',
      relatedLearningPoints: ['lp-legacy-8-romantic'],
    },
    {
      id: 'q9',
      question: 'What is significant about Shakespeare\'s global reach today?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His plays are only performed in England',
        'His works are performed in virtually every language and adapted by cultures worldwide',
        'Only academics read him now',
        'His plays are too difficult for modern audiences',
      ],
      correctAnswer: 'His works are performed in virtually every language and adapted by cultures worldwide',
      explanation: 'From Kurosawa\'s Japanese adaptations to West Side Story to countless global productions, Shakespeare\'s work has become truly universal cultural property.',
      relatedLearningPoints: ['lp-legacy-9-global'],
    },
    {
      id: 'q10',
      question: 'What common English phrases did Shakespeare originate?',
      type: 'multiple-choice',
      points: 10,
      options: [
        '"Hello" and "goodbye"',
        '"Break the ice," "wild goose chase," "heart of gold," and many others',
        'Only theater terminology',
        'He didn\'t create any phrases we still use',
      ],
      correctAnswer: '"Break the ice," "wild goose chase," "heart of gold," and many others',
      explanation: 'Many everyday English phrases originated with Shakespeare, so embedded in the language that we use them without knowing their source.',
      relatedLearningPoints: ['lp-legacy-10-phrases'],
    },
  ],
};
