import type { Quiz } from '../../../types';

export const finalQuiz: Quiz = {
  id: 'quiz-final-shakespeare-part-3',
  title: 'Shakespeare Part III: Final Assessment',
  description: 'A comprehensive examination of Hamlet, Julius Caesar, The Tempest, and Shakespeare\'s enduring legacy.',
  passingScore: 75,
  allowRetry: true,
  questions: [
    // Hamlet Section
    {
      id: 'f-q1',
      question: 'What is Hamlet\'s central philosophical innovation compared to typical revenge tragedies?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The hero dies at the end',
        'The hero thinks about revenge rather than simply enacting it, creating psychological complexity',
        'There is a ghost',
        'The revenge is against a family member',
      ],
      correctAnswer: 'The hero thinks about revenge rather than simply enacting it, creating psychological complexity',
      explanation: 'Hamlet transforms revenge tragedy by making thought itself the drama—the hero\'s intellectual paralysis becomes more important than action.',
      relatedLearningPoints: ['lp-hamlet-4-subversion', 'lp-hamlet-5-paralysis'],
    },
    {
      id: 'f-q2',
      question: 'What does the "play within a play" (The Mousetrap) accomplish?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It entertains the court during a boring evening',
        'It proves Claudius\'s guilt through his reaction, confirming the Ghost\'s truth',
        'It reveals Hamlet\'s madness to everyone',
        'It causes Ophelia to go mad',
      ],
      correctAnswer: 'It proves Claudius\'s guilt through his reaction, confirming the Ghost\'s truth',
      explanation: 'Hamlet uses theater to catch the conscience of the king—when Claudius flees, his guilt is confirmed.',
      relatedLearningPoints: ['lp-hamlet-8-mousetrap', 'lp-hamlet-8-proof'],
    },
    // Julius Caesar Section
    {
      id: 'f-q3',
      question: 'Why does Brutus believe the assassination is justified?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Caesar has already become a tyrant',
        'Caesar insulted Brutus personally',
        'Brutus believes Caesar will become a tyrant if crowned, so preemptive action is necessary',
        'The gods commanded it',
      ],
      correctAnswer: 'Brutus believes Caesar will become a tyrant if crowned, so preemptive action is necessary',
      explanation: 'Brutus justifies killing Caesar based on what he might become—a philosophically troubling basis for political violence.',
      relatedLearningPoints: ['lp-caesar-4-soliloquy', 'lp-caesar-4-preemptive'],
    },
    {
      id: 'f-q4',
      question: 'What is the key difference between Brutus\'s and Antony\'s funeral speeches?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Brutus speaks longer',
        'Antony speaks in prose while Brutus uses verse',
        'Brutus appeals to reason and honor; Antony appeals to emotion and uses irony and physical evidence',
        'Only Brutus mentions Caesar by name',
      ],
      correctAnswer: 'Brutus appeals to reason and honor; Antony appeals to emotion and uses irony and physical evidence',
      explanation: 'This contrast demonstrates the power of emotional rhetoric over rational argument in swaying crowds—a lesson in political manipulation.',
      relatedLearningPoints: ['lp-caesar-8-brutus-speech', 'lp-caesar-9-antony-speech'],
    },
    // The Tempest Section
    {
      id: 'f-q5',
      question: 'What does Caliban\'s perspective add to our understanding of The Tempest?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Pure comic relief',
        'A critique of colonialism showing the colonized perspective on dispossession and cultural domination',
        'Evidence that Prospero is entirely good',
        'Nothing significant—he is just a monster',
      ],
      correctAnswer: 'A critique of colonialism showing the colonized perspective on dispossession and cultural domination',
      explanation: 'Caliban\'s claims to the island and his famous curse about language invite us to question Prospero\'s authority and colonialism itself.',
      relatedLearningPoints: ['lp-tempest-5-caliban', 'lp-tempest-5-colonialism'],
    },
    {
      id: 'f-q6',
      question: 'What triggers Prospero\'s decision to forgive rather than take revenge?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Miranda pleads with him',
        'He runs out of magical power',
        'Ariel describes the enemies\' suffering and appeals to Prospero\'s humanity',
        'The enemies apologize first',
      ],
      correctAnswer: 'Ariel describes the enemies\' suffering and appeals to Prospero\'s humanity',
      explanation: 'Ironically, the spirit Ariel reminds the human Prospero of humane feelings, leading to his choice of virtue over vengeance.',
      relatedLearningPoints: ['lp-tempest-10-choice', 'lp-tempest-10-humanity'],
    },
    // Cross-Play Comparisons
    {
      id: 'f-q7',
      question: 'How does Hamlet\'s approach to revenge contrast with Laertes\'s?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Hamlet acts immediately while Laertes hesitates',
        'Hamlet delays through philosophizing while Laertes acts impulsively—both approaches lead to tragedy',
        'They have exactly the same approach',
        'Laertes refuses revenge entirely',
      ],
      correctAnswer: 'Hamlet delays through philosophizing while Laertes acts impulsively—both approaches lead to tragedy',
      explanation: 'Laertes as foil shows that neither extreme thought nor extreme action leads to good outcomes—Shakespeare critiques both.',
      relatedLearningPoints: ['lp-hamlet-10-contrast', 'lp-hamlet-10-cascade'],
    },
    {
      id: 'f-q8',
      question: 'What connects the ghost in Hamlet to the ghost in Julius Caesar?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They are the same ghost',
        'Both represent unfinished business and the haunting consequences of political murder',
        'Neither ghost speaks',
        'Both give false information',
      ],
      correctAnswer: 'Both represent unfinished business and the haunting consequences of political murder',
      explanation: 'Shakespeare uses ghosts to symbolize how violent deaths create lasting consequences—the past haunts the present.',
      relatedLearningPoints: ['lp-hamlet-2-ghost-command', 'lp-caesar-11-ghost'],
    },
    {
      id: 'f-q9',
      question: 'How does The Tempest\'s ending differ fundamentally from Hamlet and Julius Caesar?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It has more deaths',
        'It offers reconciliation and forgiveness instead of tragic destruction',
        'The protagonist fails completely',
        'There is no resolution at all',
      ],
      correctAnswer: 'It offers reconciliation and forgiveness instead of tragic destruction',
      explanation: 'The Tempest resolves what tragedy could not—Prospero\'s choice to forgive breaks the cycle of violence that destroys Hamlet\'s Denmark and Caesar\'s Rome.',
      relatedLearningPoints: ['lp-tempest-14-synthesis', 'lp-tempest-14-resolution'],
    },
    // Synthesis Questions
    {
      id: 'f-q10',
      question: 'What theme connects all three plays in Part III?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romantic love',
        'Comedy and humor',
        'Betrayal, revenge, and the question of justice',
        'Religious devotion',
      ],
      correctAnswer: 'Betrayal, revenge, and the question of justice',
      explanation: 'Hamlet, Julius Caesar, and The Tempest all explore betrayal by close relations and the question of how to respond—revenge or forgiveness.',
      relatedLearningPoints: ['lp-hamlet-2-ghost-command', 'lp-caesar-1-dilemma', 'lp-tempest-10-choice'],
    },
    {
      id: 'f-q11',
      question: 'Why might Prospero be seen as a figure for Shakespeare himself?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Both lived on islands',
        'Both controlled spirits and created theatrical illusions, and both bid farewell to their art',
        'They have the same birthday',
        'Both were dukes',
      ],
      correctAnswer: 'Both controlled spirits and created theatrical illusions, and both bid farewell to their art',
      explanation: 'Prospero\'s magic mirrors Shakespeare\'s theatrical art, and his renunciation of magic reads as Shakespeare\'s farewell to the stage.',
      relatedLearningPoints: ['lp-tempest-12-metatheater', 'lp-tempest-12-farewell'],
    },
    {
      id: 'f-q12',
      question: 'What does Prospero mean by "the rarer action is in virtue than in vengeance"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Revenge is more common and easier; forgiveness requires greater moral strength',
        'Virtue is more rare and valuable than revenge',
        'Both statements are equivalent interpretations of the line',
        'Only the first interpretation is correct',
      ],
      correctAnswer: 'Both statements are equivalent interpretations of the line',
      explanation: 'Prospero recognizes that while revenge is natural, choosing forgiveness is the "rarer" and more noble path—it requires transcending natural impulses.',
      relatedLearningPoints: ['lp-tempest-10-choice', 'lp-tempest-11-renunciation'],
    },
    {
      id: 'f-q13',
      question: 'How does Part III complete the Shakespeare trilogy\'s exploration of tragedy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It repeats the same themes as Parts I and II',
        'It moves from tragic destruction through political tragedy to reconciliation, showing forgiveness as an alternative to vengeance',
        'It ignores the earlier parts entirely',
        'It only focuses on comedy',
      ],
      correctAnswer: 'It moves from tragic destruction through political tragedy to reconciliation, showing forgiveness as an alternative to vengeance',
      explanation: 'Part III synthesizes the trilogy: where Part I showed love\'s joy and sorrow and Part II explored dark ambition, Part III offers resolution through mercy.',
      relatedLearningPoints: ['lp-legacy-2-universal', 'lp-tempest-14-synthesis'],
    },
    {
      id: 'f-q14',
      question: 'What makes Shakespeare\'s exploration of human nature continue to resonate today?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His plots are completely original',
        'He captures universal human experiences—love, jealousy, ambition, mortality, power—that transcend time and culture',
        'His language is very simple',
        'His plays are very short',
      ],
      correctAnswer: 'He captures universal human experiences—love, jealousy, ambition, mortality, power—that transcend time and culture',
      explanation: 'Shakespeare\'s genius lies in dramatizing fundamental aspects of human experience that remain relevant across centuries and cultures.',
      relatedLearningPoints: ['lp-legacy-2-universal', 'lp-legacy-7-psychology'],
    },
    {
      id: 'f-q15',
      question: 'What is the significance of studying the Shakespeare trilogy as a whole?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It saves time compared to reading individual plays',
        'It reveals Shakespeare\'s range—from comedy to tragedy to reconciliation—and his consistent insight into human nature',
        'It proves Shakespeare wrote all his own plays',
        'It is required for academic credit',
      ],
      correctAnswer: 'It reveals Shakespeare\'s range—from comedy to tragedy to reconciliation—and his consistent insight into human nature',
      explanation: 'The trilogy structure shows Shakespeare\'s artistic breadth while demonstrating how his central concerns—love, power, justice—appear across genres.',
      relatedLearningPoints: ['lp-legacy-2-universal', 'lp-legacy-3-influence'],
    },
  ],
};
