import type { Quiz } from '../../../types';

/**
 * Chapter 3 Quiz: The Sirens and Scylla & Charybdis
 *
 * Tests understanding of impossible choices, sacrifice, knowledge vs safety,
 * and the ethical burdens of leadership in Greek mythology.
 */
export const chapter3Quiz: Quiz = {
  id: 'quiz-chapter-3',
  title: 'Chapter 3: The Sirens and Scylla & Charybdis',
  description: 'Test your understanding of Odysseus\'s impossible choices and the burden of command',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-sirens-warning',
      question: 'Who warned Odysseus about the dangers of the Sirens and Scylla & Charybdis?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Athena',
        'Circe',
        'Tiresias',
        'Hermes',
      ],
      correctAnswer: 'Circe',
      explanation: 'Circe warned Odysseus about the upcoming dangers after he returned from the Underworld, giving him specific instructions on how to handle each threat.',
      relatedLearningPoints: ['lp-chapter-3-circe-knowledge'],
    },
    {
      id: 'q2-sirens-knowledge',
      question: 'What did the Sirens promise to those who listened to their song?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Eternal life',
        'Great wealth and treasure',
        'Knowledge of all that has happened on earth',
        'Safe passage home',
      ],
      correctAnswer: 'Knowledge of all that has happened on earth',
      explanation: 'The Sirens tempted sailors not just with beautiful singing, but with the promise of knowledge - knowing all that has happened on earth. This makes their temptation intellectual as well as sensual.',
      relatedLearningPoints: ['lp-chapter-3-sirens-temptation'],
    },
    {
      id: 'q3-odysseus-plan',
      question: 'How did Odysseus plan to safely pass the Sirens?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He steered far around their island',
        'He plugged his crew\'s ears with wax and had himself bound to the mast',
        'He sang louder than the Sirens to drown them out',
        'He used magic from Circe to make them immune',
      ],
      correctAnswer: 'He plugged his crew\'s ears with wax and had himself bound to the mast',
      explanation: 'Odysseus wanted to experience the Sirens\' song (demonstrating his thirst for knowledge) but took precautions: his crew couldn\'t hear the song, and he couldn\'t act on it even though he could hear it.',
      relatedLearningPoints: ['lp-chapter-3-knowledge-restraint'],
    },
    {
      id: 'q4-impossible-choice',
      question: 'What impossible choice did Odysseus face at the strait?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Between saving his ship or his treasure',
        'Between facing Scylla (losing some men) or Charybdis (risking everyone)',
        'Between continuing the journey or returning home',
        'Between trusting the gods or relying on himself',
      ],
      correctAnswer: 'Between facing Scylla (losing some men) or Charybdis (risking everyone)',
      explanation: 'Odysseus faced an impossible choice: sail close to Scylla and lose six men for certain, or risk the whirlpool Charybdis which could destroy the entire ship. There was no good option.',
      relatedLearningPoints: ['lp-chapter-3-impossible-choice'],
    },
    {
      id: 'q5-odysseus-decision',
      question: 'Which danger did Odysseus choose to face, and why?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Charybdis, because he believed he could outsail the whirlpool',
        'Scylla, because losing some men was better than risking everyone',
        'Neither - he found a third path between them',
        'He let his crew decide by vote',
      ],
      correctAnswer: 'Scylla, because losing some men was better than risking everyone',
      explanation: 'Odysseus chose to sail closer to Scylla, accepting the certain loss of six men rather than risking the entire crew to Charybdis. This demonstrates tragic leadership - making an awful choice because the alternative is worse.',
      relatedLearningPoints: ['lp-chapter-3-leadership-burden'],
    },
    {
      id: 'q6-concealment',
      question: 'What did Odysseus conceal from his crew before facing Scylla?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That they would lose six men for certain',
        'That Charybdis was nearby',
        'That the Sirens had cursed them',
        'That the gods had abandoned them',
      ],
      correctAnswer: 'That they would lose six men for certain',
      explanation: 'Odysseus did not tell his crew that sailing past Scylla meant certain death for six of them. This raises ethical questions about leadership - was he protecting morale or denying them agency?',
      relatedLearningPoints: ['lp-chapter-3-tragic-knowledge'],
    },
    {
      id: 'q7-scylla-nature',
      question: 'What kind of monster was Scylla?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A giant whirlpool that swallowed ships',
        'A sea serpent with poisonous fangs',
        'A six-headed monster that lived in a cliff',
        'A beautiful woman who lured sailors to their doom',
      ],
      correctAnswer: 'A six-headed monster that lived in a cliff',
      explanation: 'Scylla was a six-headed monster living in a cliff opposite Charybdis. Each head could snatch one sailor, which is why Odysseus knew he would lose exactly six men.',
      relatedLearningPoints: ['lp-chapter-3-scylla-nature'],
    },
    {
      id: 'q8-knowledge-theme',
      question: 'What does Odysseus\'s choice to hear the Sirens\' song reveal about his character?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is reckless and puts himself in unnecessary danger',
        'He values knowledge and experience even at great risk',
        'He doesn\'t trust his crew to follow orders',
        'He wants to prove he is braver than other heroes',
      ],
      correctAnswer: 'He values knowledge and experience even at great risk',
      explanation: 'Odysseus could have simply plugged his own ears, but chose to experience the Sirens\' song. This reveals his defining characteristic: an insatiable curiosity and desire for knowledge, even when dangerous.',
      relatedLearningPoints: ['lp-chapter-3-knowledge-vs-safety'],
    },
    {
      id: 'q9-leadership-burden',
      question: 'How does the Scylla and Charybdis episode illustrate the burden of leadership?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Leaders must always choose the safest path',
        'Leaders must sometimes make terrible choices where any option causes harm',
        'Leaders should let their followers make dangerous decisions',
        'Leaders are cursed by the gods to suffer',
      ],
      correctAnswer: 'Leaders must sometimes make terrible choices where any option causes harm',
      explanation: 'Odysseus faces a choice where there is no good option - only degrees of terrible. He must choose who will die, carry that decision alone, and live with the consequences. This is the tragic burden of command.',
      relatedLearningPoints: ['lp-chapter-3-command-burden'],
    },
    {
      id: 'q10-foreshadowing',
      question: 'Why is Circe\'s warning significant to the story\'s structure?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It shows that the gods are helping Odysseus',
        'It creates dramatic irony - we know what\'s coming while Odysseus must still face it',
        'It proves Circe is the most powerful goddess',
        'It gives Odysseus a chance to avoid the dangers completely',
      ],
      correctAnswer: 'It creates dramatic irony - we know what\'s coming while Odysseus must still face it',
      explanation: 'Circe\'s foreknowledge creates dramatic irony. We know the terrible choice Odysseus will face, which builds tension as we watch him approach it. Knowledge of fate doesn\'t prevent fate.',
      relatedLearningPoints: ['lp-chapter-3-dramatic-irony'],
    },
  ],
};
