import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'quiz-chapter-1',
  title: 'Chapter 1: The Lotus-Eaters and the Cyclops Quiz',
  description: 'Test your knowledge of Odysseus\'s encounters with the Lotus-Eaters and Polyphemus the Cyclops.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What was the danger of the lotus plant?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It was poisonous and deadly',
        'It made people forget their desire to return home',
        'It turned people into plants',
        'It caused permanent blindness',
      ],
      correctAnswer: 'It made people forget their desire to return home',
      explanation: 'The lotus plant caused blissful forgetfulness, making those who ate it lose all desire to return home. This represented the danger of escapism and abandoning one\'s responsibilities.',
      relatedLearningPoints: ['chapter-1-lp-9-temptation', 'chapter-1-lp-10-nostos'],
    },
    {
      id: 'q2',
      question: 'What did Odysseus have to do to save his men from the Lotus-Eaters?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Give them an antidote',
        'Fight the Lotus-Eaters',
        'Forcibly drag them back to the ships and bind them',
        'Wait for the effects to wear off naturally',
      ],
      correctAnswer: 'Forcibly drag them back to the ships and bind them',
      explanation: 'Odysseus had to use force to save his men from themselves, dragging them weeping back to the ships and binding them until the lotus\'s effects wore off. This shows that leadership sometimes requires harsh compassion.',
      relatedLearningPoints: ['chapter-1-lp-13-force-necessary'],
    },
    {
      id: 'q3',
      question: 'What is "xenia" in ancient Greek culture?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The art of war and combat',
        'The sacred law of hospitality protected by Zeus',
        'A form of Greek poetry',
        'A type of sacrifice to the gods',
      ],
      correctAnswer: 'The sacred law of hospitality protected by Zeus',
      explanation: 'Xenia was the sacred Greek custom of hospitality, where hosts were obligated to provide food, shelter, and gifts to travelers, and guests must show respect. It was protected by Zeus himself, and violating xenia was a grave offense.',
      relatedLearningPoints: ['chapter-1-lp-18-xenia-violation'],
    },
    {
      id: 'q4',
      question: 'How did Polyphemus violate xenia?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He refused to offer wine to his guests',
        'He ate two of Odysseus\'s men and trapped the rest',
        'He stole their weapons',
        'He insulted their families',
      ],
      correctAnswer: 'He ate two of Odysseus\'s men and trapped the rest',
      explanation: 'Instead of offering hospitality as Greek custom demanded, Polyphemus devoured two of Odysseus\'s men and trapped the survivors, declaring that the gods meant nothing to him. This marked him as savage and impious.',
      relatedLearningPoints: ['chapter-1-lp-18-xenia-violation'],
    },
    {
      id: 'q5',
      question: 'What name did Odysseus give to Polyphemus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Stranger',
        'Nobody',
        'Odysseus',
        'The Wanderer',
      ],
      correctAnswer: 'Nobody',
      explanation: 'Odysseus cleverly called himself "Nobody" (Outis in Greek). When the blinded Cyclops cried "Nobody is attacking me!" the other Cyclopes thought he meant no one was attacking him and left. This demonstrates Odysseus\'s mastery of language as a weapon.',
      relatedLearningPoints: ['chapter-1-lp-23-wordplay'],
    },
    {
      id: 'q6',
      question: 'How did Odysseus and his men escape from the cave?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They killed Polyphemus while he slept',
        'They dug a tunnel through the wall',
        'They blinded him and hid under the sheep when he let them out',
        'They convinced him to let them go',
      ],
      correctAnswer: 'They blinded him and hid under the sheep when he let them out',
      explanation: 'Odysseus got Polyphemus drunk, blinded his eye with a heated olive stake, then he and his men escaped by clinging to the undersides of the sheep when the blind Cyclops released them to graze. This plan showed cunning intelligence over brute force.',
      relatedLearningPoints: ['chapter-1-lp-21-metis', 'chapter-1-lp-22-intelligence'],
    },
    {
      id: 'q7',
      question: 'What is "hubris" in Greek culture?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Divine wisdom',
        'Military strategy',
        'Excessive pride or arrogance',
        'Sacred hospitality',
      ],
      correctAnswer: 'Excessive pride or arrogance',
      explanation: 'Hubris is excessive pride or arrogance, often leading mortals to defy divine will or make foolish choices. It is the defining flaw of Greek tragic heroes and inevitably leads to punishment.',
      relatedLearningPoints: ['chapter-1-lp-27-hubris-definition'],
    },
    {
      id: 'q8',
      question: 'What was Odysseus\'s fatal mistake after escaping from Polyphemus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He forgot some of his men in the cave',
        'He revealed his true name and identity to the Cyclops',
        'He stole Polyphemus\'s sheep',
        'He attacked the other Cyclopes',
      ],
      correctAnswer: 'He revealed his true name and identity to the Cyclops',
      explanation: 'In a moment of hubris, Odysseus shouted his true name and lineage to Polyphemus. This allowed the Cyclops to pray to his father Poseidon for revenge, dooming Odysseus to ten more years of wandering.',
      relatedLearningPoints: ['chapter-1-lp-26-hubris-choice', 'chapter-1-lp-28-dramatic-irony'],
    },
    {
      id: 'q9',
      question: 'Who was Polyphemus\'s father, and how did this affect Odysseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Zeus, who remained neutral',
        'Poseidon, who cursed Odysseus to wander the seas',
        'Hades, who sent monsters after him',
        'Apollo, who withdrew his protection',
      ],
      correctAnswer: 'Poseidon, who cursed Odysseus to wander the seas',
      explanation: 'Polyphemus was the son of Poseidon, god of the sea. When Odysseus revealed his identity, Polyphemus prayed to his father for revenge. Poseidon cursed Odysseus to years of suffering at sea, turning the ocean itself against him.',
      relatedLearningPoints: ['chapter-1-lp-29-divine-retribution', 'chapter-1-lp-30-consequences'],
    },
    {
      id: 'q10',
      question: 'What Greek concept does Odysseus\'s escape plan exemplify?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Arete (excellence in battle)',
        'Metis (cunning intelligence)',
        'Kleos (glory through combat)',
        'Nostos (the journey home)',
      ],
      correctAnswer: 'Metis (cunning intelligence)',
      explanation: 'The escape plan exemplifies "metis"—cunning intelligence. Rather than using force (which would fail against the giant), Odysseus uses deception, patience, and clever planning. This is his defining characteristic throughout the Odyssey.',
      relatedLearningPoints: ['chapter-1-lp-21-metis', 'chapter-1-lp-22-intelligence'],
    },
    {
      id: 'q11',
      question: 'Why couldn\'t Odysseus simply kill Polyphemus in his sleep?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He didn\'t have strong enough weapons',
        'The Cyclops was immortal',
        'They would be trapped forever behind the massive boulder',
        'The other Cyclopes would hear and attack',
      ],
      correctAnswer: 'They would be trapped forever behind the massive boulder',
      explanation: 'Polyphemus had sealed the cave with a boulder so massive that twenty oxen couldn\'t move it. If they killed him, they would be trapped forever. Odysseus needed the Cyclops alive to move the stone, showing strategic thinking over immediate revenge.',
      relatedLearningPoints: ['chapter-1-lp-22-intelligence'],
    },
    {
      id: 'q12',
      question: 'What is the significance of an oath sworn by the river Styx?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It can be easily broken',
        'It only binds mortals, not gods',
        'It is absolutely binding, even for gods',
        'It requires a sacrifice to be valid',
      ],
      correctAnswer: 'It is absolutely binding, even for gods',
      explanation: 'The river Styx flows through the underworld, and oaths sworn by the Styx are absolutely binding, even for gods. Breaking such an oath results in terrible punishment. When Poseidon swears by the Styx to curse Odysseus, the curse becomes irreversible.',
      relatedLearningPoints: ['chapter-1-lp-29-divine-retribution'],
    },
    {
      id: 'q13',
      question: 'What does the Cyclops episode reveal about Odysseus\'s character?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is purely heroic without flaws',
        'He values intelligence over strength, but his pride is his weakness',
        'He is cruel and heartless',
        'He always makes perfect decisions',
      ],
      correctAnswer: 'He values intelligence over strength, but his pride is his weakness',
      explanation: 'The Cyclops episode shows Odysseus as a complex hero—brilliant and cunning (the escape plan) but flawed by hubris (revealing his name). His greatest strengths and weaknesses are intertwined, making him a realistic, multidimensional character.',
      relatedLearningPoints: ['chapter-1-lp-14-curiosity', 'chapter-1-lp-31-tragedy'],
    },
    {
      id: 'q14',
      question: 'What literary technique does Homer use when the audience knows Odysseus\'s mistake will lead to suffering, but Odysseus doesn\'t realize it yet?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Foreshadowing',
        'Dramatic irony',
        'Metaphor',
        'Personification',
      ],
      correctAnswer: 'Dramatic irony',
      explanation: 'This is dramatic irony—when the audience knows more than the character. We understand that revealing his name will bring Poseidon\'s wrath and ten more years of wandering, even as Odysseus triumphantly shouts his identity, unaware of the consequences.',
      relatedLearningPoints: ['chapter-1-lp-28-dramatic-irony'],
    },
    {
      id: 'q15',
      question: 'How does the Cyclops episode establish the central conflict of the Odyssey?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It introduces the war between Greeks and Trojans',
        'It creates eternal enmity between Odysseus and Poseidon',
        'It shows that all monsters hate heroes',
        'It proves that the gods are powerless',
      ],
      correctAnswer: 'It creates eternal enmity between Odysseus and Poseidon',
      explanation: 'Odysseus\'s blinding of Polyphemus and his prideful revelation of his identity brings Poseidon\'s curse upon him. This divine opposition becomes the central obstacle preventing his homecoming and drives the entire plot of the Odyssey.',
      relatedLearningPoints: ['chapter-1-lp-30-consequences', 'chapter-1-lp-31-tragedy'],
    },
  ],
};
