import type { Quiz } from '../../../types';

export const chapter5Quiz: Quiz = {
  id: 'quiz-chapter-5',
  title: 'Chapter 5: Homecoming and the Suitors\' Doom Quiz',
  description: 'Test your knowledge of Odysseus\'s return to Ithaca and his revenge on the suitors.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'Why did Calypso finally release Odysseus from her island?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She grew tired of him',
        'Zeus ordered her through Hermes to let him go',
        'Odysseus escaped on his own',
        'Poseidon demanded his release',
      ],
      correctAnswer: 'Zeus ordered her through Hermes to let him go',
      explanation: 'The gods, led by Zeus and Athena, decided it was time for Odysseus to return home. Zeus sent Hermes to command Calypso to release him.',
      relatedLearningPoints: ['lp-5-1-divine-intervention'],
    },
    {
      id: 'q2',
      question: 'Who rescued Odysseus after Poseidon shipwrecked him?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The goddess Athena',
        'Princess Nausicaa of Phaeacia',
        'King Alcinous',
        'His son Telemachus',
      ],
      correctAnswer: 'Princess Nausicaa of Phaeacia',
      explanation: 'After being shipwrecked by Poseidon, Odysseus was found on the shore by Princess Nausicaa, who showed him kindness and directed him to her father\'s palace.',
      relatedLearningPoints: ['lp-5-3-hospitality'],
    },
    {
      id: 'q3',
      question: 'Why did Athena disguise Odysseus as a beggar?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To punish him for his pride',
        'To test the loyalty of his household and approach safely',
        'To hide from Poseidon',
        'To steal from the suitors',
      ],
      correctAnswer: 'To test the loyalty of his household and approach safely',
      explanation: 'Athena disguised Odysseus as a beggar so he could enter his palace unrecognized, assess the situation, test who remained loyal to him, and plan his revenge against the suitors.',
      relatedLearningPoints: ['lp-5-6-identity'],
    },
    {
      id: 'q4',
      question: 'Who was the first to recognize the disguised Odysseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His wife Penelope',
        'His son Telemachus',
        'His loyal swineherd Eumaeus',
        'His old dog Argos',
      ],
      correctAnswer: 'His old dog Argos',
      explanation: 'Though Eumaeus showed hospitality without recognition, it was Odysseus\'s faithful old dog Argos who first recognized his master after 20 years, wagging his tail before dying.',
      relatedLearningPoints: ['lp-5-7-loyalty'],
    },
    {
      id: 'q5',
      question: 'What contest did Penelope announce to choose a new husband?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A wrestling match',
        'A poetry competition',
        'Stringing Odysseus\'s bow and shooting through twelve axe heads',
        'A chariot race',
      ],
      correctAnswer: 'Stringing Odysseus\'s bow and shooting through twelve axe heads',
      explanation: 'Penelope declared that whoever could string Odysseus\'s great bow and shoot an arrow through twelve axe heads would win her hand in marriage—a feat only Odysseus could accomplish.',
      relatedLearningPoints: ['lp-5-12-test'],
    },
    {
      id: 'q6',
      question: 'What test did Penelope use to confirm Odysseus\'s identity?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She asked about their wedding day',
        'She tested his knowledge of their immovable bed',
        'She asked him to describe a secret scar',
        'She showed him their son',
      ],
      correctAnswer: 'She tested his knowledge of their immovable bed',
      explanation: 'Penelope tested Odysseus by suggesting moving their bed. Only Odysseus knew that the bed was built around a living olive tree and couldn\'t be moved, proving his identity.',
      relatedLearningPoints: ['lp-5-13-recognition'],
    },
    {
      id: 'q7',
      question: 'Which theme is most central to Odysseus\'s return and revenge?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Divine mercy',
        'Justice and retribution',
        'Forgiveness and peace',
        'Wealth and power',
      ],
      correctAnswer: 'Justice and retribution',
      explanation: 'The slaughter of the suitors represents Greek concepts of justice and retribution. The suitors violated xenia (hospitality), consumed Odysseus\'s wealth, and threatened his family, earning their doom.',
      relatedLearningPoints: ['lp-5-14-justice'],
    },
    {
      id: 'q8',
      question: 'What quality did Penelope demonstrate by waiting 20 years for Odysseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Naivety',
        'Loyalty and faithfulness',
        'Weakness',
        'Foolishness',
      ],
      correctAnswer: 'Loyalty and faithfulness',
      explanation: 'Penelope\'s 20-year wait, her clever delaying tactics (like weaving and unweaving Laertes\' shroud), and her final test all demonstrate her remarkable loyalty and faithfulness to Odysseus.',
      relatedLearningPoints: ['lp-5-10-penelope-loyalty'],
    },
    {
      id: 'q9',
      question: 'How does the theme of "disguise and identity" function in the homecoming?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It shows that appearances don\'t matter',
        'It reveals true character through how people treat those they think are beneath them',
        'It demonstrates that deception is always wrong',
        'It proves that physical appearance is most important',
      ],
      correctAnswer: 'It reveals true character through how people treat those they think are beneath them',
      explanation: 'Odysseus\'s disguise as a beggar allows him to see people\'s true nature. The loyal servants treat him kindly despite his appearance, while the suitors show their corruption by abusing him.',
      relatedLearningPoints: ['lp-5-6-identity', 'lp-5-10-penelope-loyalty'],
    },
    {
      id: 'q10',
      question: 'What does the completion of Odysseus\'s journey represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The triumph of physical strength over all obstacles',
        'The successful completion of the hero\'s journey archetype',
        'The victory of gods over mortals',
        'The importance of wealth and power',
      ],
      correctAnswer: 'The successful completion of the hero\'s journey archetype',
      explanation: 'Odysseus\'s return to Ithaca, reclaiming his identity, his throne, and his family represents the final stage of the hero\'s journey—the return with wisdom gained from his trials.',
      relatedLearningPoints: ['lp-5-14-homecoming'],
    },
  ],
};
