import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-chapter-4',
  title: 'Chapter 4: The Cattle of Helios and Calypso\'s Isle Quiz',
  description: 'Test your knowledge of divine law, loyalty, and the consequences of defying the gods.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'Why did Odysseus warn his crew not to touch the cattle on Thrinacia?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The cattle were poisonous',
        'The cattle belonged to the sun god Helios and were sacred',
        'The cattle were too wild to capture',
        'Odysseus wanted them all for himself',
      ],
      correctAnswer: 'The cattle belonged to the sun god Helios and were sacred',
      explanation: 'Odysseus had been warned by Tiresias and Circe that the cattle of Helios were sacred and must not be harmed. Violating this divine law would bring terrible consequences.',
      relatedLearningPoints: ['lp-ch4-1-divine-law', 'lp-ch4-2-warning'],
    },
    {
      id: 'q2',
      question: 'What led the crew to make their fatal decision to eat the sacred cattle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They were drunk and didn\'t care',
        'They thought Odysseus was lying',
        'They were starving and desperate for survival',
        'They wanted to anger Zeus',
      ],
      correctAnswer: 'They were starving and desperate for survival',
      explanation: 'The crew faced starvation after being stranded on the island. The conflict between survival and divine law created an impossible choice, and hunger ultimately drove them to transgression.',
      relatedLearningPoints: ['lp-ch4-3-survival', 'lp-ch4-4-hunger'],
    },
    {
      id: 'q3',
      question: 'When did the crew kill and eat the sacred cattle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Immediately after landing on the island',
        'While Odysseus was watching',
        'While Odysseus slept, away from camp',
        'After asking Odysseus for permission',
      ],
      correctAnswer: 'While Odysseus slept, away from camp',
      explanation: 'The crew waited until Odysseus went inland to pray, demonstrating their knowledge that what they were doing was wrong and their attempt to avoid his leadership.',
      relatedLearningPoints: ['lp-ch4-5-betrayal'],
    },
    {
      id: 'q4',
      question: 'How did Helios respond when he learned his cattle had been slaughtered?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He forgave them immediately',
        'He demanded vengeance from Zeus',
        'He killed the crew himself',
        'He warned them never to return',
      ],
      correctAnswer: 'He demanded vengeance from Zeus',
      explanation: 'Helios was outraged and threatened to shine his light in the Underworld instead of on Earth if Zeus did not punish the transgressors, showing the seriousness of violating divine law.',
      relatedLearningPoints: ['lp-ch4-6-helios-rage', 'lp-ch4-7-divine-demand'],
    },
    {
      id: 'q5',
      question: 'What was Zeus\'s punishment for the crew\'s transgression?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He turned them all into cattle',
        'He destroyed their ship with a thunderbolt, killing everyone except Odysseus',
        'He banished them to a desert island',
        'He made them servants of Helios forever',
      ],
      correctAnswer: 'He destroyed their ship with a thunderbolt, killing everyone except Odysseus',
      explanation: 'Zeus struck the ship with his thunderbolt, drowning all the crew. Only Odysseus survived because he had not partaken of the sacred cattle.',
      relatedLearningPoints: ['lp-ch4-8-zeus-punishment', 'lp-ch4-9-sole-survivor'],
    },
    {
      id: 'q6',
      question: 'Why did Odysseus survive when his crew perished?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He could swim better than his crew',
        'He had not eaten the sacred cattle',
        'Zeus favored him over the others',
        'He made a deal with Poseidon',
      ],
      correctAnswer: 'He had not eaten the sacred cattle',
      explanation: 'Odysseus survived because he was innocent of the transgression. He had warned his crew and was praying away from camp when they killed the cattle, demonstrating that divine justice targets the guilty.',
      relatedLearningPoints: ['lp-ch4-9-sole-survivor'],
    },
    {
      id: 'q7',
      question: 'Who was Calypso?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A sea monster who attacked Odysseus',
        'A mortal queen who helped Odysseus',
        'A nymph goddess who kept Odysseus captive on her island',
        'Odysseus\'s wife waiting in Ithaca',
      ],
      correctAnswer: 'A nymph goddess who kept Odysseus captive on her island',
      explanation: 'Calypso was a beautiful nymph goddess who lived on the island of Ogygia. She rescued Odysseus but then kept him captive, offering immortality in exchange for his companionship.',
      relatedLearningPoints: ['lp-ch4-10-calypso', 'lp-ch4-11-ogygia'],
    },
    {
      id: 'q8',
      question: 'How long was Odysseus held captive on Calypso\'s island?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'One year',
        'Three years',
        'Seven years',
        'Ten years',
      ],
      correctAnswer: 'Seven years',
      explanation: 'Odysseus spent seven years on Ogygia with Calypso. Despite her offers of immortality and comfort, he longed to return home to Penelope and Ithaca.',
      relatedLearningPoints: ['lp-ch4-12-captivity', 'lp-ch4-13-years'],
    },
    {
      id: 'q9',
      question: 'What did Calypso offer Odysseus to make him stay?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Great wealth and treasure',
        'Immortality and eternal youth',
        'An army to conquer Ithaca',
        'Magical powers',
      ],
      correctAnswer: 'Immortality and eternal youth',
      explanation: 'Calypso offered Odysseus the greatest gift a goddess could give a mortal: immortality. Yet even this could not overcome his desire to return home, showing the power of his loyalty and longing.',
      relatedLearningPoints: ['lp-ch4-14-immortality-offer'],
    },
    {
      id: 'q10',
      question: 'Who pleaded with Zeus to release Odysseus from Calypso\'s island?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Poseidon',
        'Athena',
        'Hermes',
        'Penelope',
      ],
      correctAnswer: 'Athena',
      explanation: 'Athena, Odysseus\'s divine patron, pleaded before the council of the gods for his release. She argued that he had suffered enough and deserved to return home to his family.',
      relatedLearningPoints: ['lp-ch4-15-athena-plea', 'lp-ch4-16-divine-council'],
    },
    {
      id: 'q11',
      question: 'What theme is most strongly demonstrated by the crew\'s decision to eat the cattle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The conflict between immediate survival and long-term consequences',
        'The power of friendship',
        'The importance of cooking skills',
        'The superiority of humans over gods',
      ],
      correctAnswer: 'The conflict between immediate survival and long-term consequences',
      explanation: 'The crew faces an impossible choice: starve now or face divine punishment later. This dilemma explores themes of desperation, loyalty to divine law, and the tragic consequences of choosing immediate relief over future safety.',
      relatedLearningPoints: ['lp-ch4-3-survival', 'lp-ch4-17-consequences'],
    },
    {
      id: 'q12',
      question: 'What does Odysseus\'s time on Calypso\'s island reveal about his character?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He values home and family above immortality and comfort',
        'He is easily satisfied with luxury',
        'He has forgotten about Penelope',
        'He prefers the company of goddesses to mortals',
      ],
      correctAnswer: 'He values home and family above immortality and comfort',
      explanation: 'Despite being offered immortality and living in paradise with a beautiful goddess, Odysseus weeps daily for home. This demonstrates that his deepest values are loyalty, family, and belonging, not power or eternal life.',
      relatedLearningPoints: ['lp-ch4-18-loyalty', 'lp-ch4-19-homesickness'],
    },
  ],
};
