import type { Quiz } from '../../../types';

export const epilogueQuiz: Quiz = {
  id: 'quiz-epilogue',
  title: 'Epilogue: The Hero\'s Legacy Quiz',
  description: 'Test your understanding of The Odyssey\'s influence and the oral tradition that preserved it.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'epilogue-q1',
      question: 'Why does Athena intervene to stop the conflict between Odysseus and the suitors\' families?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She wants to protect Odysseus from harm',
        'She is bored with human conflicts',
        'The cycle of blood vengeance threatens to destroy Ithaca entirely',
        'Zeus ordered her to help the suitors\' families',
      ],
      correctAnswer: 'The cycle of blood vengeance threatens to destroy Ithaca entirely',
      explanation: 'Athena intervenes because the blood feud culture would create an endless cycle of violence that would tear Ithaca apart. Divine intervention breaks the cycle that humans cannot escape on their own.',
      relatedLearningPoints: ['epilogue-lp-8-vendetta', 'epilogue-lp-10-divine-resolution'],
    },
    {
      id: 'epilogue-q2',
      question: 'How does Homer show that Penelope\'s heroism parallels Odysseus\'s?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She also goes on a physical journey',
        'She uses cunning and intelligence to survive her own trials',
        'She defeats the suitors in combat',
        'She receives help from the same gods',
      ],
      correctAnswer: 'She uses cunning and intelligence to survive her own trials',
      explanation: 'Penelope\'s cleverness—especially her trick of weaving and unweaving Laertes\' shroud—shows she uses the same intelligence and cunning that characterize Odysseus. Her heroism is domestic rather than martial, but equally strategic.',
      relatedLearningPoints: ['epilogue-lp-3-parallel', 'epilogue-lp-4-penelope-heroism'],
    },
    {
      id: 'epilogue-q3',
      question: 'What does the reunion of three generations (Laertes, Odysseus, Telemachus) symbolize?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The importance of having many male heirs',
        'The continuity of family, tradition, and legitimate kingship',
        'The inevitability of aging and death',
        'The superiority of youth over age',
      ],
      correctAnswer: 'The continuity of family, tradition, and legitimate kingship',
      explanation: 'The three generations standing together represent the unbroken line of legitimate rule and the continuation of family tradition. It symbolizes that the kingdom and its values will endure.',
      relatedLearningPoints: ['epilogue-lp-6-generations'],
    },
    {
      id: 'epilogue-q4',
      question: 'What do ancient Greek pottery depictions of Odyssey scenes tell us about the epic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Only wealthy people knew the stories',
        'The stories were widely known across social classes',
        'The pottery was created before the oral poetry',
        'Visual art was more important than the oral tradition',
      ],
      correctAnswer: 'The stories were widely known across social classes',
      explanation: 'The appearance of Odyssey scenes on everyday pottery shows the epic was part of popular culture, not just elite literature. Common people knew and valued these stories.',
      relatedLearningPoints: ['epilogue-lp-12-material-culture'],
    },
    {
      id: 'epilogue-q5',
      question: 'What were "formulaic phrases" in oral epic poetry?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Magical spells used by the characters',
        'Repeated phrases like "rosy-fingered dawn" that helped singers remember',
        'The official rules for writing poetry',
        'Mistakes made by amateur performers',
      ],
      correctAnswer: 'Repeated phrases like "rosy-fingered dawn" that helped singers remember',
      explanation: 'Formulaic phrases were repeated combinations of words that fit the epic meter and helped oral poets compose and remember the poetry in performance, serving as building blocks for improvisation.',
      relatedLearningPoints: ['epilogue-lp-13-oral-composition'],
    },
    {
      id: 'epilogue-q6',
      question: 'How did rhapsodes perform The Odyssey before it was written down?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They memorized every word exactly',
        'They read from written scrolls',
        'They improvised using learned formulas and story patterns',
        'They made up entirely new stories each time',
      ],
      correctAnswer: 'They improvised using learned formulas and story patterns',
      explanation: 'Rhapsodes didn\'t memorize verbatim but rather learned the story framework, characters, and formulaic building blocks, then composed in performance. Each telling was both familiar and unique.',
      relatedLearningPoints: ['epilogue-lp-14-performance'],
    },
    {
      id: 'epilogue-q7',
      question: 'Approximately when did Homer give final form to The Odyssey?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Around 1200 BCE, during the Trojan War',
        'Around 750 BCE, as writing was adopted in Greece',
        'Around 300 BCE, in Alexandria',
        'Around 20 BCE, when Virgil wrote the Aeneid',
      ],
      correctAnswer: 'Around 750 BCE, as writing was adopted in Greece',
      explanation: 'Most scholars date Homer\'s composition to around 750 BCE, coinciding with the adoption of alphabetic writing in Greece. The stories themselves were much older, passed down orally for generations.',
      relatedLearningPoints: ['epilogue-lp-15-chronology'],
    },
    {
      id: 'epilogue-q8',
      question: 'What is the "hero\'s journey" pattern identified by Joseph Campbell?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A pattern found only in Greek epics',
        'A universal pattern of departure, trials, and return found across cultures',
        'A modern invention with no connection to ancient stories',
        'A pattern that only applies to male heroes',
      ],
      correctAnswer: 'A universal pattern of departure, trials, and return found across cultures',
      explanation: 'Campbell identified a universal narrative pattern—the monomyth—that appears across cultures and time periods. The Odyssey is a prime example, with its clear structure of departure from Troy, trials at sea, and return to Ithaca.',
      relatedLearningPoints: ['epilogue-lp-16-literary-influence', 'epilogue-lp-19-hero-pattern'],
    },
    {
      id: 'epilogue-q9',
      question: 'How has The Odyssey influenced modern storytelling?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It has had little influence outside classical studies',
        'Its patterns appear in modern works from Star Wars to Ulysses',
        'Modern authors deliberately avoid using its patterns',
        'It only influenced ancient Roman literature',
      ],
      correctAnswer: 'Its patterns appear in modern works from Star Wars to Ulysses',
      explanation: 'The Odyssey\'s influence is vast, from direct adaptations like Joyce\'s Ulysses to narrative patterns in films like Star Wars. Its hero\'s journey structure, archetypal characters, and themes continue to shape storytelling across all media.',
      relatedLearningPoints: ['epilogue-lp-16-literary-influence', 'epilogue-lp-17-archetypes'],
    },
    {
      id: 'epilogue-q10',
      question: 'What does it mean that "odyssey" has become a common English word?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'People have forgotten the original epic',
        'The epic\'s cultural impact is so deep it shaped our language',
        'It is a coincidence with no real significance',
        'Only scholars use the word anymore',
      ],
      correctAnswer: 'The epic\'s cultural impact is so deep it shaped our language',
      explanation: 'When we use "odyssey" to mean any long, eventful journey, we\'re unconsciously referencing the ancient epic. This shows how deeply The Odyssey has penetrated Western culture—so fundamental that we use its words without thinking about their origin.',
      relatedLearningPoints: ['epilogue-lp-18-language'],
    },
    {
      id: 'epilogue-q11',
      question: 'Which trait do many later literary heroes share with Odysseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Relying purely on physical strength',
        'Using intelligence and cunning rather than brute force',
        'Avoiding all conflict',
        'Never facing supernatural threats',
      ],
      correctAnswer: 'Using intelligence and cunning rather than brute force',
      explanation: 'Odysseus established the archetype of the clever hero who uses intelligence, disguise, and strategy rather than just physical prowess. This pattern appears in countless later heroes from Sherlock Holmes to modern protagonists.',
      relatedLearningPoints: ['epilogue-lp-19-hero-pattern'],
    },
    {
      id: 'epilogue-q12',
      question: 'Why did The Odyssey need to be written down to survive?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Oral tradition was about to disappear completely',
        'Writing preserves a fixed version while oral performance varies',
        'The rhapsodes all died suddenly',
        'People stopped caring about the stories',
      ],
      correctAnswer: 'Writing preserves a fixed version while oral performance varies',
      explanation: 'While oral tradition kept the stories alive for centuries, writing created a fixed, standardized version that could be copied and transmitted exactly. This preserved the specific form we know today, though it lost the spontaneity of live performance.',
      relatedLearningPoints: ['epilogue-lp-13-oral-composition', 'epilogue-lp-14-performance'],
    },
    {
      id: 'epilogue-q13',
      question: 'What role did visual arts like pottery play in preserving The Odyssey?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They were decoration with no educational purpose',
        'They helped spread and preserve the epic\'s imagery alongside oral and written traditions',
        'They replaced the need for oral poetry',
        'They were created only after the epic was forgotten',
      ],
      correctAnswer: 'They helped spread and preserve the epic\'s imagery alongside oral and written traditions',
      explanation: 'Visual arts worked in concert with oral and written traditions to preserve and spread The Odyssey. Pottery, sculpture, and other art forms kept the imagery alive and accessible to people across different levels of literacy.',
      relatedLearningPoints: ['epilogue-lp-12-material-culture'],
    },
    {
      id: 'epilogue-q14',
      question: 'How long is the span from The Odyssey\'s setting to modern adaptations?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'About 500 years',
        'About 1,000 years',
        'About 2,000 years',
        'Over 3,000 years',
      ],
      correctAnswer: 'Over 3,000 years',
      explanation: 'From the Trojan War setting (around 1200 BCE) to modern adaptations, The Odyssey spans over 3,000 years of continuous cultural relevance. This extraordinary longevity demonstrates its universal themes and enduring power.',
      relatedLearningPoints: ['epilogue-lp-15-chronology'],
    },
    {
      id: 'epilogue-q15',
      question: 'What does the epic\'s conclusion teach about the transition from war to peace?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Victory in battle is all that matters',
        'Peace is easily achieved after defeating enemies',
        'Breaking the cycle of violence requires more than human effort',
        'Revenge should always be pursued',
      ],
      correctAnswer: 'Breaking the cycle of violence requires more than human effort',
      explanation: 'The epic shows that humans trapped in blood feuds cannot break the cycle alone—divine intervention is needed to impose peace. This reflects the difficulty of moving from vengeance culture to civil society, requiring external authority (gods or law) to end the cycle.',
      relatedLearningPoints: ['epilogue-lp-1-cycle', 'epilogue-lp-10-divine-resolution'],
    },
  ],
};
