import type { Quiz } from '../../../types';

export const chapter5Quiz: Quiz = {
  id: 'quiz-chapter-5',
  title: 'Chapter 5: Aristotle Quiz',
  description: 'Test your understanding of Aristotle\'s philosophy, including his critique of Plato, four causes, virtue ethics, teleology, logic, and political theory.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What was Aristotle\'s main critique of Plato\'s Theory of Forms?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Forms are too perfect to be useful',
        'If Forms are separate from physical things, they cannot explain physical things',
        'There are too many Forms to remember',
        'Forms contradict mathematical principles',
      ],
      correctAnswer: 'If Forms are separate from physical things, they cannot explain physical things',
      explanation: 'Aristotle argued that if the Forms exist in a separate transcendent realm, they cannot serve as explanations for the physical world we experience. He proposed instead that form exists in matter, not separately from it.',
      relatedLearningPoints: ['lp-ch5-2-aristotle-critique'],
    },
    {
      id: 'q2',
      question: 'Which of the following best describes Aristotle\'s empirical approach to knowledge?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Knowledge comes only from pure reason and mathematical proof',
        'Knowledge begins with sensory observation, then moves to classification and explanation',
        'Knowledge requires mystical contemplation of transcendent truths',
        'Knowledge is impossible because the senses always deceive us',
      ],
      correctAnswer: 'Knowledge begins with sensory observation, then moves to classification and explanation',
      explanation: 'Unlike Plato\'s emphasis on pure reason, Aristotle insisted on empirical observation as the starting point for knowledge. He observed and classified hundreds of species, then developed explanations based on those observations.',
      relatedLearningPoints: ['lp-ch5-3-empiricism', 'lp-ch5-3-scientific-method'],
    },
    {
      id: 'q3',
      question: 'Match the example to the correct Aristotelian cause: "The bronze that makes up a statue"',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Material Cause',
        'Formal Cause',
        'Efficient Cause',
        'Final Cause',
      ],
      correctAnswer: 'Material Cause',
      explanation: 'The material cause is what something is made of—the underlying matter. Bronze is the material cause of the statue, just as wood is the material cause of a table.',
      relatedLearningPoints: ['lp-ch5-5-four-causes'],
    },
    {
      id: 'q4',
      question: 'What is the "Final Cause" in Aristotle\'s four causes?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The last thing that happens chronologically',
        'The purpose or end (telos) for which something exists or was made',
        'The material that something is made from',
        'The shape or structure of something',
      ],
      correctAnswer: 'The purpose or end (telos) for which something exists or was made',
      explanation: 'The final cause is the purpose or telos—the "what for" of something. For example, the final cause of a knife is cutting, the final cause of an eye is seeing, and the final cause of a human is to exercise reason and achieve eudaimonia.',
      relatedLearningPoints: ['lp-ch5-5-four-causes', 'lp-ch5-6-teleology'],
    },
    {
      id: 'q5',
      question: 'What does "telos" mean in Aristotle\'s philosophy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The material substance of a thing',
        'The natural end, purpose, or goal toward which something develops',
        'The efficient cause that produces change',
        'The form or structure of a thing',
      ],
      correctAnswer: 'The natural end, purpose, or goal toward which something develops',
      explanation: 'Telos is the natural end or purpose inherent in something. An acorn\'s telos is to become an oak tree; a human\'s telos is to exercise reason and achieve eudaimonia. This teleological view sees nature as purposive.',
      relatedLearningPoints: ['lp-ch5-6-teleology'],
    },
    {
      id: 'q6',
      question: 'According to Aristotle, what is the telos (natural end) of human beings?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To experience as much pleasure as possible',
        'To gain power and wealth',
        'To exercise reason excellently and achieve eudaimonia (flourishing)',
        'To survive and reproduce',
      ],
      correctAnswer: 'To exercise reason excellently and achieve eudaimonia (flourishing)',
      explanation: 'Aristotle argued that the human function is what makes us distinctively human—our capacity for reason. By exercising reason excellently through virtuous and contemplative living, we achieve eudaimonia (flourishing).',
      relatedLearningPoints: ['lp-ch5-7-human-function'],
    },
    {
      id: 'q7',
      question: 'What is eudaimonia in Aristotle\'s ethics?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Temporary pleasure or happiness',
        'Complete freedom from all constraints',
        'Flourishing or living well—the highest human good',
        'Wealth and material success',
      ],
      correctAnswer: 'Flourishing or living well—the highest human good',
      explanation: 'Eudaimonia is often translated as "happiness," but better captures "flourishing" or "living well." It is achieved through exercising reason virtuously and is the ultimate end of human action.',
      relatedLearningPoints: ['lp-ch5-7-human-function'],
    },
    {
      id: 'q8',
      question: 'In Aristotle\'s virtue ethics, where does virtue lie?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'In following divine commands without question',
        'In maximizing pleasure for the greatest number',
        'In the mean between two extremes (vices of deficiency and excess)',
        'In achieving perfect rationality without emotion',
      ],
      correctAnswer: 'In the mean between two extremes (vices of deficiency and excess)',
      explanation: 'The doctrine of the mean holds that virtue is a middle path between extremes. For example, courage is the mean between cowardice (deficiency) and recklessness (excess). The mean is not a mathematical midpoint but requires practical wisdom.',
      relatedLearningPoints: ['lp-ch5-8-virtue-mean', 'lp-ch5-9-golden-mean'],
    },
    {
      id: 'q9',
      question: 'How does Aristotle say we develop virtue?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'We are born with virtue—it is innate',
        'Through study and memorization of ethical rules',
        'Through habit and practice—by repeatedly performing virtuous actions',
        'Through mystical revelation or divine grace',
      ],
      correctAnswer: 'Through habit and practice—by repeatedly performing virtuous actions',
      explanation: 'Aristotle emphasized that virtue is not innate but developed through habit. We become just by doing just acts, brave by doing brave acts, generous by doing generous acts—until virtuous behavior becomes our character.',
      relatedLearningPoints: ['lp-ch5-8-habit'],
    },
    {
      id: 'q10',
      question: 'What is a syllogism in Aristotle\'s logic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A form of poetic meter used in Greek tragedy',
        'A type of mathematical equation',
        'A form of deductive reasoning with two premises leading to a necessary conclusion',
        'A method of empirical observation',
      ],
      correctAnswer: 'A form of deductive reasoning with two premises leading to a necessary conclusion',
      explanation: 'A syllogism is Aristotle\'s systematic form of logical argument: two premises lead to a necessary conclusion. For example: "All men are mortal, Socrates is a man, therefore Socrates is mortal." This was the foundation of formal logic.',
      relatedLearningPoints: ['lp-ch5-11-logic'],
    },
    {
      id: 'q11',
      question: 'Which of the following is NOT genuinely from Aristotle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The Four Causes (material, formal, efficient, final)',
        'The Doctrine of the Mean',
        'The Theory of Forms (perfect Forms in a transcendent realm)',
        'Teleology (everything has a natural purpose)',
      ],
      correctAnswer: 'The Theory of Forms (perfect Forms in a transcendent realm)',
      explanation: 'The Theory of Forms was Plato\'s idea, which Aristotle explicitly rejected. Aristotle argued that form exists in matter, not in a separate transcendent realm. The other options are genuinely Aristotelian.',
      relatedLearningPoints: ['lp-ch5-12-distinguish'],
    },
    {
      id: 'q12',
      question: 'In Aristotle\'s classification of constitutions, what is "polity"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Rule by one person for their own benefit (tyranny)',
        'Rule by the wealthy few for their own benefit (oligarchy)',
        'Constitutional government by the many for the common good',
        'Rule by the virtuous few for the common good (aristocracy)',
      ],
      correctAnswer: 'Constitutional government by the many for the common good',
      explanation: 'Polity is constitutional government by the many for the common good—combining democratic participation with constitutional limits. Aristotle favored it as the most stable and practical constitution for most cities.',
      relatedLearningPoints: ['lp-ch5-13-constitutions', 'lp-ch5-13-polity'],
    },
    {
      id: 'q13',
      question: 'How many types of constitutions did Aristotle identify, and what determined the classification?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Three types, based on how many people rule',
        'Six types, based on who rules (one/few/many) and for whose benefit',
        'Two types, based on whether they are just or unjust',
        'Four types, based on the four causes',
      ],
      correctAnswer: 'Six types, based on who rules (one/few/many) and for whose benefit',
      explanation: 'Aristotle identified six types: three good forms (monarchy, aristocracy, polity) where rulers govern for the common good, and three corrupt forms (tyranny, oligarchy, democracy in his sense) where rulers govern for their own benefit.',
      relatedLearningPoints: ['lp-ch5-13-constitutions'],
    },
    {
      id: 'q14',
      question: 'What did Aristotle mean by saying "Man is by nature a political animal"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Humans are naturally deceptive and power-hungry',
        'Humans naturally form political communities (poleis) to achieve flourishing',
        'Humans should avoid politics and live alone',
        'Humans are naturally democratic',
      ],
      correctAnswer: 'Humans naturally form political communities (poleis) to achieve flourishing',
      explanation: 'Aristotle argued that humans are naturally political because we achieve our telos—flourishing—only in association with others in a polis. Political community is not artificial but natural to human beings.',
      relatedLearningPoints: ['lp-ch5-10-key-ideas'],
    },
    {
      id: 'q15',
      question: 'Which best describes the relationship between Aristotle\'s philosophy and empirical observation?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Aristotle rejected empirical observation in favor of pure reason',
        'Aristotle emphasized empirical observation as the foundation for knowledge, combined with systematic reasoning',
        'Aristotle believed observation was important only for ethics, not natural science',
        'Aristotle thought the senses always deceive us',
      ],
      correctAnswer: 'Aristotle emphasized empirical observation as the foundation for knowledge, combined with systematic reasoning',
      explanation: 'Aristotle\'s approach combined careful empirical observation (he studied over 500 species) with systematic logical reasoning. This contrasted with Plato\'s emphasis on pure reason and anticipated the scientific method.',
      relatedLearningPoints: ['lp-ch5-3-empiricism', 'lp-ch5-3-scientific-method', 'lp-ch5-15-synthesis'],
    },
  ],
};
