import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-chapter-4',
  title: 'Chapter 4: Plato Quiz',
  description: 'Test your understanding of Plato\'s Theory of Forms, the Allegory of the Cave, and his political philosophy.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What is the Theory of Forms?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The idea that all knowledge comes from sense experience',
        'The belief that eternal, perfect Forms exist beyond the physical world',
        'The theory that the universe is made of atoms',
        'The claim that knowledge is impossible',
      ],
      correctAnswer: 'The belief that eternal, perfect Forms exist beyond the physical world',
      explanation: 'Plato\'s Theory of Forms posits that perfect, eternal, unchanging Forms exist in a realm beyond the physical world, and that physical objects are merely imperfect copies of these Forms.',
      relatedLearningPoints: ['lp-ch4-2-forms-intro', 'lp-ch4-3-two-realms'],
    },
    {
      id: 'q2',
      question: 'In the Allegory of the Cave, what do the shadows on the wall represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The Forms themselves',
        'The deceptive appearances of the physical world',
        'Mathematical truths',
        'The wisdom of Socrates',
      ],
      correctAnswer: 'The deceptive appearances of the physical world',
      explanation: 'The shadows represent the misleading appearances that people mistake for reality. Most people live their lives seeing only shadows—reflections and illusions—never grasping the true Forms.',
      relatedLearningPoints: ['lp-ch4-4-allegory'],
    },
    {
      id: 'q3',
      question: 'What does the sun symbolize in the Allegory of the Cave?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Physical light',
        'The Form of the Good, the highest truth',
        'Democratic government',
        'The teachings of Socrates',
      ],
      correctAnswer: 'The Form of the Good, the highest truth',
      explanation: 'The sun represents the Form of the Good—the ultimate source of truth, knowledge, and reality. Just as the sun makes physical things visible, the Good makes all other Forms intelligible.',
      relatedLearningPoints: ['lp-ch4-4-allegory'],
    },
    {
      id: 'q4',
      question: 'According to Plato, what are the three parts of the soul?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Body, mind, and spirit',
        'Past, present, and future',
        'Reason, spirit, and appetite',
        'Courage, wisdom, and justice',
      ],
      correctAnswer: 'Reason, spirit, and appetite',
      explanation: 'Plato divides the soul into reason (which seeks truth), spirit (which seeks honor), and appetite (which seeks physical pleasure). Justice means each part performs its proper function, with reason ruling.',
      relatedLearningPoints: ['lp-ch4-7-tripartite'],
    },
    {
      id: 'q5',
      question: 'What are the three classes in Plato\'s ideal Republic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Rich, middle class, and poor',
        'Citizens, slaves, and foreigners',
        'Philosopher-Kings, Guardians, and Producers',
        'Priests, warriors, and farmers',
      ],
      correctAnswer: 'Philosopher-Kings, Guardians, and Producers',
      explanation: 'Plato\'s Republic mirrors the tripartite soul: Philosopher-Kings (reason) rule, Guardians (spirit) defend, and Producers (appetite) provide material goods. Each class performs its natural function.',
      relatedLearningPoints: ['lp-ch4-7-analogy', 'lp-ch4-9-republic'],
    },
    {
      id: 'q6',
      question: 'Why does Plato argue that philosophers should rule?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because they are the wealthiest citizens',
        'Because they have grasped the Form of the Good and know what is truly just',
        'Because they are the best warriors',
        'Because the people elect them',
      ],
      correctAnswer: 'Because they have grasped the Form of the Good and know what is truly just',
      explanation: 'Plato argues that only philosophers who have completed rigorous education and glimpsed the Form of the Good possess the knowledge necessary to rule justly. Political power requires wisdom, not popularity.',
      relatedLearningPoints: ['lp-ch4-8-justice', 'lp-ch4-10a-meritocracy'],
    },
    {
      id: 'q7',
      question: 'Why do Philosopher-Kings and Guardians have no private property in Plato\'s Republic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To punish them for seeking power',
        'To eliminate selfish interests that might corrupt their judgment',
        'Because Plato believed all wealth is evil',
        'To make them dependent on the Producers',
      ],
      correctAnswer: 'To eliminate selfish interests that might corrupt their judgment',
      explanation: 'Plato eliminates private property and family for the ruling classes to ensure they have no personal interests competing with the common good. Without wealth or family to advance, they can rule impartially.',
      relatedLearningPoints: ['lp-ch4-9-communism'],
    },
    {
      id: 'q8',
      question: 'What is the "Third Man Argument" criticism of Plato?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That Plato needed a third person to explain his theory',
        'That explaining resemblance between objects and Forms requires infinite additional Forms',
        'That there are three types of knowledge',
        'That democracy requires three branches of government',
      ],
      correctAnswer: 'That explaining resemblance between objects and Forms requires infinite additional Forms',
      explanation: 'Aristotle argued that if a physical object resembles its Form, there must be another Form to explain that resemblance, leading to an infinite regress. This undermines Plato\'s explanatory project.',
      relatedLearningPoints: ['lp-ch4-13-third-man'],
    },
    {
      id: 'q9',
      question: 'What does Plato mean by saying education is "turning the soul from darkness to light"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That schools should have better lighting',
        'That education redirects the soul from physical appearances toward eternal Forms',
        'That students should study during the day',
        'That education removes all mystery from life',
      ],
      correctAnswer: 'That education redirects the soul from physical appearances toward eternal Forms',
      explanation: 'Education is not adding information to the mind, but redirecting the soul\'s attention from the changing, deceptive physical world toward the eternal realm of Forms—from ignorance to knowledge.',
      relatedLearningPoints: ['lp-ch4-5-education'],
    },
    {
      id: 'q10',
      question: 'According to Plato, what is justice in the soul?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Treating all desires equally',
        'Each part of the soul performing its proper function, with reason ruling',
        'Eliminating all emotions',
        'Following whatever the majority wants',
      ],
      correctAnswer: 'Each part of the soul performing its proper function, with reason ruling',
      explanation: 'For Plato, justice is not equality or majority rule, but harmonious hierarchy—each part doing what it does best. In the just soul, reason rules, spirit supports reason, and appetites obey.',
      relatedLearningPoints: ['lp-ch4-8-justice'],
    },
    {
      id: 'q11',
      question: 'Why was Plato critical of democracy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because he believed monarchy was better',
        'Because democracy allows the ignorant to make decisions and is prone to demagoguery',
        'Because he wanted to rule Athens himself',
        'Because democracy is too slow and inefficient',
      ],
      correctAnswer: 'Because democracy allows the ignorant to make decisions and is prone to demagoguery',
      explanation: 'Plato saw democracy as rule by the unqualified masses who are easily manipulated by rhetoric and emotion. He believed democracy inevitably degenerates into tyranny when demagogues seize power by exploiting popular passions.',
      relatedLearningPoints: ['lp-ch4-10b-anti-democracy'],
    },
    {
      id: 'q12',
      question: 'How did Socrates\'s execution influence Plato\'s philosophy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It made him abandon philosophy entirely',
        'It drove him to seek objective standards of truth and justice beyond political opinion',
        'It convinced him democracy was the best form of government',
        'It had no significant influence',
      ],
      correctAnswer: 'It drove him to seek objective standards of truth and justice beyond political opinion',
      explanation: 'The unjust execution of the wisest man by democratic Athens convinced Plato that society needed objective, eternal standards of truth and justice—the Forms—rather than relying on shifting popular opinion.',
      relatedLearningPoints: ['lp-ch4-1-socrates-influence'],
    },
    {
      id: 'q13',
      question: 'Which realm does Plato consider more real?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The physical world we can see and touch',
        'The realm of eternal Forms',
        'Both are equally real',
        'Neither exists—reality is an illusion',
      ],
      correctAnswer: 'The realm of eternal Forms',
      explanation: 'Plato argues that the eternal, unchanging Forms are more real than the temporary, changing physical world. Physical objects are merely imperfect copies or shadows of the true reality—the Forms.',
      relatedLearningPoints: ['lp-ch4-3-two-realms'],
    },
    {
      id: 'q14',
      question: 'What is the relationship between Plato\'s tripartite soul and his ideal city?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They are unrelated',
        'The structure of the just soul mirrors the structure of the just city',
        'The city came first, then Plato invented the soul theory to match',
        'They contradict each other',
      ],
      correctAnswer: 'The structure of the just soul mirrors the structure of the just city',
      explanation: 'Plato draws a direct analogy: just as the soul has reason, spirit, and appetite, the city has philosopher-kings, guardians, and producers. Justice in both requires each part performing its proper function.',
      relatedLearningPoints: ['lp-ch4-7-analogy'],
    },
    {
      id: 'q15',
      question: 'According to critics like Karl Popper, what is dangerous about Plato\'s Republic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It is too democratic',
        'It is a blueprint for totalitarianism that sacrifices individual freedom to elite rule',
        'It allows too much private property',
        'It gives too much power to the Producers',
      ],
      correctAnswer: 'It is a blueprint for totalitarianism that sacrifices individual freedom to elite rule',
      explanation: 'Popper argued that Plato\'s Republic abolishes individual freedom, censors art, and concentrates power in the hands of an elite who claim special access to truth—characteristics of totalitarian regimes.',
      relatedLearningPoints: ['lp-ch4-13-totalitarian'],
    },
  ],
};
