import type { Quiz } from '../../../types';

export const chapter6Quiz: Quiz = {
  id: 'quiz-chapter-6',
  title: 'Chapter 6: The Hellenistic Philosophers Quiz',
  description: 'Test your understanding of Epicureanism, Stoicism, and Skepticism, including their approaches to achieving tranquility (ataraxia) and the good life.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What historical event marked the beginning of the Hellenistic period and changed the focus of philosophy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The trial and death of Socrates',
        'The death of Alexander the Great and the collapse of city-state independence',
        'The founding of Plato\'s Academy',
        'The Persian Wars',
      ],
      correctAnswer: 'The death of Alexander the Great and the collapse of city-state independence',
      explanation: 'Alexander\'s death in 323 BCE left behind a vast empire that transformed the Greek world from small, independent city-states into cosmopolitan kingdoms. This political instability shifted philosophy from grand political and metaphysical questions to personal ethics and finding peace in uncertain times.',
      relatedLearningPoints: ['lp-ch6-1-context', 'lp-ch6-1-shift'],
    },
    {
      id: 'q2',
      question: 'What is ataraxia, the common goal of all three major Hellenistic schools?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Perfect knowledge of all things',
        'Political power and influence',
        'Tranquility, peace of mind, freedom from disturbance',
        'Wealth and material comfort',
      ],
      correctAnswer: 'Tranquility, peace of mind, freedom from disturbance',
      explanation: 'Ataraxia means tranquility or peace of mind—freedom from anxiety, fear, and mental disturbance. Though Epicureans, Stoics, and Skeptics disagreed about how to achieve it, all three schools made ataraxia their central goal.',
      relatedLearningPoints: ['lp-ch6-3-ataraxia'],
    },
    {
      id: 'q3',
      question: 'How did Hellenistic philosophy differ from classical Greek philosophy (Plato and Aristotle)?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It focused more on metaphysics and cosmology',
        'It shifted from grand questions about the cosmos and ideal state to personal ethics and achieving tranquility',
        'It rejected all use of reason and logic',
        'It emphasized political theory over individual ethics',
      ],
      correctAnswer: 'It shifted from grand questions about the cosmos and ideal state to personal ethics and achieving tranquility',
      explanation: 'Hellenistic philosophy was a response to political instability. Instead of Plato\'s Forms or Aristotle\'s systematic metaphysics, Hellenistic schools focused on practical questions: "How should I live? How can I find peace?" Philosophy became therapy for the soul.',
      relatedLearningPoints: ['lp-ch6-1-shift', 'lp-ch6-3-therapy'],
    },
    {
      id: 'q4',
      question: 'What did Epicurus mean by "pleasure" as the highest good?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Maximum indulgence in food, drink, and bodily pleasures',
        'Ataraxia—freedom from pain and mental disturbance, achieved through simple living',
        'Political power and public recognition',
        'Intellectual achievement and fame',
      ],
      correctAnswer: 'Ataraxia—freedom from pain and mental disturbance, achieved through simple living',
      explanation: 'Epicurus distinguished his philosophy from hedonism. By "pleasure" he meant the absence of pain (physical) and disturbance (mental)—ataraxia. Simple pleasures like bread, water, and friendship suffice; luxury creates dependence and anxiety.',
      relatedLearningPoints: ['lp-ch6-4-pleasure', 'lp-ch6-6-friendship'],
    },
    {
      id: 'q5',
      question: 'Why did Epicurus adopt Democritus\'s atomism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To prove the existence of the gods',
        'To free people from fear of death and divine punishment by showing the soul is material and mortal',
        'To explain mathematical principles',
        'To justify political authority',
      ],
      correctAnswer: 'To free people from fear of death and divine punishment by showing the soul is material and mortal',
      explanation: 'Epicurus used atomism therapeutically: if everything (including the soul) is made of atoms that disperse at death, then there is no afterlife, no punishment, no reward. "Death is nothing to us"—when we exist, death does not; when death comes, we do not exist.',
      relatedLearningPoints: ['lp-ch6-4-atomism', 'lp-ch6-5-death-argument'],
    },
    {
      id: 'q6',
      question: 'What was the Epicurean "fourfold remedy" (tetrapharmakos)?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Four types of pleasure to pursue',
        'Four cures for physical ailments',
        'Four remedies for anxiety: don\'t fear god, don\'t worry about death, what is good is easy to get, what is terrible is easy to endure',
        'Four stages of philosophical education',
      ],
      correctAnswer: 'Four remedies for anxiety: don\'t fear god, don\'t worry about death, what is good is easy to get, what is terrible is easy to endure',
      explanation: 'The tetrapharmakos addressed the four main sources of human anxiety: fear of gods (who don\'t interfere in human affairs), fear of death (which is nothing to us), difficulty of achieving good (simple pleasures suffice), and inability to endure evil (pain is brief or manageable).',
      relatedLearningPoints: ['lp-ch6-4-tetrapharmakos'],
    },
    {
      id: 'q7',
      question: 'Why did Epicurus advocate "living unknown" (lathe biōsas) and withdrawing from political life?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because he believed democracy was unjust',
        'Because political life brings constant anxiety, competition, and danger',
        'Because he thought politics was boring',
        'Because he wanted to gain more political power secretly',
      ],
      correctAnswer: 'Because political life brings constant anxiety, competition, and danger',
      explanation: 'Epicurus saw political ambition as a major source of anxiety—the desire for fame, power, and honor creates endless competition and fear. He advocated withdrawal to a private community (the Garden) where friendship and philosophy could flourish without political strife.',
      relatedLearningPoints: ['lp-ch6-6-politics'],
    },
    {
      id: 'q8',
      question: 'What is the central Stoic claim about virtue and happiness?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Virtue is good but health and wealth are necessary for happiness',
        'Virtue alone is sufficient for happiness; external circumstances are "indifferents"',
        'Virtue is impossible to achieve',
        'Virtue must be balanced with pleasure',
      ],
      correctAnswer: 'Virtue alone is sufficient for happiness; external circumstances are "indifferents"',
      explanation: 'This radical claim distinguished Stoicism from Aristotle. While Aristotle thought external goods contributed to happiness, Stoics insisted that virtue alone suffices—a wise person can be happy even in poverty, illness, or exile. Health and wealth are "preferred indifferents" but not essential.',
      relatedLearningPoints: ['lp-ch6-7-virtue-sufficient', 'lp-ch6-8-indifferents'],
    },
    {
      id: 'q9',
      question: 'What is the Stoic "dichotomy of control"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The distinction between gods and mortals',
        'The distinction between what is "up to us" (judgments, character) and what is "not up to us" (external circumstances)',
        'The distinction between Greek and barbarian',
        'The distinction between body and soul',
      ],
      correctAnswer: 'The distinction between what is "up to us" (judgments, character) and what is "not up to us" (external circumstances)',
      explanation: 'The dichotomy of control is foundational to Stoic ethics. We control our judgments, intentions, and character but not health, wealth, reputation, or others\' actions. Happiness comes from perfecting what we control and accepting what we cannot change with equanimity.',
      relatedLearningPoints: ['lp-ch6-8-dichotomy'],
    },
    {
      id: 'q10',
      question: 'What is the Logos in Stoic philosophy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A logical argument or syllogism',
        'Divine reason pervading and ordering the entire universe, of which human reason is a fragment',
        'A written text of philosophical teachings',
        'The spoken word used in debate',
      ],
      correctAnswer: 'Divine reason pervading and ordering the entire universe, of which human reason is a fragment',
      explanation: 'Stoics were pantheists who identified God with Nature and Logos (reason). This divine reason orders all things rationally. Human reason is a spark of this cosmic rationality. To live according to nature means exercising reason in harmony with the Logos.',
      relatedLearningPoints: ['lp-ch6-8-logos'],
    },
    {
      id: 'q11',
      question: 'How did Stoics view fate and determinism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They rejected determinism and believed in complete free will',
        'They believed everything happens by random chance',
        'They believed everything follows necessarily from divine reason; acceptance of fate brings tranquility',
        'They believed fate exists but should be resisted',
      ],
      correctAnswer: 'They believed everything follows necessarily from divine reason; acceptance of fate brings tranquility',
      explanation: 'Stoics embraced cosmic determinism: all events follow necessarily from the rational order of the Logos. What seems bad is part of a larger rational plan we may not understand. Resisting fate causes suffering; accepting it with understanding brings peace.',
      relatedLearningPoints: ['lp-ch6-8-logos', 'lp-ch6-9-maxims'],
    },
    {
      id: 'q12',
      question: 'What is epochē in Skeptical philosophy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A type of logical argument',
        'Suspension of judgment on all questions that cannot be resolved with certainty',
        'Complete denial of all claims',
        'Absolute certainty about all things',
      ],
      correctAnswer: 'Suspension of judgment on all questions that cannot be resolved with certainty',
      explanation: 'Epochē (suspension of judgment) is the core Skeptical practice. Rather than affirming or denying dogmatic claims, Skeptics note that arguments on both sides are equally strong (equipollent), leading them to withhold judgment. This suspension, surprisingly, brings ataraxia.',
      relatedLearningPoints: ['lp-ch6-10-skepticism', 'lp-ch6-10-equipollence'],
    },
    {
      id: 'q13',
      question: 'How did Skeptics claim to achieve ataraxia (tranquility)?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'By finding certain truth about all philosophical questions',
        'By ceasing to pursue impossible certainty and suspending judgment on unanswerable questions',
        'By withdrawing completely from society',
        'By accepting Stoic determinism',
      ],
      correctAnswer: 'By ceasing to pursue impossible certainty and suspending judgment on unanswerable questions',
      explanation: 'Skeptics achieved tranquility paradoxically: not by finding answers but by ceasing to seek certain answers to inherently uncertain questions. Anxiety arises from dogmatic commitment to beliefs, not from following appearances pragmatically without belief.',
      relatedLearningPoints: ['lp-ch6-10-ataraxia-skeptical'],
    },
    {
      id: 'q14',
      question: 'What did Skeptics mean by "equipollent arguments"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Arguments that are completely identical',
        'Arguments of equal strength on both sides of a question, making judgment impossible',
        'Arguments that prove the same conclusion',
        'Arguments that use the same logical form',
      ],
      correctAnswer: 'Arguments of equal strength on both sides of a question, making judgment impossible',
      explanation: 'Skeptics practiced finding equipollent (equally weighted) arguments for and against any philosophical claim. For example: arguments that the senses are reliable versus unreliable. When both sides seem equally strong, the rational response is suspension of judgment.',
      relatedLearningPoints: ['lp-ch6-10-equipollence'],
    },
    {
      id: 'q15',
      question: 'How did all three Hellenistic schools view philosophy itself?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'As abstract speculation with no practical application',
        'As therapy or medicine for the soul—a practical guide to achieving tranquility and living well',
        'As a purely intellectual exercise for the educated elite',
        'As religious doctrine requiring faith',
      ],
      correctAnswer: 'As therapy or medicine for the soul—a practical guide to achieving tranquility and living well',
      explanation: 'Despite their differences, Epicureans, Stoics, and Skeptics all conceived philosophy as therapeutic—medicine for anxiety, fear, and suffering. They provided not just theories but concrete practices for living: withdrawing to the Garden, practicing the dichotomy of control, suspending judgment.',
      relatedLearningPoints: ['lp-ch6-3-therapy', 'lp-ch6-11-practical', 'lp-ch6-12-legacy'],
    },
  ],
};
