import type { Quiz } from '../../../types';

export const finalQuiz: Quiz = {
  id: 'quiz-shakespeare-part-2-final',
  title: 'Shakespeare Part II: Final Assessment',
  description: 'Comprehensive test of your understanding of Power, Ambition, Jealousy & Guilt across all three tragedies.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What is the central theme uniting all three plays in Part II?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'External betrayal and revenge',
        'Internal psychological forces (ambition, jealousy, pride) destroying from within',
        'Romantic love conquering all obstacles',
        'Divine intervention restoring justice',
      ],
      correctAnswer: 'Internal psychological forces (ambition, jealousy, pride) destroying from within',
      explanation: 'Unlike external conflicts, Part II explores how internal corruptions—ambition (Macbeth), jealousy (Othello), pride (Lear)—destroy the tragic heroes from within.',
      relatedLearningPoints: ['lp-lear-18-part2-synthesis', 'lp-macbeth-16-part2'],
    },

    {
      id: 'q2',
      question: 'Compare Macbeth and Othello: how do they differ in their awareness of moral wrongdoing?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Both know they are doing evil',
        'Neither understands they are doing wrong',
        'Macbeth knows his actions are evil but proceeds; Othello believes he acts righteously',
        'Othello knows; Macbeth is deceived',
      ],
      correctAnswer: 'Macbeth knows his actions are evil but proceeds; Othello believes he acts righteously',
      explanation: 'Macbeth agonizes over Duncan\'s murder knowing it\'s wrong. Othello murders Desdemona believing it\'s justice. This makes Othello\'s tragedy even more terrible.',
      relatedLearningPoints: ['lp-othello-12-contrast-macbeth', 'lp-macbeth-4-pursuit'],
    },

    {
      id: 'q3',
      question: 'What role do supernatural elements play in Macbeth versus the other tragedies?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'All three plays feature heavy supernatural intervention',
        'Only Macbeth has supernatural elements (the Weird Sisters); the others are purely psychological',
        'King Lear has the most supernatural elements',
        'None of the plays feature any supernatural elements',
      ],
      correctAnswer: 'Only Macbeth has supernatural elements (the Weird Sisters); the others are purely psychological',
      explanation: 'Macbeth\'s witches externalize internal desires. Othello and Lear have no supernatural elements—their tragedies are entirely human and psychological.',
      relatedLearningPoints: ['lp-macbeth-3-supernatural', 'lp-othello-1-domestic'],
    },

    {
      id: 'q4',
      question: 'Which character serves as manipulator in Othello, and how does this differ from Macbeth?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Desdemona manipulates Othello; Lady Macbeth helps Macbeth gain power',
        'Iago manipulates Othello into jealousy; Lady Macbeth pushes Macbeth toward ambition',
        'Both plays feature identical manipulation dynamics',
        'Neither play features manipulation',
      ],
      correctAnswer: 'Iago manipulates Othello into jealousy; Lady Macbeth pushes Macbeth toward ambition',
      explanation: 'Both plays explore manipulation, but Lady Macbeth pushes Macbeth toward his existing ambition, while Iago creates jealousy in Othello where little existed before.',
      relatedLearningPoints: ['lp-macbeth-5-manipulation', 'lp-othello-7-insinuation'],
    },

    {
      id: 'q5',
      question: 'What is the significance of "nothing" in King Lear?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'It\'s a minor theme with little importance',
        'It structures the entire play: what Cordelia says, what Lear becomes, what remains',
        'It only refers to Cordelia\'s response in the love test',
        'It means wealth and material possessions',
      ],
      correctAnswer: 'It structures the entire play: what Cordelia says, what Lear becomes, what remains',
      explanation: 'Cordelia says "nothing," Lear is reduced to "nothing," and the play questions whether any meaning remains after everything is stripped away.',
      relatedLearningPoints: ['lp-lear-1-nothing', 'lp-lear-3-nothing'],
    },

    {
      id: 'q6',
      question: 'How does dramatic irony function differently across the three plays?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'All three use identical dramatic irony techniques',
        'Macbeth and Othello use it heavily (we know truth, characters don\'t); Lear uses less',
        'None of the plays use dramatic irony',
        'Only King Lear uses dramatic irony',
      ],
      correctAnswer: 'Macbeth and Othello use it heavily (we know truth, characters don\'t); Lear uses less',
      explanation: 'In Macbeth, we know the prophecies will betray him. In Othello, we know Desdemona is innocent. Both create agonizing tension as we watch inevitable tragedy.',
      relatedLearningPoints: ['lp-othello-10-irony', 'lp-macbeth-14-equivocation'],
    },

    {
      id: 'q7',
      question: 'Compare the psychological transformations in Macbeth and Othello',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Macbeth becomes morally numb; Othello\'s language disintegrates from poetry to fragments',
        'Both maintain the same psychological state throughout',
        'Othello becomes numb; Macbeth\'s language fragments',
        'Neither undergoes psychological transformation',
      ],
      correctAnswer: 'Macbeth becomes morally numb; Othello\'s language disintegrates from poetry to fragments',
      explanation: 'Macbeth\'s repeated murders make him numb to death itself. Othello\'s jealousy destroys his eloquence, transforming poetry into brutal fragments.',
      relatedLearningPoints: ['lp-macbeth-8-numbness', 'lp-othello-12-language'],
    },

    {
      id: 'q8',
      question: 'What is the function of madness in Macbeth versus King Lear?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Lady Macbeth\'s madness brings guilt; Lear\'s madness brings terrible philosophical insight',
        'Both plays feature identical portrayals of madness',
        'Neither play features madness',
        'Madness brings only confusion in both plays',
      ],
      correctAnswer: 'Lady Macbeth\'s madness brings guilt; Lear\'s madness brings terrible philosophical insight',
      explanation: 'Lady Macbeth goes mad from overwhelming guilt. Lear\'s madness strips away illusions, revealing savage truths about justice, power, and human nature.',
      relatedLearningPoints: ['lp-macbeth-10-madness', 'lp-lear-9-madness-insight'],
    },

    {
      id: 'q9',
      question: 'How do parallel plots function in King Lear (Lear/Gloucester)?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'They contradict each other thematically',
        'They reinforce the themes of misjudging children and sight/blindness',
        'They are unrelated stories',
        'Only Lear\'s story matters; Gloucester\'s is filler',
      ],
      correctAnswer: 'They reinforce the themes of misjudging children and sight/blindness',
      explanation: 'Both fathers misjudge their children. Both are "blind" to truth and only "see" after terrible cost (Gloucester literally, Lear metaphorically).',
      relatedLearningPoints: ['lp-lear-5-parallel', 'lp-lear-11-literal-blind'],
    },

    {
      id: 'q10',
      question: 'What historical context influenced Macbeth\'s creation?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'The French Revolution',
        'King James I\'s obsession with witchcraft and the recent Gunpowder Plot (1605)',
        'The American Civil War',
        'The Protestant Reformation alone',
      ],
      correctAnswer: 'King James I\'s obsession with witchcraft and the recent Gunpowder Plot (1605)',
      explanation: 'Shakespeare wrote Macbeth for James I, who wrote about witchcraft and had just survived an assassination attempt. The play\'s themes resonated with royal anxieties.',
      relatedLearningPoints: ['lp-macbeth-2-patronage', 'lp-macbeth-2-history'],
    },

    {
      id: 'q11',
      question: 'How is Othello innovative in Renaissance drama regarding race?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'It removes all references to race',
        'It makes a Moor the noble tragic hero rather than the villain',
        'It portrays all races identically',
        'It was the first play to mention race',
      ],
      correctAnswer: 'It makes a Moor the noble tragic hero rather than the villain',
      explanation: 'Previous Moorish characters were villains. Shakespeare reverses this: the Moor is eloquent and noble, while the white Venetian Iago is the true villain.',
      relatedLearningPoints: ['lp-othello-4-innovation', 'lp-othello-3-race'],
    },

    {
      id: 'q12',
      question: 'What does Renaissance political theory say about Lear\'s abdication?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'It was a wise retirement plan',
        'It violated divine order by separating the king\'s natural and political bodies',
        'It had no theoretical significance',
        'It was required by law',
      ],
      correctAnswer: 'It violated divine order by separating the king\'s natural and political bodies',
      explanation: 'Renaissance theory held the king\'s authority was divinely ordained and inseparable from his person. Lear\'s abdication was seen as cosmically catastrophic.',
      relatedLearningPoints: ['lp-lear-2-divine-right', 'lp-lear-2-pre-christian'],
    },

    {
      id: 'q13',
      question: 'Compare the tragic endings: which offers the least redemption or restoration?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Macbeth - order is restored with Malcolm as king',
        'Othello - the truth is revealed and Iago punished',
        'King Lear - senseless deaths offer no meaning or restoration',
        'All three offer equal amounts of redemption',
      ],
      correctAnswer: 'King Lear - senseless deaths offer no meaning or restoration',
      explanation: 'Macbeth restores order (Malcolm). Othello reveals truth (Iago punished). Lear offers only bleakness—good and evil die alike, no justice, no meaning.',
      relatedLearningPoints: ['lp-lear-16-bleakness', 'lp-lear-17-nihilism'],
    },

    {
      id: 'q14',
      question: 'What symbolic significance does blood have in Macbeth?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Only literal bloodshed from battle',
        'Guilt that cannot be cleansed and violence breeding more violence',
        'Royal lineage and succession',
        'Medical health and illness',
      ],
      correctAnswer: 'Guilt that cannot be cleansed and violence breeding more violence',
      explanation: '"Will all great Neptune\'s ocean wash this blood clean?" Blood represents inescapable guilt and the cycle where violence demands more violence.',
      relatedLearningPoints: ['lp-macbeth-6-blood', 'lp-macbeth-8-paranoia'],
    },

    {
      id: 'q15',
      question: 'What makes Iago\'s evil particularly disturbing?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'He has clear, proportionate motivations',
        'He provides multiple motives but none adequately explain his malice ("motiveless malignity")',
        'He is purely a victim of circumstances',
        'He doesn\'t actually do anything evil',
      ],
      correctAnswer: 'He provides multiple motives but none adequately explain his malice ("motiveless malignity")',
      explanation: 'Iago mentions resentment, suspicion, and racism, but critics call his evil "motiveless malignity" because no motive justifies his elaborate cruelty.',
      relatedLearningPoints: ['lp-othello-3-iago-motive', 'lp-othello-11-motiveless'],
    },

    {
      id: 'q16',
      question: 'How does the handkerchief function in Othello?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Only as a minor plot device',
        'As symbol of love transformed into false "proof" of betrayal',
        'As a magical object with supernatural powers',
        'As evidence that Desdemona is actually guilty',
      ],
      correctAnswer: 'As symbol of love transformed into false "proof" of betrayal',
      explanation: 'The handkerchief—symbol of Othello\'s love—becomes manufactured evidence of adultery. Iago transforms love\'s symbol into proof of hate.',
      relatedLearningPoints: ['lp-othello-8-symbol', 'lp-othello-8-evidence'],
    },

    {
      id: 'q17',
      question: 'What philosophical insight does Lear gain through madness?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'That kings are divinely appointed',
        'That justice is arbitrary, authority is power, and "unaccommodated man" is just an animal',
        'That everything will work out happily',
        'That madness prevents all understanding',
      ],
      correctAnswer: 'That justice is arbitrary, authority is power, and "unaccommodated man" is just an animal',
      explanation: 'Lear\'s mad speeches savage social hypocrisy, reveal justice as arbitrary power, and strip humans down to "poor, bare, forked animals."',
      relatedLearningPoints: ['lp-lear-13-mad-philosophy', 'lp-lear-13-nihilism'],
    },

    {
      id: 'q18',
      question: 'Why is Cordelia\'s death particularly unbearable in King Lear?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'She deserved punishment',
        'It provides poetic justice',
        'She is purely innocent and good, yet dies senselessly without purpose',
        'It allows the kingdom to prosper',
      ],
      correctAnswer: 'She is purely innocent and good, yet dies senselessly without purpose',
      explanation: 'Cordelia\'s death serves no purpose—she is the play\'s embodiment of goodness and truth, yet dies anyway. This senseless death epitomizes Lear\'s nihilism.',
      relatedLearningPoints: ['lp-lear-16-cordelia', 'lp-lear-16-bleakness'],
    },

    {
      id: 'q19',
      question: 'How does Part II connect to the overall Shakespeare trilogy?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'Part I (comedies) → Part II (internal corruption) → Part III (external betrayal and possible restoration)',
        'All three parts are identical in theme',
        'The parts have no connection to each other',
        'Part II is the lightest and most hopeful',
      ],
      correctAnswer: 'Part I (comedies) → Part II (internal corruption) → Part III (external betrayal and possible restoration)',
      explanation: 'The trilogy moves from light (Part I) through darkness (Part II\'s internal corruptions) toward potential restoration (Part III\'s reconciliation).',
      relatedLearningPoints: ['lp-lear-18-trilogy', 'lp-lear-18-to-part3'],
    },

    {
      id: 'q20',
      question: 'What is the ultimate lesson of Part II about human nature and tragedy?',
      type: 'multiple-choice',
      points: 5,
      options: [
        'External enemies are the greatest threat',
        'The greatest tragedies come from internal psychological forces destroying us from within',
        'Tragedy is purely a matter of bad luck',
        'Human nature is fundamentally good and always triumphs',
      ],
      correctAnswer: 'The greatest tragedies come from internal psychological forces destroying us from within',
      explanation: 'Macbeth, Othello, and Lear show that ambition, jealousy, and pride—internal forces—are more destructive than any external enemy. We are our own worst enemies.',
      relatedLearningPoints: ['lp-lear-18-part2-synthesis', 'lp-macbeth-16-synthesis'],
    },
  ],
};
