import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-chapter-4',
  title: 'Chapter 4 Quiz: Much Ado About Nothing',
  description: 'Test your knowledge of wit, deception, and true love in Shakespeare\'s comedy.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    // Multiple Choice - Plot and Character (8 questions)
    {
      id: 'q1-two-plots',
      question: 'What are the two parallel love stories in Much Ado About Nothing?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romeo and Juliet; Hamlet and Ophelia',
        'Claudio and Hero; Beatrice and Benedick',
        'Don Pedro and Hero; Don John and Beatrice',
        'Leonato and his late wife; Claudio and Beatrice',
      ],
      correctAnswer: 'Claudio and Hero; Beatrice and Benedick',
      explanation: 'The play features two distinct love plots: the conventional romance of young Claudio and modest Hero, and the witty battle-turned-love between sharp-tongued Beatrice and cynical Benedick. The contrast between these pairs explores different types of love.',
      relatedLearningPoints: ['lp-much-ado-1-two-plots', 'lp-much-ado-3-contrast'],
    },
    {
      id: 'q2-merry-war',
      question: 'What does Beatrice mean when she describes a "merry war" with Benedick?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They fought together in an actual military war',
        'They engage in witty verbal sparring whenever they meet',
        'They are bitter enemies consumed by mutual hatred',
        'They compete to see who can marry first',
      ],
      correctAnswer: 'They engage in witty verbal sparring whenever they meet',
      explanation: 'The "merry war" refers to their ongoing battle of wits—their conversations are combat, but enjoyable combat. The phrase captures the paradox of their relationship: conflict that\'s also pleasure, antagonism that\'s also attraction.',
      relatedLearningPoints: ['lp-much-ado-2-merry-war', 'lp-much-ado-2-wit'],
    },
    {
      id: 'q3-gulling',
      question: 'How do Don Pedro and the others trick Beatrice and Benedick into admitting their love?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They force them to spend extended time alone together',
        'They stage conversations for each to overhear about secret love',
        'They reveal love letters that were never sent',
        'They threaten to exile them unless they marry',
      ],
      correctAnswer: 'They stage conversations for each to overhear about secret love',
      explanation: 'The "gulling" scenes involve elaborate eavesdropping: Benedick hears that Beatrice loves him, then Beatrice hears that Benedick loves her. Both are tricked, but the trick only works because the feelings are already there, hidden by pride.',
      relatedLearningPoints: ['lp-much-ado-5a-playful', 'lp-much-ado-6-transformation', 'lp-much-ado-7-parallel'],
    },
    {
      id: 'q4-benedick-justification',
      question: 'After being tricked, how does Benedick justify his sudden willingness to marry?',
      type: 'multiple-choice',
      points: 10,
      options: [
        '"Love conquers all obstacles and challenges"',
        '"The world must be peopled"',
        '"A man is nothing without his wife"',
        '"Marriage brings wealth and social status"',
      ],
      correctAnswer: '"The world must be peopled"',
      explanation: 'Benedick\'s hilariously pragmatic justification—"the world must be peopled"—shows him rationalizing his complete reversal. Minutes earlier he swore never to marry; now he needs any reason, however absurd, to change his mind without admitting he was wrong.',
      relatedLearningPoints: ['lp-much-ado-6-transformation', 'lp-much-ado-6-self-justification'],
    },
    {
      id: 'q5-don-john-motive',
      question: 'What is Don John\'s primary motivation for slandering Hero?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is in love with Hero and wants to prevent the marriage',
        'He seeks revenge for being treated poorly as a bastard son',
        'He is a melancholy villain who delights in causing misery',
        'He was paid by a rival to ruin the wedding ceremony',
      ],
      correctAnswer: 'He is a melancholy villain who delights in causing misery',
      explanation: 'Don John is a villain by nature—Shakespeare gives him no complex motivation beyond being "a plain-dealing villain." He says himself: "Only to despite them I will endeavor anything." He is an early sketch of motiveless malignity, foreshadowing Iago.',
      relatedLearningPoints: ['lp-much-ado-9-don-john', 'lp-much-ado-9-foreshadowing'],
    },
    {
      id: 'q6-deception-contrast',
      question: 'How does the play distinguish between Don Pedro\'s playful deception and Don John\'s malicious deception?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Don Pedro uses magic while Don John uses conventional lies',
        'Don Pedro\'s tricks lead to happiness; Don John\'s cause harm',
        'Don Pedro deceives men while Don John deceives women',
        'There is no distinction—all deception is equally wrong',
      ],
      correctAnswer: 'Don Pedro\'s tricks lead to happiness; Don John\'s cause harm',
      explanation: 'The play explores the ethics of deception by contrasting benevolent tricks (gulling Beatrice and Benedick into love) with malicious ones (slandering Hero). The same method—staged deception—produces opposite results depending on intent and consequence.',
      relatedLearningPoints: ['lp-much-ado-5a-playful', 'lp-much-ado-9-contrast', 'lp-much-ado-12-deception-types'],
    },
    {
      id: 'q7-beatrice-demand',
      question: 'What does Beatrice demand that Benedick do to prove his love for her?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Marry her immediately in a secret ceremony',
        'Kill Claudio for slandering Hero',
        'Convince Don Pedro that Hero is innocent',
        'Renounce his friendship with all the soldiers',
      ],
      correctAnswer: 'Kill Claudio for slandering Hero',
      explanation: 'Beatrice\'s shocking demand—"Kill Claudio!"—tests whether Benedick\'s love is sincere. She is furious at her powerlessness as a woman to defend Hero herself: "O that I were a man!" If Benedick won\'t act, his pretty words of love mean nothing.',
      relatedLearningPoints: ['lp-much-ado-11-gender', 'lp-much-ado-11-test'],
    },
    {
      id: 'q8-dogberry',
      question: 'What is ironic about Dogberry and the Watch saving the day?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They are comic fools, yet uncover what clever nobles missed',
        'They intentionally set out to trap Don John from the beginning',
        'They are secretly working for Don Pedro all along',
        'They are more educated than all the other characters',
      ],
      correctAnswer: 'They are comic fools, yet uncover what clever nobles missed',
      explanation: 'Dogberry mangles language with malapropisms and takes himself too seriously, yet he and his bumbling Watch accidentally overhear Borachio\'s confession. Shakespeare often uses "low" characters to solve problems the educated nobles create—wisdom comes from unexpected places.',
      relatedLearningPoints: ['lp-much-ado-13-comic-justice', 'lp-much-ado-13-language'],
    },

    // True/False - Cultural and Thematic (2 questions)
    {
      id: 'q9-honor-culture',
      question: 'In Renaissance society, a woman\'s reputation and honor were so fragile that a mere public accusation could destroy them irreparably.',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'True. Renaissance honor culture placed impossible standards on women\'s chastity. Claudio doesn\'t need proof—the public accusation alone ruins Hero. Her reputation, once destroyed, could never be fully recovered. This theme appears even more darkly in Othello.',
      relatedLearningPoints: ['lp-much-ado-9-honor-culture', 'lp-much-ado-10-public-shame'],
    },
    {
      id: 'q10-pride-barrier',
      question: 'The primary barrier preventing Beatrice and Benedick from admitting their love is that they genuinely despise each other.',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'False. Their barrier is pride and fear of ridicule, not genuine dislike. Both have built public personas as marriage-scorners, and admitting love would mean vulnerability and potential mockery. The gulling trick works because the feelings are already there—it just removes the barrier of pride.',
      relatedLearningPoints: ['lp-much-ado-7-pride', 'lp-much-ado-14-themes'],
    },

    // Matching - Deceptions and Consequences (1 question)
    {
      id: 'q11-deception-matching',
      question: 'Match each deception with its consequence:',
      type: 'matching',
      points: 15,
      correctAnswer: {
        'Don Pedro stages a conversation where Benedick overhears praise of Beatrice': 'Benedick admits his love and abandons his bachelor stance',
        'Hero and Ursula discuss Benedick\'s supposed love for Beatrice': 'Beatrice vows to requite Benedick\'s love',
        'Don John stages a false scene of Hero\'s infidelity': 'Claudio publicly shames Hero at the wedding',
        'The Watch overhears Borachio confessing Don John\'s plot': 'Hero\'s innocence is revealed and her honor restored',
      },
      explanation: 'These pairings show the spectrum of deceptions in the play: playful tricks that lead to genuine happiness, malicious deception that nearly causes tragedy, and accidental revelation of truth through comic incompetence.',
      relatedLearningPoints: ['lp-much-ado-5a-playful', 'lp-much-ado-12-deception-types'],
    },

    // Multiple Choice - Continued (2 more)
    {
      id: 'q12-two-couples',
      question: 'Why is Beatrice and Benedick\'s marriage considered more satisfying than Claudio and Hero\'s?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because they are wealthier and have more social power',
        'Because their love is based on intellectual equality and wit',
        'Because they have a longer courtship period together',
        'Because they are older and more experienced in romance',
      ],
      correctAnswer: 'Because their love is based on intellectual equality and wit',
      explanation: 'Claudio and Hero follow a conventional path based on appearance and social standing—he barely knows her. Beatrice and Benedick, by contrast, are intellectual equals whose witty combat reveals genuine understanding. Their love is earned, not assumed.',
      relatedLearningPoints: ['lp-much-ado-3-contrast', 'lp-much-ado-14-earned-love'],
    },
    {
      id: 'q13-hero-blush',
      question: 'In the accusation scene, how does Claudio twist Hero\'s innocent blush into evidence against her?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He ignores her blush completely and focuses elsewhere',
        'He argues her blush proves guilt, not modest innocence',
        'He claims her blush is a sign of serious illness',
        'He says her blush shows she is too young to marry',
      ],
      correctAnswer: 'He argues her blush proves guilt, not modest innocence',
      explanation: 'Claudio reinterprets Hero\'s modest blush—traditionally a sign of maiden innocence—as proof of guilt: "Her blush is guiltiness, not modesty." Once suspicion is planted, accusers can twist any evidence to fit their narrative. This demonstrates the danger of prejudgment.',
      relatedLearningPoints: ['lp-much-ado-10-public-shame'],
    },
    {
      id: 'q14-comedy-ending',
      question: 'How does Much Ado About Nothing fulfill the conventions of Shakespearean comedy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It ends with all the villains being executed publicly',
        'It ends with multiple marriages and social harmony restored',
        'It ends with the hero going on a dangerous quest',
        'It ends with tragedy and death for the main characters',
      ],
      correctAnswer: 'It ends with multiple marriages and social harmony restored',
      explanation: 'Shakespearean comedies typically end with marriage—society is restored, conflicts are resolved, and harmony returns. Much Ado gives us a double wedding, Hero\'s honor restored, Don John captured, and even the stubborn Beatrice and Benedick united. Order is fully restored.',
      relatedLearningPoints: ['lp-much-ado-14-comedy-resolution'],
    },
    {
      id: 'q15-othello-connection',
      question: 'How does the false accusation of Hero foreshadow Shakespeare\'s later tragedy Othello?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Both plays are set in Italy with similar cultural contexts',
        'Both involve men shaming innocent women based on false infidelity',
        'Both villains are named Don John and serve similar roles',
        'Both end with the women being saved by their friends',
      ],
      correctAnswer: 'Both involve men shaming innocent women based on false infidelity',
      explanation: 'Hero\'s false accusation prefigures Desdemona\'s in Othello (Part II). The crucial difference: Much Ado is a comedy where truth emerges in time to save Hero. In Othello, the same dynamic becomes tragedy when truth arrives too late and Desdemona dies. Don John is a sketch for the more developed villain Iago.',
      relatedLearningPoints: ['lp-much-ado-9-foreshadowing'],
    },
  ],
};
