import type { Quiz } from '../../../types';

export const chapter2Quiz: Quiz = {
  id: 'quiz-chapter-2',
  title: 'Chapter 2: Romeo and Juliet Quiz',
  description: 'Test your knowledge of Shakespeare\'s timeless romantic tragedy.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'What is the main cause of the tragedy in Romeo and Juliet?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romeo\'s impulsive and reckless personality',
        'The ancient Montague and Capulet family feud',
        'Friar Laurence\'s misguided intervention',
        'Juliet\'s youth and lack of life experience',
      ],
      correctAnswer: 'The ancient Montague and Capulet family feud',
      explanation: 'While individual choices contribute to the tragedy, the fundamental cause is the family feud that forces the lovers to keep their marriage secret and prevents them from seeking help openly.',
      relatedLearningPoints: ['lp-romeo-1-feud', 'lp-romeo-12-sacrifice'],
    },
    {
      id: 'q2',
      question: 'What literary device does Shakespeare use by revealing the lovers\' fate in the prologue?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Foreshadowing',
        'Dramatic irony',
        'Metaphor',
        'Allegory',
      ],
      correctAnswer: 'Dramatic irony',
      explanation: 'By telling us in the prologue that the "star-crossed lovers" will die, Shakespeare creates dramatic irony—we know their fate while they don\'t, making their hope and joy poignant and tragic.',
      relatedLearningPoints: ['lp-romeo-1-prologue', 'lp-romeo-3-dramatic-irony'],
    },
    {
      id: 'q3',
      question: 'How do Romeo and Juliet\'s first words to each other form a literary structure?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They speak in perfectly matched rhyming couplets',
        'They co-create a 14-line sonnet together',
        'They speak entirely in blank verse',
        'They use strict iambic pentameter exclusively',
      ],
      correctAnswer: 'They co-create a 14-line sonnet together',
      explanation: 'When Romeo and Juliet first speak, they create a perfect sonnet between them, each speaking alternate lines. This poetic structure suggests they are perfectly matched souls who complete each other.',
      relatedLearningPoints: ['lp-romeo-3-love-at-first-sight'],
    },
    {
      id: 'q4',
      question: 'What does Juliet mean when she says "What\'s in a name? That which we call a rose / By any other name would smell as sweet"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She is discussing her favorite garden flowers',
        'Names don\'t change what something truly is',
        'Romeo should abandon his family name immediately',
        'She prefers the natural world over people',
      ],
      correctAnswer: 'Names don\'t change what something truly is',
      explanation: 'Juliet argues that the name "Montague" is just a word—Romeo would still be the same person she loves even if he had a different name. She\'s questioning whether social labels should determine who we can love.',
      relatedLearningPoints: ['lp-romeo-4-language'],
    },
    {
      id: 'q5',
      question: 'Why does Friar Laurence agree to marry Romeo and Juliet in secret?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He wants financial gain from the wedding ceremony',
        'He hopes their union will end the family feud',
        'He fears Romeo will become violent if refused',
        'He enjoys defying both families\' authority',
      ],
      correctAnswer: 'He hopes their union will end the family feud',
      explanation: 'The Friar is well-intentioned, believing that if the families learn their children are married, they might end their hatred. He says "this alliance may so happy prove to turn your households\' rancour to pure love."',
      relatedLearningPoints: ['lp-romeo-6-friar'],
    },
    {
      id: 'q6',
      question: 'What does Mercutio mean by his dying curse "A plague on both your houses"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He literally wishes for disease to strike the families',
        'He blames both families for the feud that killed him',
        'He is delirious and speaking without sense or reason',
        'He is only cursing the Capulet family',
      ],
      correctAnswer: 'He blames both families for the feud that killed him',
      explanation: 'Mercutio, who belongs to neither family, curses both houses for their stupid feud that led to his death. His curse proves prophetic—the feud will indeed destroy children of both families.',
      relatedLearningPoints: ['lp-romeo-8-plague'],
    },
    {
      id: 'q7',
      question: 'What is the turning point that transforms Romeo and Juliet from a romantic comedy into a tragedy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romeo and Juliet falling in love at the party',
        'The secret marriage performed by Friar Laurence',
        'Mercutio\'s death and Romeo killing Tybalt',
        'Juliet taking the potion to fake her death',
      ],
      correctAnswer: 'Mercutio\'s death and Romeo killing Tybalt',
      explanation: 'This is the pivot point. Until Mercutio dies, the play has the structure of a comedy—young lovers overcoming obstacles. But once Romeo kills Tybalt, he\'s banished and tragedy becomes inevitable.',
      relatedLearningPoints: ['lp-romeo-8-turning-point'],
    },
    {
      id: 'q8',
      question: 'Why does Friar Laurence\'s plan with the sleeping potion fail?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Juliet wakes up too early from the potion',
        'The potion doesn\'t work the way it should',
        'The letter never reaches Romeo due to plague quarantine',
        'Romeo refuses to come to the Capulet tomb',
      ],
      correctAnswer: 'The letter never reaches Romeo due to plague quarantine',
      explanation: 'Friar John, who was supposed to deliver the crucial letter to Romeo, gets quarantined due to plague. Romeo never learns that Juliet\'s death is faked, so he believes she\'s truly dead and kills himself.',
      relatedLearningPoints: ['lp-romeo-10-communication'],
    },
    {
      id: 'q9',
      question: 'What does Romeo mean when he cries "O, I am fortune\'s fool!" after killing Tybalt?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is mocking fortune and fate sarcastically',
        'He sees himself as fate\'s plaything or puppet',
        'He is calling himself foolish for trusting luck',
        'He believes fortune still favors him somehow',
      ],
      correctAnswer: 'He sees himself as fate\'s plaything or puppet',
      explanation: 'Romeo realizes that despite his best intentions (trying to keep peace), he has been manipulated by fate into violence and tragedy. He\'s expressing the play\'s central theme of fate versus free will.',
      relatedLearningPoints: ['lp-romeo-8-fortune'],
    },
    {
      id: 'q10',
      question: 'How does Shakespeare use light and dark imagery throughout Romeo and Juliet?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Light represents Montagues while dark symbolizes Capulets',
        'Juliet is compared to light (sun, stars) and darkness represents obstacles',
        'Light represents tragedy while darkness represents hope',
        'The imagery carries no particular symbolic meaning',
      ],
      correctAnswer: 'Juliet is compared to light (sun, stars) and darkness represents obstacles',
      explanation: 'Romeo calls Juliet "the sun" and says she teaches "the torches to burn bright." Light imagery represents love and hope, while darkness represents the secrecy, violence, and death that surround them.',
      relatedLearningPoints: ['lp-romeo-4-imagery'],
    },
    {
      id: 'q11',
      question: 'Romeo and Juliet\'s love is described as "star-crossed." The lovers are doomed by fate alone.',
      type: 'true-false',
      points: 10,
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'False. While fate plays a role (the undelivered letter, the timing), the tragedy also results from human choices—the family feud, Romeo\'s impulsive violence, the Friar\'s overly complex plan. Shakespeare explores how fate and free will intertwine.',
      relatedLearningPoints: ['lp-romeo-9-fate-choice'],
    },
    {
      id: 'q12',
      question: 'What is the ultimate result of Romeo and Juliet\'s deaths?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The families continue their fighting in revenge',
        'The Montagues are permanently banished from Verona',
        'The families finally reconcile and end their feud',
        'The Prince executes both families\' patriarchs',
      ],
      correctAnswer: 'The families finally reconcile and end their feud',
      explanation: 'Only after seeing their dead children do the Montagues and Capulets finally make peace, clasping hands over the bodies. The lovers become "poor sacrifices of our enmity," their deaths teaching what reason could not.',
      relatedLearningPoints: ['lp-romeo-12-reconciliation', 'lp-romeo-12-sacrifice'],
    },
    {
      id: 'q13',
      question: 'How does Romeo and Juliet\'s impulsive young love differ from the mature love we\'ll explore in Twelfth Night?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romeo and Juliet shows instant passion while Twelfth Night shows patient love',
        'Romeo and Juliet depicts false love while Twelfth Night shows true love',
        'There is no difference between how the plays portray love',
        'Romeo and Juliet shows mature love while Twelfth Night shows immature love',
      ],
      correctAnswer: 'Romeo and Juliet shows instant passion while Twelfth Night shows patient love',
      explanation: 'This contrast is intentional—Romeo and Juliet marry within days of meeting, while Twelfth Night (coming next) will show love that requires self-knowledge and patience. Both are valid but different explorations of love.',
      relatedLearningPoints: ['lp-romeo-5-marriage'],
    },
    {
      id: 'q14',
      question: 'The play suggests that Romeo and Juliet\'s love could have succeeded if only...',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They had been older and more mature',
        'The feud hadn\'t existed or they had been less secretive',
        'Friar Laurence had refused to assist them',
        'They had never met at the Capulet ball',
      ],
      correctAnswer: 'The feud hadn\'t existed or they had been less secretive',
      explanation: 'The tragedy emerges from the forced secrecy. If there had been no feud, or if they\'d revealed their marriage earlier, the chain of misunderstandings might have been prevented. The play shows how social hatred destroys individual love.',
      relatedLearningPoints: ['lp-romeo-9-causation'],
    },
    {
      id: 'q15',
      question: 'What makes the timing of the final tragedy especially heartbreaking?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Romeo arrives at the tomb many days after Juliet dies',
        'Romeo dies moments before Juliet wakes from her sleep',
        'Juliet wakes immediately and saves Romeo from poison',
        'Both lovers survive but remain separated forever',
      ],
      correctAnswer: 'Romeo dies moments before Juliet wakes from her sleep',
      explanation: 'The devastating timing—Romeo dies just before Juliet wakes—suggests they were always meant to miss each other, separated by minutes in a cosmic near-miss. If Romeo had waited even briefly, they might have lived.',
      relatedLearningPoints: ['lp-romeo-11-timing', 'lp-romeo-9-timing'],
    },
  ],
};
