import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'quiz-chapter-1',
  title: 'Chapter 1: Prologue Quiz',
  description: 'Test your knowledge of Shakespeare\'s life, the Globe Theatre, and Elizabethan England.',
  passingScore: 70,
  allowRetry: true,
  questions: [
    {
      id: 'q1',
      question: 'When and where was William Shakespeare born?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'London in 1558, during Queen Mary\'s reign',
        'Stratford-upon-Avon, 1564',
        'Oxford in 1570, near the university',
        'Canterbury in 1560, in Kent',
      ],
      correctAnswer: 'Stratford-upon-Avon, 1564',
      explanation: 'Shakespeare was born in Stratford-upon-Avon in 1564, the son of a glove-maker and wool dealer. He was baptized on April 26th, though his exact birthdate is unknown (traditionally celebrated on April 23rd).',
      relatedLearningPoints: ['lp-5-shakespeare-biography'],
    },
    {
      id: 'q2',
      question: 'What made Shakespeare unusual compared to other playwrights of his time?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was the only playwright educated at Oxford University',
        'He was both a writer and a shareholder in his company',
        'He was the first playwright to write exclusively in English',
        'He only wrote tragedies and never attempted comedy',
      ],
      correctAnswer: 'He was both a writer and a shareholder in his company',
      explanation: 'Shakespeare was unusual in being both a playwright and a shareholder in the Lord Chamberlain\'s Men (later the King\'s Men). This gave him both creative control and financial rewards from the company\'s success, allowing him greater artistic freedom than most playwrights.',
      relatedLearningPoints: ['lp-6-shareholder-model'],
    },
    {
      id: 'q3',
      question: 'The Globe Theatre opened in 1599. Where was it located and why?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Inside the City of London, protected by royal charter',
        'In Bankside, outside the city\'s Puritan jurisdiction',
        'In Oxford, near the university for educated audiences',
        'In Stratford, Shakespeare\'s hometown for local support',
      ],
      correctAnswer: 'In Bankside, outside the city\'s Puritan jurisdiction',
      explanation: 'The Globe was built in Bankside, on the south bank of the Thames, deliberately outside the City of London\'s jurisdiction. This allowed theaters to operate more freely, away from Puritan city officials who viewed plays as immoral.',
      relatedLearningPoints: ['lp-1-globe-opening', 'lp-3-london-geography'],
    },
    {
      id: 'q4',
      question: 'What were "groundlings" at the Globe Theatre?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Actors who performed on the ground-level stage',
        'Audience members who stood in the yard for a penny',
        'Workers who maintained the theater building structure',
        'Musicians who played instruments during scene changes',
      ],
      correctAnswer: 'Audience members who stood in the yard for a penny',
      explanation: 'Groundlings were audience members who paid just one penny (the cheapest admission) to stand in the open-air yard surrounding the stage. They often ate, drank, and were rowdy during performances, representing the common people who made up a large part of Shakespeare\'s audience.',
      relatedLearningPoints: ['lp-9-globe-structure', 'lp-4-cross-class-audience'],
    },
    {
      id: 'q5',
      question: 'Why is the First Folio (1623) so important?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It was the first book ever printed in the English language',
        'It proved Shakespeare wrote all plays attributed to him',
        'It preserved half of Shakespeare\'s plays, never printed before',
        'It contained Shakespeare\'s complete autobiography and letters',
      ],
      correctAnswer: 'It preserved half of Shakespeare\'s plays, never printed before',
      explanation: 'The First Folio, published seven years after Shakespeare\'s death by his fellow actors John Heminges and Henry Condell, preserved 36 of his plays. About half of these had never been printed before, including masterpieces like Macbeth, Twelfth Night, and Julius Caesar. Without the First Folio, these works might have been lost forever.',
      relatedLearningPoints: ['lp-7-first-folio-importance', 'lp-8-plays-as-literature'],
    },
    {
      id: 'q6',
      question: 'What is iambic pentameter?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A type of theatrical stage with five performance levels',
        'A rhythmic pattern of five unstressed-stressed syllable pairs',
        'A musical instrument commonly used in Globe performances',
        'A theater company structure with exactly five key members',
      ],
      correctAnswer: 'A rhythmic pattern of five unstressed-stressed syllable pairs',
      explanation: 'Iambic pentameter is the rhythmic pattern Shakespeare used for most of his verse. An iamb is an unstressed syllable followed by a stressed syllable (da-DUM), and pentameter means five iambs per line. This creates a rhythm that sounds natural in English while elevating everyday speech to poetry.',
      relatedLearningPoints: ['lp-16-iambic-pentameter', 'lp-17-verse-prose'],
    },
    {
      id: 'q7',
      question: 'What was the "Great Chain of Being" in Elizabethan society?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A series of popular taverns along the Thames River',
        'A divine hierarchy from God through kings to all creatures',
        'The chain used to secure the Globe Theatre at night',
        'A ceremonial necklace worn by Queen Elizabeth I',
      ],
      correctAnswer: 'A divine hierarchy from God through kings to all creatures',
      explanation: 'The Great Chain of Being was the Elizabethan worldview: a divinely ordered hierarchy with God at the top, then angels, monarchs, nobility, commoners, animals, plants, and minerals. Disrupting this order—like killing a king—was believed to cause chaos in nature itself. This concept underlies many of Shakespeare\'s tragedies, particularly those we\'ll explore in Part II.',
      relatedLearningPoints: ['lp-19-social-hierarchy', 'lp-21-cross-reference-context'],
    },
    {
      id: 'q8',
      question: 'Who was Richard Burbage?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The chief architect who designed the Globe Theatre',
        'Shakespeare\'s brother who helped manage the theater',
        'The lead actor who originated Romeo, Hamlet, Othello',
        'The publisher responsible for the First Folio edition',
      ],
      correctAnswer: 'The lead actor who originated Romeo, Hamlet, Othello',
      explanation: 'Richard Burbage was the lead actor of the Lord Chamberlain\'s Men and Shakespeare\'s longtime collaborator. He originated many of Shakespeare\'s greatest roles, from Romeo to Hamlet to King Lear. Shakespeare wrote with Burbage\'s voice and talents in mind, creating a unique artistic partnership.',
      relatedLearningPoints: ['lp-12-collaborative-writing', 'lp-15-actor-collaboration'],
    },
    {
      id: 'q9',
      question: 'What were the three main types of plays Shakespeare wrote?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Sonnets, musicals, and operas',
        'Comedies, tragedies, and histories',
        'Farces, melodramas, and satires',
        'Morality plays, mystery plays, and miracle plays',
      ],
      correctAnswer: 'Comedies, tragedies, and histories',
      explanation: 'Shakespeare wrote three main types of plays: comedies (ending in marriage and celebration), tragedies (ending in death and destruction), and histories (dramatizing the reigns of English kings). Each genre explores different aspects of human experience using distinct structures and tones.',
      relatedLearningPoints: ['lp-24-three-genres', 'lp-25-comedy-structure', 'lp-26-tragedy-structure'],
    },
    {
      id: 'q10',
      question: 'Why did Shakespeare set many of his plays in Italy, Denmark, or ancient Rome rather than England?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He had traveled extensively in those foreign countries',
        'English audiences strongly preferred exotic foreign settings',
        'It allowed him to explore dangerous political themes safely',
        'He couldn\'t get royal permission to write about England',
      ],
      correctAnswer: 'It allowed him to explore dangerous political themes safely',
      explanation: 'Shakespeare navigated religious and political tensions by setting plays in foreign lands. This allowed him to explore dangerous themes like rebellion, murder of kings, and political corruption without directly commenting on English politics. The foreign settings provided a safe distance while still allowing audiences to see parallels to their own world.',
      relatedLearningPoints: ['lp-20-religious-politics'],
    },
    {
      id: 'q11',
      question: 'The Globe Theatre\'s structure included "heaven," "earth," and "hell." What did this represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Three different seating price levels for audiences',
        'The cosmic order—theater as microcosm of the universe',
        'Three different types of plays performed at the Globe',
        'The three levels of Elizabethan social hierarchy',
      ],
      correctAnswer: 'The cosmic order—theater as microcosm of the universe',
      explanation: 'The Globe\'s design reflected the Elizabethan worldview. The painted ceiling ("the heavens") represented the cosmos, the stage was "earth," and the underside/trapdoor area was "hell." This architectural symbolism reinforced the metaphor that theater mirrors all of life and contained the entire universe on a single platform.',
      relatedLearningPoints: ['lp-10-universal-theater'],
    },
    {
      id: 'q12',
      question: 'What closing happened regularly in Elizabethan London that forced theaters to close?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Religious holidays and Puritan celebrations',
        'Royal visits and official state ceremonies',
        'Plague outbreaks when deaths exceeded limits',
        'Winter snowstorms and severe weather events',
      ],
      correctAnswer: 'Plague outbreaks when deaths exceeded limits',
      explanation: 'Bubonic plague struck London regularly throughout Shakespeare\'s career. When plague deaths exceeded 30 per week, all public gatherings were banned and theaters closed. This forced theater companies to tour the countryside or face financial ruin. The threat of plague reinforced both fatalism and the urgency to enjoy life while you could—themes present in many of Shakespeare\'s comedies.',
      relatedLearningPoints: ['lp-19-social-hierarchy'],
    },
    {
      id: 'q13',
      question: 'How did Shakespeare write roles for his actors?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He wrote generic roles any actor could perform',
        'He tailored roles to specific actors\' strengths',
        'He required actors to rewrite their own lines',
        'He only wrote roles for himself to perform',
      ],
      correctAnswer: 'He tailored roles to specific actors\' strengths',
      explanation: 'Shakespeare wrote with his company members in mind, particularly lead actor Richard Burbage. He understood each actor\'s voice, strengths, and weaknesses, creating roles that showcased their talents. As both playwright and actor, he knew what worked on stage and would revise scripts based on performance. This collaborative approach helped create some of theater\'s greatest roles.',
      relatedLearningPoints: ['lp-12-collaborative-writing', 'lp-14-character-depth'],
    },
    {
      id: 'q14',
      question: 'True or False: Shakespeare\'s plays were considered great literature during his lifetime.',
      type: 'true-false',
      points: 10,
      correctAnswer: 'false',
      explanation: 'False. During Shakespeare\'s lifetime, plays were considered popular entertainment, not "serious" literature worthy of preservation. Poetry and classical works were valued more highly. The First Folio\'s editors felt they had to justify publishing the plays, explaining they were honoring their friend, not seeking profit or fame. It was only in later centuries that Shakespeare\'s plays came to be recognized as literary masterpieces. The First Folio helped begin this transformation.',
      relatedLearningPoints: ['lp-8-plays-as-literature'],
    },
  ],
};
