import type { Quiz } from '../../../types';

export const finalQuiz: Quiz = {
  id: 'final-quiz-arabian-nights',
  title: 'Arabian Nights: Final Assessment',
  description: 'A comprehensive quiz covering all chapters of the Arabian Nights adventure, testing your understanding of the major themes, literary techniques, and cultural context.',
  passingScore: 75,
  allowRetry: true,
  questions: [
    {
      id: 'fq1',
      question: 'What literary technique is central to the structure of Arabian Nights?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Stream of consciousness',
        'Frame narrative (stories within stories)',
        'Epic poetry',
        'Epistolary narrative',
      ],
      correctAnswer: 'Frame narrative (stories within stories)',
      explanation: 'Arabian Nights uses frame narratives extensively - Scheherazade tells stories to the Sultan, and within those stories are often more nested stories (like Sinbad telling the Porter).',
      relatedLearningPoints: ['lp-ch1-6', 'lp-ch5-1', 'lp-ch5-22'],
    },
    {
      id: 'fq2',
      question: 'Why does Scheherazade tell stories to Sultan Shahryar?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To entertain him',
        'To survive and transform him from executing women',
        'To win a storytelling competition',
        'To teach him history',
      ],
      correctAnswer: 'To survive and transform him from executing women',
      explanation: 'Scheherazade uses storytelling as a survival strategy, leaving stories unfinished each dawn so the Sultan spares her to hear the ending. Through this, she gradually transforms his heart.',
      relatedLearningPoints: ['lp-ch1-1', 'lp-ch1-5'],
    },
    {
      id: 'fq3',
      question: 'What do the magical elements in Ali Baba (cave, talking door) represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Pure fantasy with no deeper meaning',
        'Tests of character and moral choices',
        'Historical technology',
        'Religious symbols',
      ],
      correctAnswer: 'Tests of character and moral choices',
      explanation: 'The magical elements serve as narrative devices that create moral tests - how characters respond to the cave\'s wealth reveals their true nature.',
      relatedLearningPoints: ['lp-ch2-4'],
    },
    {
      id: 'fq4',
      question: 'In "Ali Baba and the Forty Thieves," who is the true hero of the story?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Ali Baba',
        'Morgiana, the servant',
        'Cassim',
        'The thieves\' leader',
      ],
      correctAnswer: 'Morgiana, the servant',
      explanation: 'Morgiana saves Ali Baba\'s family multiple times through her intelligence and bravery, subverting expectations about who can be a hero based on social class.',
      relatedLearningPoints: ['lp-ch2-10', 'lp-ch2-12'],
    },
    {
      id: 'fq5',
      question: 'What is the main theme of "The Fisherman and the Jinni"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Greed leads to destruction',
        'Intelligence and wisdom triumph over brute force',
        'Magic solves all problems',
        'Revenge is justified',
      ],
      correctAnswer: 'Intelligence and wisdom triumph over brute force',
      explanation: 'The fisherman defeats the powerful jinni not through strength but through clever reasoning, showing that wisdom is more valuable than power.',
      relatedLearningPoints: ['lp-ch3-8', 'lp-ch3-11'],
    },
    {
      id: 'fq6',
      question: 'How does the fisherman trick the jinni back into the bottle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He uses magic spells',
        'He appeals to the jinni\'s vanity by expressing disbelief',
        'He makes a deal',
        'He fights the jinni',
      ],
      correctAnswer: 'He appeals to the jinni\'s vanity by expressing disbelief',
      explanation: 'The fisherman cleverly says he doesn\'t believe the jinni could fit in the bottle, appealing to the jinni\'s pride and getting him to demonstrate - then quickly seals it.',
      relatedLearningPoints: ['lp-ch3-9'],
    },
    {
      id: 'fq7',
      question: 'What is Aladdin\'s character arc in his story?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He remains a lazy street boy who gets lucky',
        'He transforms from idle youth to responsible, worthy leader',
        'He becomes corrupted by power',
        'He never changes',
      ],
      correctAnswer: 'He transforms from idle youth to responsible, worthy leader',
      explanation: 'Aladdin undergoes significant character development, learning responsibility, wisdom, and earning his position through growth rather than just magical luck.',
      relatedLearningPoints: ['lp-ch4-2', 'lp-ch4-13'],
    },
    {
      id: 'fq8',
      question: 'What does the magic lamp in Aladdin represent thematically?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Pure wish fulfillment',
        'Opportunity that requires wisdom to use properly',
        'Evil temptation',
        'Divine intervention',
      ],
      correctAnswer: 'Opportunity that requires wisdom to use properly',
      explanation: 'The lamp gives Aladdin opportunities, but his character development - learning to use power wisely and responsibly - determines whether those opportunities lead to good or bad outcomes.',
      relatedLearningPoints: ['lp-ch4-6', 'lp-ch4-12'],
    },
    {
      id: 'fq9',
      question: 'What pattern do all of Sinbad\'s voyages follow?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Departure, disaster, survival through cleverness, reward, return',
        'Peace, conflict, war, victory',
        'Discovery, exploration, conquest',
        'Trade, profit, celebration',
      ],
      correctAnswer: 'Departure, disaster, survival through cleverness, reward, return',
      explanation: 'Each of Sinbad\'s seven voyages follows this cyclical pattern, creating an episodic structure that emphasizes resourcefulness and resilience.',
      relatedLearningPoints: ['lp-ch5-6', 'lp-map-pattern'],
    },
    {
      id: 'fq10',
      question: 'What historical period and culture do Sinbad\'s stories reflect?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Ancient Egypt',
        'Islamic Golden Age maritime trade networks',
        'European Age of Exploration',
        'Ancient Greece',
      ],
      correctAnswer: 'Islamic Golden Age maritime trade networks',
      explanation: 'Sinbad\'s voyages reflect the extensive maritime trade networks during the Islamic Golden Age (8th-13th centuries), when Arab merchants dominated Indian Ocean trade.',
      relatedLearningPoints: ['lp-ch5-19', 'lp-map-geography'],
    },
    {
      id: 'fq11',
      question: 'According to Arabian Nights, what is the ultimate value of stories?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Entertainment only',
        'Historical record',
        'Tools of survival, transformation, and human connection',
        'Moral instruction',
      ],
      correctAnswer: 'Tools of survival, transformation, and human connection',
      explanation: 'Throughout Arabian Nights, stories serve as tools for survival (Scheherazade), bridges between social classes (the two Sinbads), means of transformation (the Sultan), and ways to create understanding across boundaries.',
      relatedLearningPoints: ['lp-ch5-21', 'lp-ch5-23'],
    },
    {
      id: 'fq12',
      question: 'What connects the stories of Ali Baba, the Fisherman, Aladdin, and Sinbad?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'All feature the same characters',
        'All show ordinary people facing extraordinary circumstances through wit and courage',
        'All are purely historical accounts',
        'All have tragic endings',
      ],
      correctAnswer: 'All show ordinary people facing extraordinary circumstances through wit and courage',
      explanation: 'A central theme across all these stories is that ordinary people (a woodcutter, a poor fisherman, a street boy, a merchant) can overcome extraordinary challenges through intelligence, resourcefulness, and moral character.',
      relatedLearningPoints: ['lp-ch2-1', 'lp-ch3-8', 'lp-ch4-2', 'lp-ch5-7'],
    },
  ],
};
