import type { Quiz } from '../../../types';

export const finalQuiz: Quiz = {
  id: 'final-quiz-the-iliad',
  title: 'The Iliad: Final Assessment',
  description: 'A comprehensive quiz covering all chapters of The Iliad, testing your understanding of Homer\'s epic, its themes of rage and honor, the tragedy of war, and the humanity beneath heroism.',
  passingScore: 75,
  allowRetry: true,
  questions: [
    {
      id: 'fq1',
      question: 'What is the central theme that drives the entire Iliad from the very first line?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The glory of war',
        'The rage of Achilles',
        'The fall of Troy',
        'The love of Helen',
      ],
      correctAnswer: 'The rage of Achilles',
      explanation: 'Homer begins with "Sing, goddess, the rage of Achilles" - the entire epic centers on Achilles\' wrath, first against Agamemnon, then against Hector after Patroclus\'s death.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq2',
      question: 'Why does Achilles refuse to fight after his quarrel with Agamemnon?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is wounded',
        'He is afraid of Hector',
        'Agamemnon dishonored him by taking Briseis',
        'The gods commanded him to stop',
      ],
      correctAnswer: 'Agamemnon dishonored him by taking Briseis',
      explanation: 'When Agamemnon takes Briseis, Achilles\' war prize, it\'s not just about the woman - it\'s about honor and respect. This public dishonor drives Achilles to withdraw from battle.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq3',
      question: 'What literary technique does Homer use by starting the Iliad in the tenth year of the war?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Flashback',
        'In medias res (starting in the middle)',
        'Foreshadowing',
        'Stream of consciousness',
      ],
      correctAnswer: 'In medias res (starting in the middle)',
      explanation: 'Homer throws readers directly into the conflict in year ten, assuming knowledge of how the war started. This creates immediate dramatic tension and focuses on the story\'s most intense period.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq4',
      question: 'What makes Hector a tragic hero?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is the strongest warrior',
        'He fights for a just cause and his family, knowing he is doomed',
        'He defeats Achilles',
        'He survives the war',
      ],
      correctAnswer: 'He fights for a just cause and his family, knowing he is doomed',
      explanation: 'Hector is Troy\'s defender fighting to protect his city, wife, and son. He knows the prophecies of Troy\'s fall and his own death, yet chooses duty and honor anyway - classic tragic heroism.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq5',
      question: 'Why is the farewell scene between Hector and Andromache so important?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It shows Hector preparing for battle',
        'It humanizes war by showing what warriors fight for and must leave behind',
        'It introduces their son Astyanax',
        'It proves Hector is brave',
      ],
      correctAnswer: 'It humanizes war by showing what warriors fight for and must leave behind',
      explanation: 'This scene shows Hector as a loving husband and father, not just a warrior. It reveals the human cost of war - families torn apart, the weight of duty versus love, the tragedy of what is lost.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq6',
      question: 'Why does Patroclus borrow Achilles\' armor and enter battle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To steal glory from Achilles',
        'To save the Greeks from destruction while Achilles refuses to fight',
        'Because Achilles commanded him to',
        'To challenge Hector to single combat',
      ],
      correctAnswer: 'To save the Greeks from destruction while Achilles refuses to fight',
      explanation: 'Patroclus is moved by compassion for the dying Greeks. He hopes that if the Trojans think Achilles has returned (seeing his armor), they will retreat. His motivation is mercy, not personal glory.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq7',
      question: 'What role does Apollo play in Patroclus\'s death?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Apollo warns Patroclus to retreat',
        'Apollo strikes Patroclus, making him vulnerable to Hector',
        'Apollo has no involvement',
        'Apollo protects Patroclus',
      ],
      correctAnswer: 'Apollo strikes Patroclus, making him vulnerable to Hector',
      explanation: 'Apollo intervenes directly, striking Patroclus and knocking off his armor. This divine intervention shows that fate and the gods control mortal destinies - even great warriors cannot escape what is ordained.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq8',
      question: 'How does Patroclus\'s death transform Achilles?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It makes him a coward',
        'It has no effect on him',
        'It transforms his rage from pride to grief, making him even more dangerous',
        'It makes him give up fighting',
      ],
      correctAnswer: 'It transforms his rage from pride to grief, making him even more dangerous',
      explanation: 'Achilles\' rage against Agamemnon was about honor. His rage after Patroclus\'s death comes from devastating grief and love, making him an unstoppable, terrifying force of vengeance.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq9',
      question: 'What is the significance of the Shield of Achilles?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It makes him invincible',
        'It depicts the entire cosmos - war and peace, life and death - a world he is about to leave',
        'It was stolen from Hector',
        'It contains magic powers',
      ],
      correctAnswer: 'It depicts the entire cosmos - war and peace, life and death - a world he is about to leave',
      explanation: 'The shield shows cities at peace and war, farmers and dancers, birth and death - the whole of human life. It\'s ironic: Achilles carries the world on his shield but is fated to die young, experiencing only war.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq10',
      question: 'Why does Hector choose to face Achilles despite knowing he will likely die?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He believes he can win',
        'He values honor and duty more than life',
        'He is forced to fight',
        'He wants to die',
      ],
      correctAnswer: 'He values honor and duty more than life',
      explanation: 'Hector understands he\'s outmatched and doomed, but as Troy\'s defender and a man of honor, he cannot hide. His choice to face death rather than flee defines true heroism.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq11',
      question: 'Why does Achilles desecrate Hector\'s body by dragging it behind his chariot?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To celebrate his victory',
        'Because he is consumed by grief-fueled rage that makes him inhuman',
        'To follow Greek custom',
        'To please the gods',
      ],
      correctAnswer: 'Because he is consumed by grief-fueled rage that makes him inhuman',
      explanation: 'This horrifying act shows how far Achilles has fallen into rage and grief. Desecrating a corpse violates sacred Greek beliefs - Achilles has become more force of nature than human, unable to find peace even in victory.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq12',
      question: 'What is remarkable about Priam\'s journey to Achilles\' tent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He brings an army',
        'An old king risks everything to beg his son\'s killer for his body',
        'He threatens Achilles',
        'He brings Helen as ransom',
      ],
      correctAnswer: 'An old king risks everything to beg his son\'s killer for his body',
      explanation: 'Priam, king of Troy, humbles himself before the man who killed his son. He risks capture or death to give Hector proper burial. This supreme act of courage and love breaks through Achilles\' rage.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq13',
      question: 'What finally breaks Achilles\' rage and allows him to return Hector\'s body?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The gods force him',
        'Priam reminds him of his own father, awakening shared humanity',
        'He is paid enough ransom',
        'He fears revenge',
      ],
      correctAnswer: 'Priam reminds him of his own father, awakening shared humanity',
      explanation: 'When Priam says "I have kissed the hands that killed my son," and speaks of Achilles\' own father, both men weep together. This moment of shared grief and humanity transcends the war and transforms Achilles.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq14',
      question: 'What does the Iliad ultimately say about the glory of war?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'War is glorious and makes men immortal',
        'War brings glory but at a terrible human cost - it destroys what is most precious',
        'War should be avoided at all costs',
        'War has no glory',
      ],
      correctAnswer: 'War brings glory but at a terrible human cost - it destroys what is most precious',
      explanation: 'The Iliad doesn\'t condemn or glorify war simply. It shows both: warriors achieve immortal fame (kleos), but war destroys families, kills the best men young, and brings endless grief. Glory and tragedy are inseparable.',
      relatedLearningPoints: [],
    },
    {
      id: 'fq15',
      question: 'Reflect on the entire Iliad: Which moment or character do you think best demonstrates Homer\'s central message about war, honor, and humanity? Explain your reasoning and connect it to the major themes of rage, grief, glory, and compassion.',
      type: 'self-assessment',
      points: 10,
      modelAnswer: `The moment when Achilles and Priam weep together over their shared losses best demonstrates Homer's central message about humanity transcending conflict. Despite being mortal enemies, both men recognize their common suffering—Priam grieves for Hector, Achilles for Patroclus and his own father. This scene shows that compassion and shared grief can break through even the deepest rage and hatred.

This moment reveals that Homer ultimately values human connection over military victory or glory. The Iliad doesn't end with Troy's fall or Greek triumph, but with two enemies sharing a meal and honoring each other's grief. It suggests that maintaining our humanity—our capacity for empathy, mercy, and recognizing others' pain—matters more than any battlefield achievement. War may bring eternal fame (kleos), but it's our compassion that defines our humanity.`,
      assessmentCriteria: [
        {
          id: 'crit1',
          text: 'Identified a specific moment or character from the Iliad with clear context',
          points: 3,
        },
        {
          id: 'crit2',
          text: 'Explained why this moment demonstrates Homer\'s central message about war and humanity',
          points: 4,
        },
        {
          id: 'crit3',
          text: 'Connected the analysis to major themes (rage, grief, glory, compassion, or shared humanity)',
          points: 3,
        },
      ],
      explanation: 'This holistic question asks you to synthesize everything you\'ve learned about the Iliad and reflect on its ultimate meaning, demonstrating your understanding of how individual moments connect to larger themes.',
      relatedLearningPoints: [],
    },
  ],
};
