import type { Quiz } from '../../../types';

export const chapter3Quiz: Quiz = {
  id: 'quiz-chapter-3',
  title: 'Chapter 3 Quiz: Jason',
  description: 'Test your knowledge of Jason\'s quest for the Golden Fleece and the consequences of betrayal.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-birthright',
      question: 'Why did Pelias send Jason on the quest for the Golden Fleece?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To reward Jason for his courage and strength',
        'To remove the threat Jason posed to his stolen throne by sending him on an impossible quest',
        'Because the gods commanded it through an oracle',
        'To train Jason to become a worthy king',
      ],
      correctAnswer: 'To remove the threat Jason posed to his stolen throne by sending him on an impossible quest',
      explanation: 'Pelias had usurped the throne from Jason\'s father Aeson. When Jason arrived wearing one sandal (fulfilling an oracle\'s prophecy), Pelias assigned the Golden Fleece quest hoping Jason would die, eliminating the threat to his rule. It\'s the same pattern as Perseus\'s Medusa quest—tyrants assign impossible tasks to remove threats.',
      relatedLearningPoints: ['lp-jason-1-usurpation', 'lp-jason-3-impossible-quest'],
    },
    {
      id: 'q2-ensemble',
      question: 'What makes the Argonauts significant in the history of Western storytelling?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They were the first heroes to use magical weapons',
        'They represent the first major "ensemble quest" in Western literature, establishing team adventure patterns still used today',
        'They were the strongest warriors in Greek mythology',
        'They invented the concept of the hero\'s journey',
      ],
      correctAnswer: 'They represent the first major "ensemble quest" in Western literature, establishing team adventure patterns still used today',
      explanation: 'The Argonauts established the template for ensemble casts: diverse specialists with unique skills uniting for an impossible goal. This pattern appears throughout modern storytelling—from the Avengers and Fellowship of the Ring to Ocean\'s Eleven and the Guardians of the Galaxy. Jason\'s story shifts from solo hero to team leader, creating new narrative possibilities.',
      relatedLearningPoints: ['lp-jason-4-ensemble', 'lp-jason-4-modern'],
    },
    {
      id: 'q3-oath',
      question: 'What oath did Jason swear to Medea, and why was it so significant?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He swore to give her half the Golden Fleece and treasure',
        'He swore by all the gods to make her his wife and never abandon her—an oath that became the moral foundation of the tragedy',
        'He swore to kill her father King Aeëtes',
        'He swore to teach her Greek magic and culture',
      ],
      correctAnswer: 'He swore by all the gods to make her his wife and never abandon her—an oath that became the moral foundation of the tragedy',
      explanation: 'Jason\'s sacred oath to Medea becomes the fulcrum of the entire tragedy. Medea sacrifices everything—family, homeland, innocence—based on this oath. When Jason eventually breaks it to marry Princess Glauce, he commits not just betrayal but oath-breaking, a grave offense to the gods. Medea\'s horrific revenge is framed as justice for a sacred vow violated.',
      relatedLearningPoints: ['lp-jason-8-medea-oath', 'lp-jason-2a-idealism'],
    },
    {
      id: 'q4-trials',
      question: 'How did Jason complete the three impossible tasks set by King Aeëtes?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Through his superior strength and combat skills learned from Chiron',
        'With help from the other Argonauts, especially Heracles',
        'Entirely through Medea\'s magic—a protective salve, a clever trick, and a sleeping spell',
        'By bribing the guards and stealing the Fleece at night',
      ],
      correctAnswer: 'Entirely through Medea\'s magic—a protective salve, a clever trick, and a sleeping spell',
      explanation: 'Jason succeeds not through his own abilities but completely through Medea\'s intervention: her fireproof salve lets him yoke the bronze bulls, her trick makes the dragon\'s teeth warriors fight each other, and her spell puts the sleepless dragon to sleep. This establishes Jason\'s dependency on Medea\'s power—he literally cannot succeed without her, making his eventual betrayal even more ungrateful and tragic.',
      relatedLearningPoints: ['lp-jason-10-magic', 'lp-jason-7-impossible'],
    },
    {
      id: 'q5-medea-sacrifice',
      question: 'What did Medea sacrifice to help Jason escape with the Golden Fleece?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She gave up her priesthood and her magical powers',
        'She murdered her younger brother Apsyrtus and scattered his body parts in the sea to slow her father\'s pursuit',
        'She destroyed the city of Colchis with fire',
        'She challenged her father to single combat and defeated him',
      ],
      correctAnswer: 'She murdered her younger brother Apsyrtus and scattered his body parts in the sea to slow her father\'s pursuit',
      explanation: 'In one of mythology\'s most horrific acts, Medea killed and dismembered her own brother, forcing her father Aeëtes to stop his pursuit to gather the remains for proper burial. This demonstrates the absolute totality of her commitment to Jason—she can never return home, never be forgiven. She has literally nothing left except Jason. This makes his eventual betrayal of her even more devastating.',
      relatedLearningPoints: ['lp-jason-12-brother', 'lp-jason-12-cost'],
    },
    {
      id: 'q6-euripides',
      question: 'In Euripides\' play, what does Medea\'s speech reveal about the position of women in ancient Greek society?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That women had equal rights and freedom in marriage',
        'That women enjoyed lives of leisure free from danger',
        'That women were systematically powerless—they had to "buy" husbands, became property, couldn\'t divorce, and had no recourse against cruelty',
        'That all women in ancient Greece practiced witchcraft',
      ],
      correctAnswer: 'That women were systematically powerless—they had to "buy" husbands, became property, couldn\'t divorce, and had no recourse against cruelty',
      explanation: 'Euripides gives voice to female powerlessness in ancient society: women must provide enormous dowries to "buy" husbands, become their property, cannot divorce, and have no legal recourse if the husband is cruel. When Jason betrays Medea, she loses everything—home, status, security, future. Her revenge, while horrific, is the only power available to her in a system that strips women of all legitimate agency. This contextualizes her violence without justifying it.',
      relatedLearningPoints: ['lp-jason-11-female-perspective', 'lp-jason-11-tragedy'],
    },
    {
      id: 'q7-pelias-death',
      question: 'How did Medea engineer the death of King Pelias after Jason returned with the Fleece?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She poisoned his wine during a celebration feast',
        'She tricked his daughters into cutting him up and boiling him, claiming it would restore his youth',
        'She sent assassins to stab him in his sleep',
        'She turned him into a statue with her magic',
      ],
      correctAnswer: 'She tricked his daughters into cutting him up and boiling him, claiming it would restore his youth',
      explanation: 'Medea demonstrated her magic by rejuvenating an old ram in a cauldron, then convinced Pelias\'s daughters they could restore their father\'s youth the same way. When they cut him up and boiled him, Medea didn\'t provide the magic herbs—he died screaming. It\'s brilliant and horrific, and critically, Jason didn\'t stop her. His complicity in this murder further corrupts his heroism.',
      relatedLearningPoints: ['lp-jason-13-medea-violence', 'lp-jason-13-complicity'],
    },
    {
      id: 'q8-jason-flaw',
      question: 'What is Jason\'s fundamental character flaw that leads to his downfall?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His excessive pride and arrogance',
        'His cowardice in battle',
        'His short-term thinking—solving immediate problems without considering future consequences, and his willingness to discard those who helped him',
        'His inability to lead others effectively',
      ],
      correctAnswer: 'His short-term thinking—solving immediate problems without considering future consequences, and his willingness to discard those who helped him',
      explanation: 'Jason repeatedly makes pragmatic choices that solve immediate crises while creating future disasters: he swears oaths he doesn\'t truly mean, accepts Medea\'s help but takes credit for victories, and abandons her when a better offer comes along. He forgets that every triumph came from her power, not his own. This character flaw—valuing ambition over loyalty, short-term gain over long-term integrity—leads directly to his complete destruction.',
      relatedLearningPoints: ['lp-jason-9a-pragmatism', 'lp-jason-14-temptation', 'lp-jason-15b-rationalization'],
    },
    {
      id: 'q9-betrayal',
      question: 'How did Jason rationalize his decision to divorce Medea and marry Princess Glauce?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He claimed the gods commanded it',
        'He said he never loved Medea',
        'He claimed he was doing it "for the children" to give them a better future as princes of Corinth',
        'He admitted it was purely for personal ambition',
      ],
      correctAnswer: 'He claimed he was doing it "for the children" to give them a better future as princes of Corinth',
      explanation: 'Jason tells himself and Medea that divorcing her and marrying Glauce will make their sons princes of Corinth, giving them security and status. But this is self-deception—he\'s really choosing ambition, youth, a more "acceptable" Greek wife, and a fresh start. Medea sees through this rationalization immediately, recognizing it as the ultimate betrayal after everything she sacrificed.',
      relatedLearningPoints: ['lp-jason-15b-rationalization', 'lp-jason-14-temptation'],
    },
    {
      id: 'q10-medea-revenge',
      question: 'What was Medea\'s revenge for Jason\'s betrayal?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She cursed Jason to wander the earth forever',
        'She sent a poisoned dress that killed Glauce and Creon, then murdered her own children to destroy everything Jason loved',
        'She returned to Colchis and raised an army against Jason',
        'She turned Jason into a monster using her magic',
      ],
      correctAnswer: 'She sent a poisoned dress that killed Glauce and Creon, then murdered her own children to destroy everything Jason loved',
      explanation: 'Medea\'s revenge is total and horrific: she destroys Jason\'s new bride and future in Corinth with a poisoned wedding gift, then commits the most shocking act in Greek mythology—she murders her own sons, the children she bore to Jason. She chooses revenge over motherhood, proving that Jason\'s betrayal has broken her completely. He ends with no wife, no children, no kingdom, no glory—nothing.',
      relatedLearningPoints: ['lp-jason-16-tragedy', 'lp-jason-16-antihero'],
    },
    {
      id: 'q11-jason-death',
      question: 'How does Jason die, and what does his death symbolize?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He dies heroically in battle defending Greece',
        'He dies pathetically when a rotting beam from the Argo falls and crushes him',
        'Medea kills him directly with poison',
        'He lives to old age but in misery',
      ],
      correctAnswer: 'He dies pathetically when a rotting beam from the Argo falls and crushes him',
      explanation: 'Jason\'s death is intentionally unheroic and pathetic—he dies alone, unmourned, crushed by a piece of the decaying Argo, the ship that represented his former glory. He\'s literally killed by the wreckage of his past triumphs. There\'s no honor, no glory, no kleos. It\'s the perfect ending for an antihero whose character flaws led to his complete destruction.',
      relatedLearningPoints: ['lp-jason-16-tragedy', 'lp-jason-16-antihero'],
    },
    {
      id: 'q12-antihero',
      question: 'How does Jason differ from heroes like Perseus or Theseus, and what modern narrative tradition does he represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He is physically stronger and more skilled in combat',
        'He is an early example of the antihero—a morally complex protagonist whose character flaws lead to downfall, like Walter White or Tony Soprano',
        'He receives more help from the gods than other heroes',
        'He completes more heroic labors than any other Greek hero',
      ],
      correctAnswer: 'He is an early example of the antihero—a morally complex protagonist whose character flaws lead to downfall, like Walter White or Tony Soprano',
      explanation: 'Unlike Perseus or Theseus who end in triumph (despite flaws), Jason ends in complete ruin. He\'s an antihero—not evil, but fundamentally flawed, making choices that lead to tragedy. His story follows perfect tragic structure: his character flaw (ambition, disloyalty, ingratitude) directly causes his destruction. This pattern appears in modern antihero narratives like Breaking Bad, The Sopranos, and Game of Thrones, where protagonists are morally complex and their flaws lead to downfall.',
      relatedLearningPoints: ['lp-jason-16-antihero', 'lp-jason-16-tragedy'],
    },
  ],
};
