import type { Quiz } from '../../../types';

export const chapter6Quiz: Quiz = {
  id: 'quiz-chapter-6',
  title: 'Chapter 6 Quiz: Tragedy & Hubris',
  description: 'Test your knowledge of Icarus, Orpheus, Bellerophon, and the timeless lessons about hubris and cautionary tales.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    // ICARUS ARC
    {
      id: 'q1-daedalus-prison',
      question: 'Why were Daedalus and Icarus imprisoned by King Minos?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They stole treasure from the palace',
        'Daedalus helped Theseus navigate the Labyrinth and defeat the Minotaur',
        'They tried to escape Crete by ship',
        'Icarus insulted the king',
      ],
      correctAnswer: 'Daedalus helped Theseus navigate the Labyrinth and defeat the Minotaur',
      explanation: 'Daedalus had built the Labyrinth for Minos, but then betrayed him by helping Theseus navigate it and slay the Minotaur. This enraged Minos, who imprisoned them both.',
      relatedLearningPoints: ['lp-tragedy-1-daedalus'],
    },
    {
      id: 'q2-wings',
      question: 'How did Daedalus plan to escape from Crete?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'By building a secret tunnel',
        'By bribing the guards',
        'By constructing wings from feathers and wax to fly',
        'By stealing a ship at night',
      ],
      correctAnswer: 'By constructing wings from feathers and wax to fly',
      explanation: 'Daedalus crafted wings from feathers held together with wax, allowing them to fly—the one escape route King Minos couldn\'t guard.',
      relatedLearningPoints: ['lp-tragedy-2-invention'],
    },
    {
      id: 'q3-middle-path',
      question: 'What warning did Daedalus give Icarus about flying?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Fly as high as possible to avoid detection',
        'Stay close to the water to stay cool',
        'Follow the middle path—not too high (sun melts wax) nor too low (sea spray weighs down wings)',
        'Fly only at night when it\'s cooler',
      ],
      correctAnswer: 'Follow the middle path—not too high (sun melts wax) nor too low (sea spray weighs down wings)',
      explanation: 'Daedalus warned Icarus to take the middle path, avoiding both extremes. This represents the Greek ideal of moderation (sophrosyne)—avoiding excess in either direction.',
      relatedLearningPoints: ['lp-tragedy-3-warning'],
    },
    {
      id: 'q4-icarus-hubris',
      question: 'What is hubris, as demonstrated by Icarus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Fear and cowardice',
        'Excessive pride and overconfidence that leads to overstepping boundaries',
        'Careful planning and preparation',
        'Loyalty to family',
      ],
      correctAnswer: 'Excessive pride and overconfidence that leads to overstepping boundaries',
      explanation: 'Hubris is excessive pride that causes someone to overstep proper limits. Icarus\'s decision to fly higher despite his father\'s warnings exemplifies this fatal flaw.',
      relatedLearningPoints: ['lp-tragedy-4-hubris'],
    },
    {
      id: 'q5-icarus-fall',
      question: 'What happened to Icarus when he flew too close to the sun?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The sun god Apollo caught him',
        'The wax melted, his wings fell apart, and he plummeted to his death',
        'Zeus struck him with lightning',
        'He successfully reached the sun',
      ],
      correctAnswer: 'The wax melted, his wings fell apart, and he plummeted to his death',
      explanation: 'When Icarus flew too high, the sun\'s heat melted the wax holding his wings together. He fell into the sea and drowned—the inevitable consequence of hubris.',
      relatedLearningPoints: ['lp-tragedy-5-consequences'],
    },

    // ORPHEUS ARC
    {
      id: 'q6-orpheus-gift',
      question: 'What was Orpheus\'s special gift?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Superhuman strength',
        'The ability to see the future',
        'Music so beautiful it could charm nature, animals, and even the gods',
        'Immortality',
      ],
      correctAnswer: 'Music so beautiful it could charm nature, animals, and even the gods',
      explanation: 'Orpheus possessed the power of music and poetry so profound that it could affect nature itself and move even the gods—a gift that would allow him to achieve the impossible.',
      relatedLearningPoints: ['lp-tragedy-6-orpheus'],
    },
    {
      id: 'q7-orpheus-descent',
      question: 'Why did Orpheus descend to the Underworld?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'To steal treasure from Hades',
        'To retrieve his wife Eurydice who had died from a snake bite',
        'To ask the gods for immortality',
        'To defeat a monster',
      ],
      correctAnswer: 'To retrieve his wife Eurydice who had died from a snake bite',
      explanation: 'Orpheus journeyed to the Underworld to bring back Eurydice after she died. This represents humanity\'s refusal to accept death as final—a recurring theme in mythology.',
      relatedLearningPoints: ['lp-tragedy-7-descent'],
    },
    {
      id: 'q8-hades-condition',
      question: 'What condition did Hades place on Orpheus for returning Eurydice to life?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He must defeat Cerberus in combat',
        'He must never speak of what he saw in the Underworld',
        'He must not look back at Eurydice until they both reach the surface world',
        'He must give up his gift of music',
      ],
      correctAnswer: 'He must not look back at Eurydice until they both reach the surface world',
      explanation: 'Hades granted the unprecedented gift of returning a soul to life, but with one condition: Orpheus must walk ahead and not look back until they both reached the surface. This tests whether mortals can trust divine commands.',
      relatedLearningPoints: ['lp-tragedy-8-condition', 'lp-tragedy-8-impossible-gift'],
    },
    {
      id: 'q9-orpheus-failure',
      question: 'Why did Orpheus look back at Eurydice?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He heard her call his name',
        'Hades told him to look back',
        'He doubted she was really there and couldn\'t trust without seeing proof',
        'He wanted to take a selfie',
      ],
      correctAnswer: 'He doubted she was really there and couldn\'t trust without seeing proof',
      explanation: 'Orpheus\'s inability to have faith without proof—his need to verify rather than trust—represents a fundamentally human weakness that cost him everything.',
      relatedLearningPoints: ['lp-tragedy-9-doubt'],
    },
    {
      id: 'q10-orpheus-loss',
      question: 'What makes Orpheus\'s loss especially tragic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He never loved Eurydice',
        'He looked back at the very threshold of success, having almost made it to the surface',
        'Hades refused to let him try',
        'Eurydice chose to stay in the Underworld',
      ],
      correctAnswer: 'He looked back at the very threshold of success, having almost made it to the surface',
      explanation: 'The tragedy is magnified by proximity to success—Orpheus failed at the very moment of victory, making his loss infinitely more painful.',
      relatedLearningPoints: ['lp-tragedy-10-threshold'],
    },

    // BELLEROPHON ARC
    {
      id: 'q11-bellerophon-success',
      question: 'What made Bellerophon famous before his downfall?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He built the Parthenon',
        'He tamed Pegasus and slew the Chimera monster',
        'He won the Olympics',
        'He conquered Troy',
      ],
      correctAnswer: 'He tamed Pegasus and slew the Chimera monster',
      explanation: 'Bellerophon achieved incredible heroic feats—taming the winged horse Pegasus and defeating the monstrous Chimera. These early successes set up his later catastrophic hubris.',
      relatedLearningPoints: ['lp-tragedy-12-success'],
    },
    {
      id: 'q12-bellerophon-hubris',
      question: 'What act of hubris did Bellerophon commit?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He refused to worship the gods',
        'He tried to fly Pegasus to Mount Olympus to join the gods',
        'He declared himself king of all Greece',
        'He challenged Zeus to a duel',
      ],
      correctAnswer: 'He tried to fly Pegasus to Mount Olympus to join the gods',
      explanation: 'Bellerophon believed his achievements made him equal to the gods and tried to fly to Olympus—textbook hubris. The arrogant belief that mortal success makes one divine.',
      relatedLearningPoints: ['lp-tragedy-13-hubris-defined'],
    },
    {
      id: 'q13-zeus-punishment',
      question: 'How did Zeus punish Bellerophon?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Killed him instantly with a lightning bolt',
        'Sent a gadfly to sting Pegasus, causing Bellerophon to fall and wander as a crippled, blind beggar',
        'Imprisoned him in Tartarus',
        'Turned him into a monster',
      ],
      correctAnswer: 'Sent a gadfly to sting Pegasus, causing Bellerophon to fall and wander as a crippled, blind beggar',
      explanation: 'Zeus\'s punishment was precisely calibrated—Bellerophon wanted to rise above mortals, so he was reduced below them. He survived but lost everything that made him heroic, wandering as a broken beggar.',
      relatedLearningPoints: ['lp-tragedy-14-proportional'],
    },

    // THEMES & CONNECTIONS
    {
      id: 'q14-cautionary-pattern',
      question: 'What pattern do Icarus, Orpheus, and Bellerophon share?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They all became kings',
        'They all possessed extraordinary abilities but failed due to human flaws—hubris, doubt, or disobedience',
        'They all defeated monsters',
        'They all lived happily ever after',
      ],
      correctAnswer: 'They all possessed extraordinary abilities but failed due to human flaws—hubris, doubt, or disobedience',
      explanation: 'All three stories follow the cautionary tale pattern: characters with amazing gifts or opportunities fail because of fatal human flaws—Icarus\'s hubris, Orpheus\'s doubt, Bellerophon\'s arrogance.',
      relatedLearningPoints: ['lp-tragedy-15-patterns'],
    },
    {
      id: 'q15-modern-parallels',
      question: 'Which modern work is described as updating the Greek hubris story for the scientific age?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Harry Potter',
        'Frankenstein',
        'The Hunger Games',
        'Star Wars',
      ],
      correctAnswer: 'Frankenstein',
      explanation: 'Frankenstein explores scientific hubris—Victor Frankenstein\'s attempt to create life is humanity trying to become god-like, like Daedalus creating wings or Bellerophon trying to reach Olympus. His brilliant invention becomes his greatest tragedy.',
      relatedLearningPoints: ['lp-tragedy-16-frankenstein'],
    },
  ],
};
