import type { Quiz } from '../../../types';

export const chapter4Quiz: Quiz = {
  id: 'quiz-chapter-4',
  title: 'Chapter 4 Quiz: Heracles and the Twelve Labors',
  description: 'Test your knowledge of Heracles\'s tragic past, his path to redemption, and the lessons learned through his legendary labors.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-birth',
      question: 'Who were Heracles\'s parents?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Zeus and Hera',
        'Zeus and Alcmene',
        'Amphitryon and Alcmene',
        'Poseidon and Alcmene',
      ],
      correctAnswer: 'Zeus and Alcmene',
      explanation: 'Heracles was the son of Zeus, king of the gods, and Alcmene, a mortal woman. Zeus disguised himself as Alcmene\'s husband Amphitryon to seduce her, making Heracles a demigod.',
      relatedLearningPoints: ['lp-heracles-1-divine-birth'],
    },
    {
      id: 'q2-hera-antagonist',
      question: 'Why did Hera hate Heracles from the moment of his birth?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He stole something from her',
        'He was prophesied to overthrow her',
        'He represented proof of Zeus\'s infidelity',
        'He insulted her at a feast',
      ],
      correctAnswer: 'He represented proof of Zeus\'s infidelity',
      explanation: 'Hera, Zeus\'s wife and queen of the gods, hated Heracles because he was living proof of Zeus\'s betrayal. As Zeus\'s illegitimate son, destined for greatness, Heracles embodied everything Hera despised about her husband\'s infidelities.',
      relatedLearningPoints: ['lp-heracles-1-hera-antagonist'],
    },
    {
      id: 'q3-infant-serpents',
      question: 'What did baby Heracles do when Hera sent serpents to kill him in his cradle?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He cried and his parents saved him',
        'He strangled them with his bare hands while laughing',
        'He turned them to stone with magic',
        'He escaped through the window',
      ],
      correctAnswer: 'He strangled them with his bare hands while laughing',
      explanation: 'Even as an eight-month-old infant, Heracles displayed his supernatural strength by strangling the two massive serpents Hera sent to kill him. While his mortal twin brother Iphicles screamed in terror, Heracles laughed with delight, foreshadowing his future as the world\'s greatest hero.',
      relatedLearningPoints: ['lp-heracles-2-infant-strength', 'lp-heracles-2-foreshadowing'],
    },
    {
      id: 'q4-choice-virtue',
      question: 'In the Choice of Heracles allegory, what does choosing Virtue over Vice represent?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Choosing an easy life of pleasure',
        'That heroism requires consciously choosing hardship over comfort to achieve true excellence (arete)',
        'That heroes should avoid all physical comfort',
        'That virtue is only for the weak',
      ],
      correctAnswer: 'That heroism requires consciously choosing hardship over comfort to achieve true excellence (arete)',
      explanation: 'The Choice of Heracles is a famous philosophical allegory showing that true heroism and excellence (arete) require consciously choosing the difficult path of virtue over the easy path of pleasure. This choice reflects the Greek ideal that anything worth having must be earned through struggle.',
      relatedLearningPoints: ['lp-heracles-3-choice', 'lp-heracles-3-allegory'],
    },
    {
      id: 'q5-madness-cause',
      question: 'What caused Heracles to kill his wife and children?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was tricked by an enemy',
        'Hera sent divine madness upon him that made him see enemies instead of family',
        'He became drunk and lost control',
        'He was defending himself from an attack',
      ],
      correctAnswer: 'Hera sent divine madness upon him that made him see enemies instead of family',
      explanation: 'Hera\'s revenge was terrible: she sent divine madness (supernatural frenzy) upon Heracles that destroyed his mind and twisted his perceptions. In his madness, he believed his wife was a hostile invader and his children were enemies\' offspring, leading him to kill them all.',
      relatedLearningPoints: ['lp-heracles-5-madness', 'lp-heracles-5-tragedy'],
    },
    {
      id: 'q6-moral-responsibility',
      question: 'How did ancient Greeks understand moral responsibility when someone committed crimes under divine madness?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They were completely innocent and faced no consequences',
        'They were fully guilty and deserved death',
        'They were both innocent of intent and still responsible for atonement—divine causation did not erase the need for redemption',
        'Divine madness was considered just an excuse for violence',
      ],
      correctAnswer: 'They were both innocent of intent and still responsible for atonement—divine causation did not erase the need for redemption',
      explanation: 'Greek tragedy explores moral complexity: Heracles did not choose to kill his family (Hera caused his madness), yet he still had to live with what he did and atone for it. The gods may cause suffering, but mortals must still find a way to redeem themselves. Divine madness removes moral culpability but not the need for purification.',
      relatedLearningPoints: ['lp-heracles-6-greek-madness', 'lp-heracles-6-complexity'],
    },
    {
      id: 'q7-oracle-labors',
      question: 'What did the Oracle at Delphi command Heracles to do to atone for his crimes?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Exile himself from Greece forever',
        'Serve his cousin Eurystheus for twelve years and complete whatever tasks he demanded',
        'Build a temple to Hera',
        'Sacrifice himself to the gods',
      ],
      correctAnswer: 'Serve his cousin Eurystheus for twelve years and complete whatever tasks he demanded',
      explanation: 'The Oracle commanded Heracles to serve his cousin Eurystheus, King of Mycenae, for twelve years and complete whatever tasks he demanded. This was especially bitter because Eurystheus was a weak, cowardly man who only became king because Hera had tricked Zeus. The Labors represent penance rather than glory-seeking.',
      relatedLearningPoints: ['lp-heracles-7-penance', 'lp-heracles-7-submission'],
    },
    {
      id: 'q8-nemean-lion',
      question: 'How did Heracles ultimately defeat the Nemean Lion, whose hide could not be pierced by any weapon?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He found a magical weapon that could pierce it',
        'He strangled it with his bare hands, using his supernatural strength',
        'He drowned it in a river',
        'He tricked it into falling off a cliff',
      ],
      correctAnswer: 'He strangled it with his bare hands, using his supernatural strength',
      explanation: 'When arrows, swords, and spears all failed against the lion\'s invulnerable hide, Heracles realized he had to use what made him unique—his own supernatural strength. He caught the lion in his bare hands and strangled it to death after a thirty-minute struggle. He then skinned it using its own claws (the only thing sharp enough to cut it) and wore the pelt as armor.',
      relatedLearningPoints: ['lp-heracles-10-strength', 'lp-heracles-10-iconography'],
    },
    {
      id: 'q9-hydra-strategy',
      question: 'What important lesson did the Lernaean Hydra teach Heracles?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That he needed better weapons',
        'That brute force alone was not enough—he needed tactics, problem-solving, and teamwork to succeed',
        'That he should avoid fighting monsters',
        'That he was invincible',
      ],
      correctAnswer: 'That brute force alone was not enough—he needed tactics, problem-solving, and teamwork to succeed',
      explanation: 'The Hydra forced Heracles to evolve beyond pure strength. When cutting off one head made two grow back, he had to think strategically and call his nephew Iolaus for help. Together, they used tactics (cauterizing wounds to prevent regrowth) and teamwork to defeat the monster. The regenerating heads represent problems that worsen with conventional approaches.',
      relatedLearningPoints: ['lp-heracles-12-strategy', 'lp-heracles-12-adaptation'],
    },
    {
      id: 'q10-stymphalian-birds',
      question: 'What did the Stymphalian Birds labor demonstrate about heroism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That heroes must work alone',
        'That strength must be paired with divine wisdom—the right tool, used cleverly, accomplishes what raw power cannot',
        'That birds are dangerous enemies',
        'That heroes should avoid asking for help',
      ],
      correctAnswer: 'That strength must be paired with divine wisdom—the right tool, used cleverly, accomplishes what raw power cannot',
      explanation: 'Athena gave Heracles a bronze rattle made by Hephaestus. The terrifying noise drove the birds into the air where he could shoot them. This shows that heroes must combine strength with divine wisdom and specialized tools. As Heracles grew in wisdom and humility, he earned more divine aid—the gods favor those who learn.',
      relatedLearningPoints: ['lp-heracles-13-tools', 'lp-heracles-13-wisdom'],
    },
    {
      id: 'q11-hippolyta-tragedy',
      question: 'What happened when Heracles tried to obtain the Belt of Hippolyta peacefully?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The Amazons attacked him without provocation',
        'Hippolyta willingly gave him the belt, but Hera disguised herself and spread a rumor that caused the Amazons to attack, leading to Hippolyta\'s death',
        'He was forced to fight all the Amazons',
        'He stole the belt in the night',
      ],
      correctAnswer: 'Hippolyta willingly gave him the belt, but Hera disguised herself and spread a rumor that caused the Amazons to attack, leading to Hippolyta\'s death',
      explanation: 'Queen Hippolyta was impressed by Heracles and agreed to give him the belt willingly, without violence. But Hera, disguised as an Amazon warrior, spread a rumor that Heracles planned to kidnap their queen. In the resulting chaos, Hippolyta died. This shows that even when heroes choose peace, tragedy can follow—some forces conspire against reconciliation.',
      relatedLearningPoints: ['lp-heracles-14-tragedy', 'lp-heracles-14-amazons'],
    },
    {
      id: 'q12-atlas-cunning',
      question: 'How did Heracles trick Atlas into taking back the burden of holding up the sky?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He threatened Atlas with violence',
        'He asked Atlas to hold the sky "just for a moment" so he could pad his shoulders, and Atlas fell for it',
        'He used magic to force Atlas',
        'He convinced the gods to help',
      ],
      correctAnswer: 'He asked Atlas to hold the sky "just for a moment" so he could pad his shoulders, and Atlas fell for it',
      explanation: 'When Atlas returned with the golden apples and tried to leave Heracles holding the sky forever, Heracles used cunning instead of strength. He asked Atlas to hold the sky "just for a moment" to adjust the padding on his shoulders. Atlas, not thinking clearly after eons of torment, took back the burden—and Heracles grabbed the apples and left. This shows his complete evolution from relying solely on strength to using intellect and strategic thinking.',
      relatedLearningPoints: ['lp-heracles-16-cunning', 'lp-heracles-16-burden'],
    },
    {
      id: 'q13-superhero-parallel',
      question: 'Which modern superhero\'s struggle with uncontrollable rage and fear of hurting loved ones most directly mirrors Heracles\'s tragedy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Superman',
        'Batman',
        'The Hulk',
        'Wonder Woman',
      ],
      correctAnswer: 'The Hulk',
      explanation: 'The Hulk\'s uncontrollable rage and fear of hurting others mirrors Heracles\'s divine madness and the tragedy of misdirected strength. Bruce Banner\'s constant struggle is Heracles\'s tragedy—power that can destroy what it should protect. Both characters must live with the guilt of actions committed while not in control of themselves.',
      relatedLearningPoints: ['lp-heracles-8-hulk'],
    },
    {
      id: 'q14-redemption-arc',
      question: 'What narrative structure did Heracles originate that remains central to superhero stories today?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The chosen one narrative',
        'The redemption arc through heroic deeds',
        'The mentor-student relationship',
        'The secret identity trope',
      ],
      correctAnswer: 'The redemption arc through heroic deeds',
      explanation: 'The "redemption arc through heroic deeds" structure originated with Heracles and remains central to superhero narratives today. The pattern of superpowered individual commits tragedy (often accidentally), seeks redemption through heroic deeds, and struggles with the burden of power appears in Spider-Man, Batman, and countless other modern heroes.',
      relatedLearningPoints: ['lp-heracles-8-redemption', 'lp-heracles-18-legacy'],
    },
    {
      id: 'q15-labor-progression',
      question: 'How do the Twelve Labors function as a bildungsroman (coming-of-age story)?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They show Heracles getting physically stronger with each labor',
        'Each trial teaches Heracles new skills until he achieves complete heroism—progressing from pure strength to strategic thinking, wisdom, and cunning',
        'They are simply a list of his victories',
        'They demonstrate that strength alone is sufficient for heroism',
      ],
      correctAnswer: 'Each trial teaches Heracles new skills until he achieves complete heroism—progressing from pure strength to strategic thinking, wisdom, and cunning',
      explanation: 'The Labors progress from pure strength challenges (Nemean Lion) to tasks requiring cleverness (Hydra), using divine gifts (Stymphalian Birds), seeking peaceful solutions (Belt of Hippolyta), and ultimately cunning and mental agility (tricking Atlas). Each labor teaches Heracles something new about heroism, showing his growth beyond physical power.',
      relatedLearningPoints: ['lp-heracles-17-progression', 'lp-heracles-9a-progression'],
    },
  ],
};
