import type { Quiz } from '../../../types';

export const chapter5Quiz: Quiz = {
  id: 'quiz-chapter-5',
  title: 'Chapter 5 Quiz: Heracles - Part II',
  description: 'Test your knowledge of Heracles\' life beyond the labors, his tragic flaws, and the deconstruction of the superhero archetype.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-aftermath',
      question: 'After completing his twelve labors, what did Heracles discover about his life?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The labors brought him lasting peace and happiness',
        'Completing heroic tasks didn\'t resolve his inner struggles or give him purpose',
        'He was immediately granted godhood by Zeus',
        'He retired to a quiet life with his family',
      ],
      correctAnswer: 'Completing heroic tasks didn\'t resolve his inner struggles or give him purpose',
      explanation: 'The chapter emphasizes that Heracles was only in his thirties when the labors ended, and he struggled to find purpose in peacetime. His heroic achievements hadn\'t made him happy or wise—he became a wandering adventurer unable to settle into normal life.',
      relatedLearningPoints: ['lp-heracles-1-aftermath', 'lp-heracles-8-restlessness'],
    },
    {
      id: 'q2-troy-anger',
      question: 'What pattern of behavior does Heracles demonstrate when King Laomedon refuses to give him the promised horses?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He calmly negotiates a different payment',
        'He accepts the loss and moves on peacefully',
        'He destroys Troy in an explosive rage, demonstrating his inability to control anger when insulted',
        'He seeks legal justice through the Greek council',
      ],
      correctAnswer: 'He destroys Troy in an explosive rage, demonstrating his inability to control anger when insulted',
      explanation: 'Heracles\' sacking of Troy over broken promises reveals his greatest flaw: explosive rage when his honor is challenged. This inability to control his anger becomes a recurring tragic pattern throughout his life.',
      relatedLearningPoints: ['lp-heracles-2-anger', 'lp-heracles-4a-tragedy'],
    },
    {
      id: 'q3-deianira-relationship',
      question: 'How is Deianira portrayed in her relationship with Heracles?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'As a helpless princess who needs constant protection',
        'As an equal partner who challenges Heracles to confront his own nature',
        'As a villain who plots against him from the start',
        'As a minor character with no significant role',
      ],
      correctAnswer: 'As an equal partner who challenges Heracles to confront his own nature',
      explanation: 'The chapter emphasizes that Deianira is not a passive prize but an equal partner who directly challenges Heracles about his temper and violent nature. She asks him to discover who he is beyond monster-slaying.',
      relatedLearningPoints: ['lp-heracles-3-relationship'],
    },
    {
      id: 'q4-nessus-irony',
      question: 'What makes the Nessus episode tragically ironic?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Nessus defeats Heracles in combat',
        'The Hydra-poisoned arrow Heracles uses to save Deianira becomes the instrument of his own death',
        'Deianira was secretly in love with Nessus',
        'Heracles refuses to help Deianira escape',
      ],
      correctAnswer: 'The Hydra-poisoned arrow Heracles uses to save Deianira becomes the instrument of his own death',
      explanation: 'The dramatic irony is that the weapon from Heracles\' second labor—the Hydra\'s poison—which he uses heroically to save his wife, ultimately becomes the poison that kills him through Nessus\'s blood.',
      relatedLearningPoints: ['lp-heracles-5-protection', 'lp-heracles-5-tragic-irony', 'lp-heracles-6-revenge'],
    },
    {
      id: 'q5-deconstruction',
      question: 'According to the chapter, what do modern works like "Watchmen," "The Boys," and "Logan" have in common with Heracles\' story?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'They all celebrate superhuman power without examining its consequences',
        'They all show heroes as perfect moral exemplars',
        'They deconstruct the superhero archetype to reveal flawed, damaged humans beneath the power',
        'They all end with the hero achieving perfect happiness',
      ],
      correctAnswer: 'They deconstruct the superhero archetype to reveal flawed, damaged humans beneath the power',
      explanation: 'The chapter explicitly connects these modern works to what Greek tragedy did 2,400 years ago: stripping away the superhuman exterior to reveal the broken human underneath. They show that superhuman power in flawed human hands creates tragedy.',
      relatedLearningPoints: ['lp-heracles-7-deconstruction', 'lp-heracles-7-power-danger'],
    },
    {
      id: 'q6-iole-betrayal',
      question: 'What does Heracles\' treatment of Iole and Deianira reveal about his character?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That he is always thoughtful about others\' feelings',
        'That even loving heroes can be thoughtlessly cruel and can be perpetrators as well as protectors',
        'That he never really cared about anyone',
        'That his strength makes him immune to moral judgment',
      ],
      correctAnswer: 'That even loving heroes can be thoughtlessly cruel and can be perpetrators as well as protectors',
      explanation: 'Heracles destroys an entire city to possess Iole, kills her family, and brings her home to his loyal wife—demonstrating how heroes can be perpetrators of violence even as they see themselves as protectors. His casual dismissal of Deianira\'s feelings shows thoughtless cruelty.',
      relatedLearningPoints: ['lp-heracles-9-iole', 'lp-heracles-9a-betrayal'],
    },
    {
      id: 'q7-deianira-motivation',
      question: 'Why does Deianira use Nessus\'s "love charm"?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She wants to murder Heracles in revenge',
        'She is manipulated by her legitimate fears and desperate love, trusting her enemy out of pain',
        'She knows it\'s poison and uses it anyway',
        'She is ordered to do it by the gods',
      ],
      correctAnswer: 'She is manipulated by her legitimate fears and desperate love, trusting her enemy out of pain',
      explanation: 'The chapter emphasizes that Deianira\'s tragedy comes from legitimate pain after decades of betrayal. She believes the charm will save her marriage, not realizing that a dying centaur would only give her revenge, not help.',
      relatedLearningPoints: ['lp-heracles-6-manipulation', 'lp-heracles-10a-desperation'],
    },
    {
      id: 'q8-poisoned-robe',
      question: 'How does Heracles\' divine strength become a curse during his death?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It prevents him from removing the robe',
        'It keeps him alive while the poison slowly destroys him, prolonging his agony',
        'It causes the poison to spread faster',
        'It makes the gods angry with him',
      ],
      correctAnswer: 'It keeps him alive while the poison slowly destroys him, prolonging his agony',
      explanation: 'Heracles\' greatest asset—his divine strength and heritage—becomes a curse by preventing him from dying quickly. Power turns to suffering as he begs for death but his body won\'t release him.',
      relatedLearningPoints: ['lp-heracles-11-poison', 'lp-heracles-11-strength-curse'],
    },
    {
      id: 'q9-sophocles-humanity',
      question: 'In Sophocles\' "Women of Trachis," what truth about heroism does Heracles\' suffering reveal?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That true heroes never suffer',
        'That superhuman achievements cannot escape human vulnerability—even the greatest hero is mortal',
        'That the gods always protect their children',
        'That strength is the only thing that matters',
      ],
      correctAnswer: 'That superhuman achievements cannot escape human vulnerability—even the greatest hero is mortal',
      explanation: 'Sophocles deconstructs heroism by showing Heracles reduced to a "writhing, screaming thing" despite all his legendary labors. This is the core of Greek tragedy: greatness doesn\'t exempt anyone from human pain and mortality.',
      relatedLearningPoints: ['lp-heracles-12-tragedy', 'lp-heracles-12-irony'],
    },
    {
      id: 'q10-apotheosis-meaning',
      question: 'According to the chapter, what does Heracles\' apotheosis (transformation into a god) suggest about the path to transcendence?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'That strength alone is enough to become divine',
        'That gods simply choose favorites randomly',
        'That divinity is achieved through fully experiencing and transcending human suffering, not just through heroic deeds',
        'That anyone who completes twelve labors becomes a god',
      ],
      correctAnswer: 'That divinity is achieved through fully experiencing and transcending human suffering, not just through heroic deeds',
      explanation: 'The chapter poses the question: Did Heracles earn apotheosis through his labors or through his suffering? It concludes that transcendence comes from fully experiencing human flaws, pain, and mortality—becoming divine not despite being human, but because he fully experienced what it means to be human.',
      relatedLearningPoints: ['lp-heracles-14-apotheosis', 'lp-heracles-14-redemption'],
    },
    {
      id: 'q11-tragic-cycle',
      question: 'How does the chapter illustrate that Heracles\' past violence comes back to destroy him?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His old enemies band together to attack him',
        'The Hydra poison from his second labor becomes the poison that kills him through Nessus\'s blood',
        'Zeus punishes him for his violent past',
        'He is killed by one of the monsters he defeated',
      ],
      correctAnswer: 'The Hydra poison from his second labor becomes the poison that kills him through Nessus\'s blood',
      explanation: 'The cause-effect scene explicitly shows this cycle: Heracles shoots Nessus with a Hydra-poisoned arrow, and the dying centaur\'s blood (mixed with that poison) becomes the weapon that kills Heracles. His past violence literally comes back to destroy him.',
      relatedLearningPoints: ['lp-heracles-11-poison', 'lp-heracles-6-revenge'],
    },
    {
      id: 'q12-human-flaws',
      question: 'What does the chapter identify as Heracles\' greatest human flaws that lead to tragedy?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His lack of physical strength and courage',
        'His excessive wisdom and caution',
        'His rage, pride, lust, and inability to control his strength—human flaws amplified by superhuman power',
        'His unwillingness to help others',
      ],
      correctAnswer: 'His rage, pride, lust, and inability to control his strength—human flaws amplified by superhuman power',
      explanation: 'The cause-effect scene explicitly states that Heracles\' tragedy stems from human flaws (rage, pride, lust) that his superhuman strength amplifies rather than mitigates. His power makes every angry gesture potentially fatal.',
      relatedLearningPoints: ['lp-heracles-15-flaws', 'lp-heracles-4a-tragedy'],
    },
    {
      id: 'q13-deianira-suicide',
      question: 'What does Deianira do when she learns what her "love charm" has actually done to Heracles?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She flees to another city',
        'She takes her own life in grief and horror',
        'She blames Nessus publicly',
        'She tries to find an antidote',
      ],
      correctAnswer: 'She takes her own life in grief and horror',
      explanation: 'The chapter states that Deianira takes her own life when she realizes her "love charm" was killing her husband. She had never meant to kill him—only to win back his love. Her suicide completes the tragedy, with both hero and wife destroyed by love and misunderstanding.',
      relatedLearningPoints: ['lp-heracles-13-deianira'],
    },
    {
      id: 'q14-pyre-transformation',
      question: 'What symbolic function does the funeral pyre serve in Heracles\' story?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It simply ends his life with no further meaning',
        'It becomes a transformative ritual, burning away mortal suffering to reveal divine essence',
        'It proves that gods can\'t really die',
        'It serves as punishment for his crimes',
      ],
      correctAnswer: 'It becomes a transformative ritual, burning away mortal suffering to reveal divine essence',
      explanation: 'The chapter explains that the pyre meant to end suffering becomes the gateway to transformation. Embracing mortality paradoxically leads to immortality as Heracles\' mortal flesh burns away but his divine essence ascends to Olympus.',
      relatedLearningPoints: ['lp-heracles-13-pyre'],
    },
    {
      id: 'q15-modern-relevance',
      question: 'Why does the chapter suggest Heracles\' story remains relevant to modern superhero narratives?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Because superhero stories should always be simple and optimistic',
        'Because the Greeks invented all modern storylines',
        'Because the pattern of examining power without wisdom, and humanity beneath heroism, is timeless',
        'Because all modern heroes are based on Greek gods',
      ],
      correctAnswer: 'Because the pattern of examining power without wisdom, and humanity beneath heroism, is timeless',
      explanation: 'The chapter emphasizes that both ancient Greek tragedy and modern deconstructions (Watchmen, The Boys, Logan) explore the same timeless theme: superhuman power in the hands of someone with human flaws creates tragedy. The Greeks understood that power without wisdom destroys everything it touches.',
      relatedLearningPoints: ['lp-heracles-7-deconstruction', 'lp-heracles-7-power-danger'],
    },
  ],
};
