import type { Quiz } from '../../../types';

export const chapter2Quiz: Quiz = {
  id: 'quiz-chapter-2',
  title: 'Chapter 2: Theseus - The Civilizing Hero',
  description: 'Test your knowledge of Theseus\'s journey from road-clearing hero to tragic king.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-tokens',
      question: 'What did Theseus find beneath the boulder when he lifted it?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A map to Athens and a letter from his father',
        'A sword and sandals',
        'Gold coins and royal robes',
        'A shield and helmet',
      ],
      correctAnswer: 'A sword and sandals',
      explanation: 'Theseus found his father Aegeus\'s tokens beneath the boulder: a sword and a pair of sandals that proved his identity as the king\'s son.',
      relatedLearningPoints: ['lp-theseus-1-birthright'],
    },
    {
      id: 'q2-road-choice',
      question: 'Why did Theseus choose the dangerous land route to Athens instead of the safe sea route?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was afraid of sailing',
        'The sea route was blocked',
        'He wanted to clear the road of bandits and monsters to help other travelers',
        'His mother told him to take the land route',
      ],
      correctAnswer: 'He wanted to clear the road of bandits and monsters to help other travelers',
      explanation: 'Theseus deliberately chose the dangerous path to prove himself as a "civilizer hero"—someone who makes the world safer for ordinary people, not just seeking personal glory.',
      relatedLearningPoints: ['lp-theseus-2-choice', 'lp-theseus-2-civilizer'],
    },
    {
      id: 'q3-periphetes',
      question: 'What weapon did Theseus take from Periphetes after defeating him?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A bronze club',
        'An iron spear',
        'A golden bow',
        'A magical sword',
      ],
      correctAnswer: 'A bronze club',
      explanation: 'Theseus took Periphetes\'s bronze club as both a weapon and a trophy, establishing the pattern of heroes claiming the weapons of defeated enemies.',
      relatedLearningPoints: ['lp-theseus-3a-trophies'],
    },
    {
      id: 'q4-sinis',
      question: 'How did Sinis the Pine-Bender kill his victims?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He pushed them off cliffs',
        'He tied them between two bent pine trees and released them',
        'He crushed them with a giant boulder',
        'He fed them to a sea monster',
      ],
      correctAnswer: 'He tied them between two bent pine trees and released them',
      explanation: 'Sinis would tie victims\' arms to two bent pine trees, then release them so the trees would spring back and tear the person apart. Theseus gave him the same death as poetic justice.',
      relatedLearningPoints: ['lp-theseus-3a-justice'],
    },
    {
      id: 'q5-procrustes',
      question: 'What made Procrustes\'s "hospitality" so horrific?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He poisoned his guests\' food',
        'He stretched or cut guests to make them "fit" his bed',
        'He locked guests in cells',
        'He forced guests to fight each other',
      ],
      correctAnswer: 'He stretched or cut guests to make them "fit" his bed',
      explanation: 'Procrustes claimed to have a bed that fit everyone perfectly, but actually stretched short guests on a rack or cut the legs off tall guests—a grotesque violation of hospitality customs.',
      relatedLearningPoints: ['lp-theseus-3b-psychology'],
    },
    {
      id: 'q6-tribute',
      question: 'What was the tribute that Athens had to send to Crete every nine years?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Gold and silver',
        'Seven young men and seven young women',
        'One hundred cattle',
        'Ships and weapons',
      ],
      correctAnswer: 'Seven young men and seven young women',
      explanation: 'Athens was forced to send fourteen youths (seven boys and seven girls) to be devoured by the Minotaur in the Labyrinth—a humiliating symbol of Athens\' subjugation to Cretan power.',
      relatedLearningPoints: ['lp-theseus-4-tribute'],
    },
    {
      id: 'q7-volunteer',
      question: 'What does Theseus\'s decision to volunteer for the tribute demonstrate about his character?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was reckless and foolish',
        'He was trying to impress his father',
        'He was willing to sacrifice himself for his people, showing political leadership',
        'He wanted personal glory more than anything',
      ],
      correctAnswer: 'He was willing to sacrifice himself for his people, showing political leadership',
      explanation: 'Unlike heroes who fought for personal glory, Theseus volunteered to stand with ordinary people and risk everything for their freedom—establishing him as a political hero and future leader.',
      relatedLearningPoints: ['lp-theseus-5a-leadership'],
    },
    {
      id: 'q8-sails',
      question: 'What agreement did Theseus make with his father Aegeus about the ship\'s sails?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Keep the sails down until entering the harbor',
        'Change to white sails if successful, keep black sails if failed',
        'Fly a red flag if victorious',
        'Send a messenger bird ahead',
      ],
      correctAnswer: 'Change to white sails if successful, keep black sails if failed',
      explanation: 'Aegeus watched from a cliff for the returning ship. Black sails meant death; white sails meant victory. Theseus tragically forgot to change the sails.',
      relatedLearningPoints: ['lp-theseus-6a-sails'],
    },
    {
      id: 'q9-ariadne-help',
      question: 'How did Ariadne help Theseus survive the Labyrinth?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She gave him a map of the Labyrinth',
        'She gave him a ball of thread to mark his path',
        'She killed the Minotaur herself',
        'She distracted the guards',
      ],
      correctAnswer: 'She gave him a ball of thread to mark his path',
      explanation: 'Ariadne gave Theseus a ball of red thread to tie at the entrance and unwind as he went, creating a lifeline back to the exit—intelligence conquering chaos.',
      relatedLearningPoints: ['lp-theseus-11-thread'],
    },
    {
      id: 'q10-minotaur-symbol',
      question: 'What does the Minotaur symbolize according to the chapter\'s analysis?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Pure evil that must be destroyed',
        'The beast within civilization, created by human sin and hidden away',
        'Divine punishment for disobedience',
        'Natural chaos that heroes must conquer',
      ],
      correctAnswer: 'The beast within civilization, created by human sin and hidden away',
      explanation: 'The Minotaur was born from Pasiphaë\'s unnatural union—a sin created by civilization itself, then hidden in the Labyrinth rather than confronted. It represents the dark secrets societies bury.',
      relatedLearningPoints: ['lp-theseus-13-symbol'],
    },
    {
      id: 'q11-ariadne-abandonment',
      question: 'What did Theseus do to Ariadne after escaping Crete?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Married her immediately',
        'Made her queen of Athens',
        'Abandoned her on the island of Naxos',
        'Brought her safely to Athens',
      ],
      correctAnswer: 'Abandoned her on the island of Naxos',
      explanation: 'Despite promising to take her to Athens, Theseus abandoned Ariadne on Naxos while she slept—a morally ambiguous act that reveals the complexity of his character.',
      relatedLearningPoints: ['lp-theseus-14-abandonment'],
    },
    {
      id: 'q12-black-sails',
      question: 'What tragic consequence resulted from Theseus forgetting to change the sails?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The ship crashed on the rocks',
        'His crew mutinied against him',
        'His father Aegeus saw black sails and threw himself off a cliff',
        'Athens refused to let him enter the city',
      ],
      correctAnswer: 'His father Aegeus saw black sails and threw himself off a cliff',
      explanation: 'Seeing black sails and believing Theseus was dead, King Aegeus threw himself into the sea in grief. The sea was thereafter named the Aegean Sea.',
      relatedLearningPoints: ['lp-theseus-16-tragedy'],
    },
    {
      id: 'q13-civilizer',
      question: 'How does Theseus as a "civilizer hero" differ from heroes like Perseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He was stronger and braver',
        'He cleared roads and made society safer for ordinary people, not just slaying one monster',
        'He never needed help from the gods',
        'He became king while other heroes did not',
      ],
      correctAnswer: 'He cleared roads and made society safer for ordinary people, not just slaying one monster',
      explanation: 'Unlike monster-slayers who hunt specific beasts, civilizer heroes like Theseus clear roads, defeat multiple threats, and make the world systematically safer for everyone.',
      relatedLearningPoints: ['lp-theseus-2-civilizer', 'lp-theseus-3b-civilizer'],
    },
    {
      id: 'q14-labyrinth-metaphor',
      question: 'What does the Labyrinth represent as a metaphor?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'The simplicity of heroic quests',
        'Life\'s complexity and the need for guidance to navigate impossible situations',
        'The power of physical strength',
        'The inevitability of death',
      ],
      correctAnswer: 'Life\'s complexity and the need for guidance to navigate impossible situations',
      explanation: 'The Labyrinth works as a metaphor for life\'s confusing challenges—we need guidance (mentors, wisdom, tools like Ariadne\'s thread) to navigate seemingly impossible situations.',
      relatedLearningPoints: ['lp-theseus-11-metaphor'],
    },
    {
      id: 'q15-leadership',
      question: 'What does Theseus\'s story ultimately teach about leadership and power?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Heroes always make perfect leaders',
        'Strength in battle guarantees wisdom in governance',
        'Heroism in crisis doesn\'t always translate to wisdom in governance—power can corrupt even the well-intentioned',
        'Leaders should never show weakness',
      ],
      correctAnswer: 'Heroism in crisis doesn\'t always translate to wisdom in governance—power can corrupt even the well-intentioned',
      explanation: 'Theseus was genuinely heroic in defeating the Minotaur and clearing the roads, but his later failures (abandoning Ariadne, forgetting the sails) show that heroism doesn\'t guarantee wise leadership.',
      relatedLearningPoints: ['lp-theseus-19-modern', 'lp-theseus-19-complexity'],
    },
  ],
};
