import type { Quiz } from '../../../types';

export const chapter1Quiz: Quiz = {
  id: 'quiz-chapter-1',
  title: 'Chapter 1 Quiz: Perseus',
  description: 'Test your knowledge of Perseus\'s heroic journey and the archetypal chosen one narrative.',
  passingScore: 70,
  allowRetry: true,

  questions: [
    {
      id: 'q1-prophecy',
      question: 'What prophecy did King Acrisius receive from the Oracle at Delphi?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'His daughter would become a powerful queen',
        'His grandson would kill him',
        'He would lose his kingdom to a foreign invader',
        'His wife would betray him',
      ],
      correctAnswer: 'His grandson would kill him',
      explanation: 'The Oracle prophesied that Acrisius would be killed by his daughter\'s son. This prophecy set in motion the entire Perseus myth, as Acrisius\'s attempts to prevent it actually brought it about—a common pattern in Greek tragedy.',
      relatedLearningPoints: ['lp-perseus-1-prophecy', 'lp-perseus-1-oracle'],
    },
    {
      id: 'q2-zeus-form',
      question: 'How did Zeus visit Danaë in her sealed bronze chamber?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'As a swan',
        'As a shower of golden rain',
        'As a bull',
        'As an eagle',
      ],
      correctAnswer: 'As a shower of golden rain',
      explanation: 'Zeus transformed himself into a shower of golden rain to slip through the roof vent of Danaë\'s chamber. This transformation marks Perseus as a demi-god and demonstrates that divine power cannot be constrained by mortal walls.',
      relatedLearningPoints: ['lp-perseus-3-divine-conception'],
    },
    {
      id: 'q3-acrisius-exile',
      question: 'How did Acrisius attempt to avoid directly killing Danaë and baby Perseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He sent them to live on a distant island',
        'He locked them in a wooden chest and cast them into the sea',
        'He gave them to slave traders',
        'He left them in the wilderness',
      ],
      correctAnswer: 'He locked them in a wooden chest and cast them into the sea',
      explanation: 'Acrisius put Danaë and Perseus in a wooden chest and cast them into the sea, hoping to avoid the gods\' wrath for directly killing his own family. This "child cast out and raised in exile" motif appears in many hero myths, including Moses and Oedipus.',
      relatedLearningPoints: ['lp-perseus-4-exile', 'lp-perseus-4-divine-protection'],
    },
    {
      id: 'q4-polydectes-motive',
      question: 'Why did King Polydectes send Perseus on the impossible quest to kill Medusa?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He genuinely wanted Medusa\'s head as a trophy',
        'He hoped Perseus would die, removing the obstacle to marrying Danaë',
        'He wanted to test Perseus\'s courage',
        'The gods commanded him to send Perseus on a quest',
      ],
      correctAnswer: 'He hoped Perseus would die, removing the obstacle to marrying Danaë',
      explanation: 'Polydectes desired Danaë but Perseus stood in his way. By sending Perseus on an "impossible" quest, Polydectes hoped to eliminate him. This is a classic example of the "impossible task" device used to remove heroes—though it often triggers the heroic journey instead.',
      relatedLearningPoints: ['lp-perseus-5-impossible-quest'],
    },
    {
      id: 'q5-call-adventure',
      question: 'Which modern story does NOT follow the same "Call to Adventure" pattern as Perseus?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Luke Skywalker finding Leia\'s message',
        'Harry Potter receiving his Hogwarts letter',
        'Neo being offered the red pill',
        'Batman\'s parents being wealthy philanthropists',
      ],
      correctAnswer: 'Batman\'s parents being wealthy philanthropists',
      explanation: 'Batman\'s "Call to Adventure" is his parents\' murder, not their wealth. The other three examples all show the hero receiving a challenge that takes them from safety into the unknown—just like Perseus accepting Polydectes\' challenge.',
      relatedLearningPoints: ['lp-perseus-6-call', 'lp-perseus-6-modern'],
    },
    {
      id: 'q6-divine-gifts',
      question: 'Which divine gifts did Perseus receive to help him kill Medusa?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'A magic bow and arrows from Artemis',
        'A shield, winged sandals, and an adamantine sword',
        'The golden fleece and a magic helmet',
        'Lightning bolts from Zeus',
      ],
      correctAnswer: 'A shield, winged sandals, and an adamantine sword',
      explanation: 'Athena gave Perseus a polished bronze shield (to see Medusa\'s reflection), and Hermes provided winged sandals and an adamantine sword. These gifts demonstrate a key principle: Greek heroes succeed through a combination of their own courage and divine assistance—neither alone is sufficient.',
      relatedLearningPoints: ['lp-perseus-8-divine-aid', 'lp-perseus-8-tools'],
    },
    {
      id: 'q7-mirror-shield',
      question: 'Why was Athena\'s polished shield critical to Perseus\'s success?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'It protected him from Medusa\'s snake hair',
        'It allowed him to see Medusa\'s reflection without looking directly at her',
        'It could deflect magical attacks',
        'It made him invisible to the Gorgons',
      ],
      correctAnswer: 'It allowed him to see Medusa\'s reflection without looking directly at her',
      explanation: 'Anyone who looked directly at Medusa turned to stone. The mirror-bright shield allowed Perseus to see her reflection and strike without meeting her deadly gaze. This clever solution shows how intelligence and divine gifts combine to overcome impossible challenges.',
      relatedLearningPoints: ['lp-perseus-10-reflection'],
    },
    {
      id: 'q8-medusa-victim',
      question: 'According to Ovid\'s version of the myth, how did Medusa become a Gorgon?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She was born as a monster',
        'She was cursed by Athena after being assaulted by Poseidon in Athena\'s temple',
        'She willingly transformed herself to gain power',
        'She was punished for her vanity',
      ],
      correctAnswer: 'She was cursed by Athena after being assaulted by Poseidon in Athena\'s temple',
      explanation: 'Ovid presents Medusa as a tragic victim: a beautiful woman assaulted by Poseidon in Athena\'s temple, then cursed by Athena for the violation of her sacred space. This backstory adds moral complexity to the simple "hero slays monster" narrative.',
      relatedLearningPoints: ['lp-perseus-11-transformation', 'lp-perseus-11-perspective'],
    },
    {
      id: 'q9-andromeda-sacrifice',
      question: 'Why was Andromeda chained to a rock as a sacrifice?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'She had offended Athena',
        'Her mother boasted that she was more beautiful than the sea nymphs',
        'She had stolen from Poseidon\'s temple',
        'A prophet demanded her sacrifice',
      ],
      correctAnswer: 'Her mother boasted that she was more beautiful than the sea nymphs',
      explanation: 'Queen Cassiopeia\'s boast that Andromeda was more beautiful than the sea nymphs offended Poseidon. He sent a sea monster to ravage the coast, and the Oracle declared only Andromeda\'s sacrifice would appease it. This exemplifies hubris—excessive pride that offends the gods and brings catastrophe.',
      relatedLearningPoints: ['lp-perseus-12-hubris'],
    },
    {
      id: 'q10-heroism-choice',
      question: 'What does Perseus\'s decision to save Andromeda reveal about true heroism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Heroes must complete every quest they encounter',
        'True heroism involves choosing to help others even when it\'s not part of your assigned quest',
        'Heroes should focus only on their original mission',
        'Heroism is about gaining rewards and marriage alliances',
      ],
      correctAnswer: 'True heroism involves choosing to help others even when it\'s not part of your assigned quest',
      explanation: 'Perseus had already completed his quest—he had Medusa\'s head and could have simply flown home. His choice to help Andromeda shows that heroism isn\'t just about fulfilling assigned tasks, but about choosing to help when you could walk away.',
      relatedLearningPoints: ['lp-perseus-13a-heroism'],
    },
    {
      id: 'q11-polydectes-fate',
      question: 'What happened to Polydectes when Perseus returned to Seriphos?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'He fled the island in fear',
        'He was turned to stone when Perseus showed him Medusa\'s head',
        'He apologized and released Danaë',
        'He challenged Perseus to single combat',
      ],
      correctAnswer: 'He was turned to stone when Perseus showed him Medusa\'s head',
      explanation: 'Perseus used Medusa\'s head against Polydectes and his supporters, turning them to stone. The weapon gained in the quest solves the original problem, completing the heroic cycle. Polydectes\' petrification represents poetic justice—frozen forever in an expression of mockery.',
      relatedLearningPoints: ['lp-perseus-14-return', 'lp-perseus-14-justice'],
    },
    {
      id: 'q12-prophecy-fulfillment',
      question: 'How was the original prophecy about Acrisius eventually fulfilled?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Perseus deliberately hunted down his grandfather',
        'Perseus accidentally killed Acrisius with a discus at athletic games',
        'Acrisius died of natural causes while Perseus was away',
        'The prophecy was never fulfilled',
      ],
      correctAnswer: 'Perseus accidentally killed Acrisius with a discus at athletic games',
      explanation: 'Despite all of Acrisius\'s attempts to prevent the prophecy, it came true accidentally when Perseus threw a discus that struck and killed him at athletic games. This demonstrates a central theme of Greek tragedy: fate is inevitable, though its path may surprise us.',
      relatedLearningPoints: ['lp-perseus-15-causality'],
    },
    {
      id: 'q13-divine-aid-principle',
      question: 'What principle does Perseus\'s story teach about Greek heroism?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Heroes succeed entirely through their own strength',
        'Heroes succeed entirely through divine favor',
        'Heroes succeed through a combination of personal courage and divine assistance',
        'Heroes succeed through trickery and deception',
      ],
      correctAnswer: 'Heroes succeed through a combination of personal courage and divine assistance',
      explanation: 'Perseus needed both his own courage to face Medusa and the divine gifts from Athena and Hermes. Greek heroes typically succeed through this combination—neither personal qualities nor divine favor alone is sufficient.',
      relatedLearningPoints: ['lp-perseus-8-divine-aid'],
    },
    {
      id: 'q14-prophecy-irony',
      question: 'What literary pattern does Acrisius\'s story demonstrate?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Villains always get what they deserve',
        'Attempts to prevent prophecy often create the circumstances for it to occur',
        'Prophecies are always false',
        'Hard work and planning can overcome fate',
      ],
      correctAnswer: 'Attempts to prevent prophecy often create the circumstances for it to occur',
      explanation: 'Acrisius\'s attempts to prevent the prophecy—locking away Danaë, casting Perseus to sea—directly led to Perseus\'s divine conception and heroic journey. This pattern of prophecy fulfillment despite (or because of) prevention attempts is central to Greek tragedy.',
      relatedLearningPoints: ['lp-perseus-3-futility', 'lp-perseus-15-causality'],
    },
    {
      id: 'q15-chosen-one-archetype',
      question: 'Which element is NOT typically part of the "chosen one" archetype that Perseus represents?',
      type: 'multiple-choice',
      points: 10,
      options: [
        'Extraordinary birth or parentage',
        'Being cast out and raised in humble circumstances',
        'Receiving supernatural aid for an impossible task',
        'Achieving success through pure luck without any personal effort',
      ],
      correctAnswer: 'Achieving success through pure luck without any personal effort',
      explanation: 'While "chosen one" heroes receive advantages (divine parentage, magical gifts), they still must demonstrate courage and make the choice to act. Perseus had to accept the quest, use the gifts wisely, and have the courage to face Medusa. The archetype combines destiny with personal heroism.',
      relatedLearningPoints: ['lp-perseus-6-call', 'lp-perseus-6-modern'],
    },
  ],
};
